GRANT SELECT ON BCPMS_OWNER.REQUEST TO ADMIN_PORTAL_OWNER;
GRANT SELECT ON BCPMS_OWNER.ITEM TO ADMIN_PORTAL_OWNER;
GRANT SELECT ON BCPMS_OWNER.VENDOR TO ADMIN_PORTAL_OWNER;
GRANT SELECT ON BCPMS_OWNER.ROUTE TO ADMIN_PORTAL_OWNER;
GRANT SELECT ON BCPMS_OWNER.LKUP_ROUTE_STATUS TO ADMIN_PORTAL_OWNER;
GRANT SELECT ON BCPMS_OWNER.LKUP_ROUTE_TYPE TO ADMIN_PORTAL_OWNER;
GRANT SELECT ON BCPMS_OWNER.NIST_USER TO ADMIN_PORTAL_OWNER;
