/*
 * File: app/view/AuditReportViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define("bcp.view.AuditReportViewController", {
    extend: "Ext.app.ViewController",
    alias: "controller.auditreport",

    onDownload: function (button, e, eOpts) {
        var record = this.getViewModel().get("record"),
            reqId = record.get("requestId");

        bcp.util.DownloadFile.download({
            method: "GET",
            url: "/empbc/v1/requests/" + reqId + "/auditReport"
        });
    },

    onSearch: function (button, e, eOpts) {
        var store = this.getStore("searchedRequests"),
            fileStore = Ext.getStore("RequestFiles"),
            refs = this.getReferences(),
            list = refs.list,
            fy = refs.comboFy.value,
            ouId = refs.comboOu.value,
            divisionId = refs.comboDiv.value,
            groupId = refs.comboGrp.value,
            requesterId = refs.comboEmp.value,
            reqNum = refs.reqNumTf.value,
            fromDate = Ext.Date.format(this.lookupReference("dateFrom").value, "Y-m-d"),
            toDate = Ext.Date.format(this.lookupReference("dateTo").value, "Y-m-d"),
            requestStatusId = refs.comboReqStatus.value;
        store.proxy.url = "/empbc/v1/requests?";
        //requestStatusId=10&ouId=13204&divisionId=13225&requesterId=23826
        //&fromDate=2017-05-30&toDate=2017-06-06&groupId=13316

        //clean previous result and selection if any
        list.setSelection(null);
        fileStore.removeAll();

        //build query
        if (fy) {
            store.proxy.url += "fy=" + fy + "&";
        }
        if (ouId) {
            store.proxy.url += "ouId=" + ouId + "&";
        }
        if (divisionId) {
            store.proxy.url += "divisionId=" + divisionId + "&";
        }
        if (groupId) {
            store.proxy.url += "groupId=" + groupId + "&";
        }
        if (requesterId) {
            store.proxy.url += "requesterId=" + requesterId + "&";
        }
        if (reqNum) {
            reqNum = bcp.util.CommonUtil.removeSafetySuffix(reqNum);
            store.proxy.url += "requisitionNumber=" + reqNum + "&";
        }
        if (fromDate && fromDate !== "") {
            store.proxy.url += "fromDate=" + fromDate + "&";
        }
        if (toDate && toDate !== "") {
            store.proxy.url += "toDate=" + toDate + "&";
        }
        if (requestStatusId) {
            store.proxy.url += "routeTypeId=" + requestStatusId + "&";
        }

        store.load();
    },

    onReset: function (button, e, eOpts) {
        Ext.suspendLayouts();
        var refs = this.getReferences(),
            tb1 = refs.filterTb1,
            tb2 = refs.filterTb2,
            fields = tb1.items.items,
            f,
            fLen = fields.length;

        for (f = 0; f < fLen; f++) {
            if (fields[f].xtype !== "button") {
                fields[f].reset();
            }
        }

        fields = tb2.items.items;
        fLen = fields.length;

        for (f = 0; f < fLen; f++) {
            if (fields[f].xtype !== "button") {
                fields[f].reset();
            }
        }

        Ext.resumeLayouts(true);
    },

    onSelect: function (rowmodel, record, index, eOpts) {
        var reqId = record.get("requestId"),
            fileStore = Ext.getStore("RequestFiles");

        fileStore.proxy.url = "/empbc/v1/requests/" + reqId + "/attachments";
        fileStore.load();
    },

    onReqNumChange: function (field, newValue, oldValue, eOpts) {
        var comboFy = this.lookupReference("comboFy");
        if (newValue && newValue.trim() !== "") {
            // If reqNumTf has a value, clear comboFy
            comboFy.clearValue(); // or comboFy.setValue(null);
        } else {
            // If reqNumTf is empty, set comboFy to current FY
            var currentFy = this.getCurrentFiscalYear();
            comboFy.setValue(currentFy);
        }
    },
    
    getCurrentFiscalYear: function() {
        var currentYear = new Date().getFullYear(), // yr in 4 digits
            currentFy = Number(currentYear.toString().slice(-2)), // yr in 2 digits
            // Assuming FY starts Oct 1st. Adjust timezone as needed for your server/client setup.
            // Using UTC to avoid local timezone issues, but ensure this matches your business logic.
            createNextFyEndDate = new Date(Date.UTC(currentYear, 9, 1)); // October is month 9 (0-indexed)

        // If today's date (in UTC) is on or after October 1st UTC, increment the FY
        if (new Date().getTime() >= createNextFyEndDate.getTime()) {
            currentFy++;
        }
        return currentFy;
    },

    onViewAdded: function (component, container, pos, eOpts) {
        var model = this.getViewModel(),
            loggedInUser = model.get("loggedInUser"),
            ouStore = this.getStore("ous"),
            divStore = this.getStore("divisions"),
            grpStore = this.getStore("groups"),
            empStore = this.getStore("bcEmployees"),
            ouId = 0;

        var currentFy = this.getCurrentFiscalYear(); // Use helper function

        //MB-464
        this.lookupReference("comboFy").setValue(currentFy);
        //detailee mode
        if (loggedInUser.detaileeMode == true) {
            ouId = Ext.getStore("Detailees").first().get("ouId");
        } else {
            ouId = loggedInUser.ouId;
        }

        if (!bcp.util.CommonUtil.isUserInRole(["App Admin"])) {
            //first, limit org filter to user's ou only
            ouStore.addFilter({operator: "==", property: "ouId", value: ouId});

            divStore.addFilter({operator: "==", property: "ouId", value: ouId});

            grpStore.addFilter({operator: "==", property: "ouId", value: ouId});

            //check user roles and setup filter fields (check LkUserRoles store for roles defined in NIST Org)
            if (
                !bcp.util.CommonUtil.isUserInRole([
                    "Director",
                    "Deputy Director",
                    "Administrative Officer",
                    "Senior Management Advisor",
                    "Laboratory Office Manager",
                    "Bankcard Approving Official"
                ])
            ) {
                divStore.addFilter({
                    operator: "==",
                    property: "divisionId",
                    value: loggedInUser.divisionId
                });

                if (
                    !bcp.util.CommonUtil.isUserInRole([
                        "Division Chief",
                        "Deputy Chief",
                        "Division Office Manager",
                        "Bankcard Holder",
                        "Administrative Office Assistant"
                    ])
                ) {
                    grpStore.addFilter({
                        operator: "==",
                        property: "groupId",
                        value: loggedInUser.groupId
                    });

                    if (!bcp.util.CommonUtil.isUserInRole(["Group Office Manager", "Group Leader"])) {
                        empStore.addFilter({
                            operator: "==",
                            property: "peopleId",
                            value: loggedInUser.peopleId
                        });
                    }
                }
            }
        }
    }
});
