/*
 * File: app/view/BchCommentWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.BchCommentWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.bchcommentwindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    config: {store: 'store'},

    modal: true,
    height: 214,
    width: 400,
    defaultFocus: 'noButton',
    layout: 'card',
    closable: false,
    defaultButton: 'noBtn',
    title: 'Save Comments',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            flex: 1,
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textareafield',
                    id: 'bchComments',
                    anchor: '100%',
                    reference: 'taComment',
                    fieldLabel: 'Bankcard Holder Comments',
                    labelAlign: 'top',
                    maxLength: 2000,
                    allowBlank: false,
                    allowOnlyWhitespace: false
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    defaultButtonUI: 'default',
                    layout: {type: 'hbox', pack: 'center'},
                    items: [
                        {
                            xtype: 'button',
                            reference: 'noBtn',
                            itemId: 'noButton',
                            width: 80,
                            text: 'Cancel',
                            listeners: {click: 'onNoButtonClick'}
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            width: 80,
                            text: 'Save',
                            listeners: {click: 'onSaveClick'}
                        }
                    ]
                }
            ]
        }
    ],

    onNoButtonClick: function (button, e, eOpts) {
        this.fireEvent('cancelComment');
    },

    onSaveClick: function (button, e, eOpts) {
        this.fireEvent('saveComment', this.query('textareafield')[0].value);
    }
});
