/*
 * File: app/view/ChangeRequesterWindowViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.ChangeRequesterWindowViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.changerequesterwindow',

    requires: [
        'Ext.data.ChainedStore',
        'Ext.util.Filter',
        'Ext.app.bind.Formula'
    ],

    stores: {
        bcEmployees: {
            source: 'OuAllStaffs',
            filters: {
                operator: '==',
                property: 'staffType',
                value: 'NIST Employee'
            }
        },
        bcAssociates: {
            source: 'OuAllStaffs',
            filters: {
                operator: '==',
                property: 'staffType',
                value: 'NIST Associate'
            }
        }
    },
    formulas: {
        forMe: {
            get: function (data) {
                if (!data || data === null) {
                    return false; //by default, enable and show the combo in UI
                } else {
                    return data.get('creatorId') === data.get('requesterId');
                }
            },
            bind: {bindTo: '{record}', deep: true}
        }
    }
});
