/*
 * File: app/view/DashBoard.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define("bcp.view.DashBoard", {
    extend: "Ext.container.Container",
    alias: "widget.bcpdashboard",

    requires: [
        "bcp.view.DashBoardViewModel",
        "bcp.view.DashBoardViewController",
        "Ext.toolbar.Toolbar",
        "Ext.form.field.ComboBox",
        "Ext.button.Button",
        "Ext.slider.Single",
        "Ext.ux.layout.ResponsiveColumn"
    ],

    controller: "bcpdashboard",
    viewModel: {type: "bcpdashboard"},
    anchor: "100%",
    flex: 1,
    scrollable: true,
    layout: {type: "vbox", align: "stretch"},
    listeners: {added: "onContainerAdded"},

    initConfig: function (instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: "toolbar",
                        dock: "top",
                        defaultButtonUI: "default",
                        enableOverflow: true,
                        overflowHandler: "menu",
                        items: [
                           
                            {
                                xtype: "combobox",
                                reference: "comboSubviews",
                                fieldLabel: "Available Subviews",
                                labelWidth: 80,
                                displayField: "displayText",
                                queryMode: "local",
                                store: "SubViews",
                                valueField: "routeId"
                            },
                            {
                                xtype: "button",
                                text: "Add",
                                listeners: {click: "onAddSubview"}
                            },
                            {
                                xtype: "slider",
                                reference: "sliderSubviewHeight",
                                width: 200,
                                fieldLabel: "Subview Height",
                                labelWidth: 80,
                                value: 299,
                                increment: 25,
                                maxValue: 500,
                                minValue: 200,
                                pageSize: 25,
                                listeners: {change: "onSliderChange"}
                            },
                            {
                                xtype: "slider",
                                reference: "comboPerRow",
                                width: 150,
                                fieldLabel: "Subview Per Row",
                                labelWidth: 80,
                                increment: 1,
                                maxValue: 2,
                                minValue: 1,
                                listeners: {change: "onViewPerRowChange"}
                            },
                            {
                                xtype: "button",
                                text: "Save Dashboard Settings",
                                listeners: {click: "onSaveSetting"}
                            }
                        ]
                    },
                    me.processRespContainer({
                        xtype: "container",
                        reference: "respContainer"
                    })
                ]
            };
        if (instanceConfig) {
            me.self.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processRespContainer: function (config) {
        config.layout = {
            type: "responsivecolumn",
            states: {small: 800, medium: 1600, large: 0}
        };
        return config;
    }
});
