/*
 * File: app/view/DashBoardViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.DashBoardViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.bcpdashboard',

    onAddSubview: function (button, e, eOpts) {
        var refs = this.getReferences(),
            selectedRouteId = refs.comboSubviews.value,
            respContainer = refs.respContainer,
            subView = {};

        if (selectedRouteId === null || refs[selectedRouteId]) {
            //subview is already in the dashboard, do nothing
        } else {
            subView = Ext.create({
                xtype: 'requestsdashview',
                viewType: selectedRouteId,
                reference: selectedRouteId,
                userCls: 'big-50 medium-100 small-100'
            });
            respContainer.add(subView);
        }
        this.onSaveSetting();
    },

    onSliderChange: function (slider, newValue, thumb, type, eOpts) {
        var container = this.lookupReference('respContainer'),
            items = container.items.items;
        for (var i = 0; i < items.length; i++) {
            items[i].setHeight(newValue);
        }
        this.onSaveSetting();
    },

    onViewPerRowChange: function (slider, newValue, thumb, type, eOpts) {
        var refs = this.getReferences(),
            ctn = refs.respContainer,
            width = ctn.getWidth();

        if (newValue === 1) {
            ctn.layout.config.states.medium = width * 2;
        } else if (newValue === 2) {
            ctn.layout.config.states.medium = width / 2 - 1;
        }
        //set the width one pixel higher or lower to trigger the view to re-render
        ctn.setWidth(width + 1);
        ctn.setWidth(width - 1);
        this.onSaveSetting();
    },

    onSaveSetting: function (button, e, eOpts) {
        var store = Ext.getStore('DashSettings'),
            refs = this.getReferences(),
            userHeight = refs.sliderSubviewHeight.getValue(),
            perRow = refs.comboPerRow.getValue(),
            ctn = refs.respContainer,
            items = ctn.items.items,
            arr = [],
            obj = {};
        store.removeAll();
        for (var i = 0; i < items.length; i++) {
            arr.push(items[i].viewType);
        }
        obj.viewPerRow = perRow;
        obj.viewHeight = userHeight;
        obj.subviews = arr;
        store.add(obj);
        store.sync();
    },

    onContainerAdded: function (component, container, pos, eOpts) {
        var store = Ext.getStore('DashSettings'),
            refs = this.getReferences(),
            model = this.getViewModel(),
            user = model.get('loggedInUser'),
            userHeight = 300,
            perRow = 2,
            ctn = refs.respContainer,
            width = 1600,
            items = [
                'requesttracking',
                'pendingrequests',
                'savedrequests',
                'preparedrequests',
                'archivedrequests'
            ];
        if (store.count() > 0) {
            var rec = store.first();
            userHeight = rec.get('viewHeight');
            items = rec.get('subviews');
            perRow = rec.get('viewPerRow');
        } else {
            //no user saved settings yet, try to see user's role and set some default settings
            //based on role
            if (user.staffType !== 'NIST Employee') {
                items = ['savedrequests', 'preparedrequests'];
            } else {
                items = ['requesttracking', 'pendingrequests'];
            }
        }

        refs.sliderSubviewHeight.setValue(userHeight);
        refs.comboPerRow.setValue(perRow);

        for (var i = 0; i < items.length; i++) {
            ctn.add({
                xtype: 'requestsdashview',
                viewType: items[i],
                reference: items[i],
                userCls: 'big-50 medium-100 small-100',
                height: userHeight
            });
        }

        //code to adjust the width settings of subviews
        if (perRow === 1) {
            ctn.layout.config.states.medium = width * 2;
        } else if (perRow === 2) {
            ctn.layout.config.states.medium = width / 2 - 1;
        }
        //set the width one pixel higher or lower to trigger the view to re-render
        ctn.setWidth(width + 1);
        ctn.setWidth(width - 1);
    }
});
