/*
 * File: app/view/FileAttachmentsViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define("bcp.view.FileAttachmentsViewController", {
    extend: "Ext.app.ViewController",
    alias: "controller.fileattachments",

    showView: function (view) {
        var layout = this.getView().getLayout();
        layout.setActiveItem(this.lookupReference(view));
    },

    add: function (button, e, eOpts) {
        var formPanel = this.getReferences().form,
            form = formPanel.getForm(),
            model = this.getViewModel(),
            newRecord = Ext.create("model.bcpfile", {
                requestId: model.get("generalInfo").get("requestId")
            });

        // Clear form
        form.reset();

        model.set("record", newRecord);

        // Set record
        form.loadRecord(newRecord);

        // Show form
        this.showView("form");
    },

    remove: function (button, e, eOpts) {
        var record = this.getViewModel().get("record"),
            fileId = record.get("fileId"),
            //fileCategory = record.get('categoryId'),
            store = this.lookupReference("list").store,
            url = "",
            me = this;

        /*if (fileCategory === 5) {
            Ext.Msg.alert("Warning",
                "The Shopping Cart File, which is linked with the Shopping Cart Item, cannot be removed from here. Please remove it from the Items grid");
            return;
        }*/

        // Ask user to confirm this action
        Ext.Msg.confirm("Confirm Delete", "Are you sure you want to delete this file attachment?", function (result) {
            // User confirmed yes
            if (result == "yes") {
                url = bcp.config.Runtime.getServerBaseUrl() + "attachments/" + fileId;
                var method = "DELETE";
                Ext.Ajax.request({
                    url: url,
                    method: method,
                    scope: this,
                    success: function (response) {
                        // reload store
                        store.reload();

                        // Display record
                        me.showView("list");
                    }
                });
            }
        });
    },

    onDownload: function (button, e, eOpts) {
        var record = this.getViewModel().get("record"),
            fileId = record.get("fileId");
        //issue 610
        if (fileId == -999) {
            var pdfUrl = "resources/files/IT_Buying_Service_IT_Compliance_in_Acquisition_Checklist_v5.0-NIST.pdf";
            // Create a new window to display the PDF
            Ext.Ajax.request({
                url: pdfUrl,
                method: "HEAD", // HEAD request only checks headers
                success: function (response) {
                    if (response.status === 200) {
                        // File exists
                        window.open(
                            pdfUrl,
                            "_blank",
                            "PrefilledITChecklist",
                            "width=600,height=520,resizable=yes,scrollbars=yes"
                        );
                    } else {
                        bcp.util.CommonUtil.showError("prefilled IT Checklist PDF file not found.");
                    }
                },
                failure: function (response) {
                    bcp.util.CommonUtil.showError(`Error accessing PDF file for ID: ${fileId}: ${response.statusText}`);
                }
            });
        } else {
            bcp.util.DownloadFile.download({
                method: "GET",
                url: "/empbc/v1/attachments/" + fileId
            });
        }
    },

    select: function (rowmodel, record, index, eOpts) {
        // Set selected record
        this.getViewModel().set("record", record);
    },

    onCategoryChange: function (field, newValue, oldValue, eOpts) {
        if (newValue && newValue === 3) {
            this.lookupReference("cateDesc").show();
        } else {
            this.lookupReference("cateDesc").hide();
        }
    },

    onFilefieldChange: function (filefield, value, eOpts) {
        if (value !== "") {
            var newValue = value.replace(/(^.*(\\|\/))?/, "");
            var v = new RegExp(".(jpg|gif|doc|docx|pdf|txt|xls|xlsx|csv)$", "i");
            var sizeInMB = filefield.fileInputEl.dom.files[0].size / (1024 * 1024);

            if (!v.test(newValue)) {
                Ext.Msg.alert("Validation Error ", "The file type is not allowed.");
                filefield.reset();
                return;
            }

            if (newValue.length > 200) {
                Ext.Msg.alert("Validation Error ", "The file name cannot be greater than 200 chars.");
                filefield.reset();
                return;
            }

            if (sizeInMB > 20) {
                Ext.Msg.alert("Validation Error ", "The file size is greater than 20MB.");
                filefield.reset();
                return;
            }

            filefield.setRawValue(newValue);
        }
    },

    cancel: function (button, e, eOpts) {
        this.showView("list");
    },

    upload: function (button, e, eOpts) {
        var refs = this.getReferences(),
            form = refs.form,
            list = refs.list,
            fileField = refs.fileLocation,
            model = this.getViewModel(),
            requestId = model.get("generalInfo").get("requestId"),
            url = bcp.config.Runtime.getServerBaseUrl() + "requests/" + requestId + "/attachment",
            me = this;

        if (form.isValid()) {
            //add a fake progress window first
            Ext.MessageBox.show({
                title: "Uploading File",
                progressText: "Please wait...",
                progress: true,
                closable: true
            });

            // Once the file is extracted, it will no longer be available in the field
            var fileInput = fileField.extractFileInput();
            var file = fileInput.files[0];

            //get other form data
            var jsdata = form.getValues();

            //convert file content to base64 string and put it to the data attribute in the jsdata
            bcp.util.CommonUtil.convertFileToBase64(file)
                .then(function (base64File) {
                    // This is required to remove the data url part -> data:*/*;base64,
                    var base64Data = base64File.split(",")[1];

                    jsdata.data = base64Data;

                    //add these data to jsondata
                    jsdata.name = file.name;
                    jsdata.type = file.type;

                    //make ajax call, server side code is also changed to take json instead of multiformdata
                    Ext.Ajax.request({
                        url: url,
                        method: "POST",
                        timeout: 0,
                        //headers: {'OWASP_TOKEN': token_value},
                        scope: this,
                        jsonData: jsdata,
                        success: function (response) {
                            Ext.MessageBox.hide();
                            var jsonResp = Ext.decode(response.responseText);
                            if (jsonResp.success) {
                                Ext.Msg.alert("Success", "Your File uploaded successfully.");
                                list.store.reload();
                                me.showView("list");
                            } else {
                                Ext.Msg.alert("Failure", "Unexpected error occurred. File was not uploaded.");
                            }
                        },
                        failure: function (response) {
                            Ext.MessageBox.hide();
                            Ext.Msg.alert("Failure", "Unexpected error occurred. File was not uploaded.");
                            return;
                        }
                    });
                })
                .catch(function () {
                    //in case file read has a problem
                    Ext.MessageBox.hide();
                    Ext.Msg.alert("Failure", "Unexpected error occurred. File was not uploaded.");
                });
        }
    },

    onFormShow: function (component, eOpts) {
        var refs = this.getReferences(),
            formPanel = refs.form,
            form = formPanel.getForm(),
            model = this.getViewModel(),
            record = model.get("record");
        // Clear form
        form.reset();
        // Set record
        form.loadRecord(record);
    },

    onWindowClose: function (panel, eOpts) {
        this.fireViewEvent("closeFileWindow", this.lookupReference("list").store.getCount());
    }
});
