/*
 * File: app/view/FileUploadForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.FileUploadForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.fileuploadform',

    requires: [
        'bcp.view.FileUploadFormViewModel',
        'bcp.view.FileUploadFormViewController',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Number',
        'Ext.form.field.File',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'fileuploadform',
    viewModel: {type: 'fileuploadform'},
    reference: 'form',
    flex: 1,
    defaults: {labelWidth: 145},
    bodyPadding: 10,

    items: [
        {
            xtype: 'displayfield',
            cls: 'bcp_notice',
            fieldLabel: 'Note',
            labelWidth: 60,
            value: 'Only the following file types are allowed: <b>.doc, .docx, .pdf, .jpg, .gif, .txt, .xls, .xlsx, and .csv</b>.  File size is limited to <b>20MB</b>.'
        },
        {
            xtype: 'hiddenfield',
            anchor: '100%',
            reference: 'requestIdHf',
            fieldLabel: 'Label',
            name: 'requestId',
            bind: {value: '{record.requestId}'}
        },
        /*{
            xtype: 'combobox',
            reference: 'vendorCombo',
            anchor: '100%',
            disabled: true,
            hidden: true,
            fieldLabel: 'Vendor (no longer needed)',
            name: 'vendorId',
            submitValue: false,
            allowBlank: false,
            allowOnlyWhitespace: false,
            anyMatch: true,
            displayField: 'name',
            forceSelection: true,
            minChars: 2,
            queryMode: 'local',
            valueField: 'vendorId'
        },*/
        /*{
            xtype: 'checkboxfield',
            anchor: '100%',
            fieldLabel: 'Contains Chemical?',
            name: 'isChemical',
            boxLabel: 'Yes',
            bind: {
                disabled: '{record.fileCategoryId!==5}',
                hidden: '{record.fileCategoryId!==5}',
                value: '{record.isChemical}'
            }
        },*/
        /*{
            xtype: 'numberfield',
            anchor: '50%',
            maxWidth: 300,
            minWidth: 250,
            fieldLabel: 'Total Amount',
            name: 'price',
            allowBlank: false,
            allowOnlyWhitespace: false,
            allowExponential: false,
            minValue: 0,
            bind: {
                disabled: '{record.fileCategoryId!==5}',
                hidden: '{record.fileCategoryId!==5}',
                value: '{record.price}',
                maxValue: '{purchaseLimit}'
            }
        },*/
        {
            xtype: 'hiddenfield',
            anchor: '40%',
            disabled: true,
            maxWidth: 300,
            minWidth: 200,
            fieldLabel: 'Quantity',
            name: 'quantity',
            bind: {value: '{record.quantity}'}
        },
        /*{
            xtype: 'hiddenfield',
            anchor: '100%',
            reference: 'hfFileCateId',
            fieldLabel: 'Label',
            name: 'fileCategoryId'
        },*/
        {
            xtype: 'combobox',
            formBind: false,
            reference: 'fileCateCombo',
            anchor: '100%',
            fieldLabel: 'File Category',
            name: 'fileCategoryId',
            allowBlank: false,
            allowOnlyWhitespace: false,
            displayField: 'name',
            forceSelection: true,
            queryMode: 'local',
            valueField: 'id',
            bind: {
                //disabled: '{record.fileCategoryId===5}',
                //hidden: '{record.fileCategoryId===5}',
                store: '{fileCategories}'
            },
            listeners: {change: 'onCategoryChange'}
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            reference: 'cateDesc',
            hidden: true,
            fieldLabel: 'Category Description',
            name: 'fileDescription',
            emptyText: 'Optionally enter a description',
            maxLength:100
        },
        {
            xtype: 'filefield',
            reference: 'fileLocation',
            anchor: '100%',
            fieldLabel: 'File Location',
            name: 'file',
            allowBlank: false,
            allowOnlyWhitespace: false,
            listeners: {change: 'onFilefieldChange'}
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            defaultButtonUI: 'default',
            layout: {type: 'hbox', pack: 'center'},
            items: [
                {xtype: 'button', text: 'Cancel', listeners: {click: 'cancel'}},
                {
                    xtype: 'button',
                    formBind: true,
                    text: 'Upload',
                    listeners: {click: 'upload'}
                }
            ]
        }
    ],
    listeners: {show: 'onFormShow'}
});
