/*
 * File: app/view/FinancePanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.FinancePanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.financepanel',

    onSplit: function (button, e, eOpts) {
        Ext.Msg.alert(
            'This is a place holder for a bankcard holder function, which is not implemented yet.'
        );
    },

    onApplyPtcToAllClick: function (button, e, eOpts) {
        var model = this.getViewModel(),
            reqId = model.get('generalInfo').get('requestId'),
            store = Ext.getStore('RequestItems');

        var ptcwindow = Ext.create('widget.ptcwindow', {
            reference: 'ptcwindow',
            store: store
        });
        //set event listeners
        ptcwindow.on({
            cancelPTC: {
                fn: function (data) {
                    ptcwindow.destroy();
                },
                scope: this,
                single: true
            }
        });
        ptcwindow.on({
            applyPTC: {
                fn: function (data) {
                    Ext.Ajax.request({
                        url:
                            bcp.config.Runtime.getServerBaseUrl() +
                            'requests/' +
                            reqId +
                            '/items/projectTask/' +
                            data,
                        method: 'PUT',
                        scope: this,
                        success: function (response) {
                            store.reload();
                            ptcwindow.destroy();
                        },
                        failure: function (response) {
                            store.reload();
                            ptcwindow.destroy();
                        }
                    });
                },
                scope: this,
                single: true
            }
        });

        //add to the parent view
        this.view.add(ptcwindow);

        // Show the window
        ptcwindow.show();
    },

    onApplyOcToAllClick: function (button, e, eOpts) {
        var model = this.getViewModel(),
            reqId = model.get('generalInfo').get('requestId'),
            store = Ext.getStore('RequestItems'),
            ocStore = this.getStore('objectClasses');

        var ocwindow = Ext.create('widget.ocwindow', {
            reference: 'ocwindow',
            store: ocStore
        });
        //set event listeners
        ocwindow.on({
            cancelOC: {
                fn: function (data) {
                    ocwindow.destroy();
                },
                scope: this,
                single: true
            }
        });
        ocwindow.on({
            applyOC: {
                fn: function (data) {
                    Ext.Ajax.request({
                        url:
                            bcp.config.Runtime.getServerBaseUrl() +
                            'requests/' +
                            reqId +
                            '/items/objectClass/' +
                            data,
                        method: 'PUT',
                        scope: this,
                        success: function (response) {
                            store.reload();
                            ocwindow.destroy();
                        },
                        failure: function (response) {
                            store.reload();
                            ocwindow.destroy();
                        }
                    });
                },
                scope: this,
                single: true
            }
        });

        //add to the parent view
        this.view.add(ocwindow);

        // Show the window
        ocwindow.show();
    },

    onCellEditingEdit: function (editor, context, eOpts) {
        //handles single PTC or OC update from the editor in the grid
        var rec = context.record,
            field = context.field,
            url = bcp.config.Runtime.getServerBaseUrl(),
            val = '';

        if (context.value && context.originalValue !== context.value) {
            val = context.value.trim();
            if (field === 'projTask') {
                var v = new RegExp('^[a-zA-Z0-9]{7}-[a-zA-Z0-9]{3}$', 'i');
                if (!v.test(val)) {
                    Ext.Msg.alert(
                        'Validation Error',
                        'A valid project task code should be in the xxxxxxx-xxx format where [x] is a alphanumeric character.'
                    );
                    context.record.reject();
                    return;
                }
                url += 'items/' + rec.data.itemId + '/projectTask/' + val;
            } else if (field === 'objectClass') {
                url += 'items/' + rec.data.itemId + '/objectClass/' + val;
            }

            Ext.Ajax.request({
                url: url,
                method: 'PUT',
                scope: this,
                success: function (response) {
                    rec.dirty = false;
                }
            });
        }
    },

    onViewAdded: function (component, container, pos, eOpts) {
        var refs = this.getReferences(),
            showTb = false;

        if (container.xtype == 'readonlyrequest' || component.readOnly) {
            showTb = false;
        } else {
            showTb = true;
        }

        //AOs, can edit it anytime they want even the request is in the readonly mode
        if (bcp.util.CommonUtil.isUserInRole(['Administrative Officer'])) {
            showTb = true;
        }

        if (showTb) {
            refs.tb.show();
        } else {
            refs.tb.hide();
        }
    }
});
