/*
 * File: app/view/FinancePanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.FinancePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.financepanel',

    requires: [
        'bcp.view.FinancePanelViewModel',
        'bcp.view.FinancePanelViewController',
        'Ext.form.field.Display',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.column.Number',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Boolean',
        'Ext.grid.plugin.CellEditing'
    ],

    controller: 'financepanel',
    viewModel: {type: 'financepanel'},
    reference: 'financePanel',
    scrollable: true,
    iconCls: 'fas fa-money-bill',
    title: 'Finance Data',

    config:{
        isInReadOnlyContext: false
    },

    dockedItems: [
        {
            xtype: 'displayfield', 
            cls: 'bcp_notice',
            dock: 'top',
            fieldLabel: 'Note',
            labelWidth: 60,
            value: '<ul><li>If you know the <b>Project Task & Object Class</b>, please enter them. Otherwise, you can skip this step.</li>'+
            '<li>If you are unsure what object class to use for a item, take a look at this <b><a href="Javascript: window.open(\'https://nistgov.atlassian.net/wiki/pages/viewpageattachments.action?pageId=14517297&sortBy=date&highlight=occ_guidance.pdf&&preview=/14517297/212107274/occ_guidance.pdf\')";>Object Class Code Guidance</a></b> document.</li>' +
            '</ul>'
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            reference: 'list', 
            resizable: false,
            title: '',
            forceFit: true,
            store: 'RequestItems',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    defaultButtonUI: 'default',
                    reference: 'tb',
                    items: [
                        {
                            xtype: 'button',
                            hidden: true,
                            text: 'Split Item',
                            bind: {disabled: '{list.selection}'},
                            listeners: {click: 'onSplit'}
                        },
                        {
                            xtype: 'button',
                            text: 'Apply PTC to All Items',
                            tooltip: 'apply PTC to all items',
                            bind: {hidden: '{!hasItem}'},
                            listeners: {click: 'onApplyPtcToAllClick'}
                        },
                        {
                            xtype: 'button',
                            text: 'Apply Object Class to All Items',
                            tooltip:
                                'apply an Object Class to all items listed in the grid',
                            bind: {hidden: '{!hasItem}'},
                            listeners: {click: 'onApplyOcToAllClick'}
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'itemId',
                    text: 'Item Id',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'requestId',
                    text: 'Request Id',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'vendorId',
                    text: 'Vendor Id'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    cellWrap: true,
                    dataIndex: 'vendorName',
                    text: 'Vendor Name'
                },
                {
                    xtype: 'gridcolumn',
                    maxWidth: 400,
                    minWidth: 200,
                    cellWrap: true,
                    dataIndex: 'itemName',
                    text: 'Item Name'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    cellWrap: true,
                    dataIndex: 'description',
                    text: 'Description'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    cellWrap: true,
                    dataIndex: 'catalogNumber',
                    text: 'Catalog Number'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    cellWrap: true,
                    dataIndex: 'purpose',
                    text: 'Purpose'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    minWidth: 80,
                    width: 80,
                    dataIndex: 'unitPrice',
                    text: 'Unit Price'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    minWidth: 80,
                    width: 60,
                    dataIndex: 'quantity',
                    text: 'Quantity',
                    format: '00'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function (
                        value,
                        metaData,
                        record,
                        rowIndex,
                        colIndex,
                        store,
                        view
                    ) {
                        return bcp.util.CommonUtil.moneyRenderer(
                            record.data.unitPrice * record.data.quantity
                        );
                    },
                    maxWidth: 130,
                    minWidth: 100,
                    width: 100,
                    cellWrap: true,
                    dataIndex: 'amount',
                    text: 'Amount'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function (
                        value,
                        metaData,
                        record,
                        rowIndex,
                        colIndex,
                        store,
                        view
                    ) {
                        return bcp.util.CommonUtil.moneyRenderer(
                            record.get('actualPrice') *
                                record.get('actualQuantity')
                        );
                    },
                    reference: 'aAmtCol',
                    hidden: true,
                    minWidth: 140,
                    align: 'end',
                    dataIndex: 'actualAmount',
                    text: '<b>Actual Amount</b>'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function (
                        value,
                        metaData,
                        record,
                        rowIndex,
                        colIndex,
                        store,
                        view
                    ) {
                        if (
                            view.ownerGrid.ownerCt.isInReadOnlyContext==true
                        ) {
                            return value;
                        } else {
                            if (value === null || value === '') {
                                return (
                                    'Add New ' +
                                    '<i class="fas fa-plus" aria-hidden="true"></i>'
                                );
                            } else {
                                return (
                                    value +
                                    ' <i class="fas fa-pencil-alt" aria-hidden="true"></i>'
                                );
                            }
                        }
                    },
                    maxWidth: 400,
                    minWidth: 200,
                    align: 'center',
                    cellWrap: true,
                    dataIndex: 'projTask',
                    text: 'Project Task',
                    editor: {
                        xtype: 'combobox',
                        reference: 'pjtskCombo',
                        anyMatch: true,
                        displayField: 'display',
                        minChars: 2,
                        queryMode: 'local',
                        queryParam: 'filter',
                        valueField: 'code',
                        bind: {
                            store: '{projectTasks}'
                        }
                    }
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function (
                        value,
                        metaData,
                        record,
                        rowIndex,
                        colIndex,
                        store,
                        view
                    ) {

                        if (
                            view.ownerGrid.ownerCt.isInReadOnlyContext==true
                        ) {
                            return value;
                        } else {
                            if (value === null || value === '') {
                                return (
                                    'Add New ' +
                                    '<i class="fas fa-plus" aria-hidden="true"></i>'
                                );
                            } else {
                                return (
                                    value +
                                    ' <i class="fas fa-pencil-alt" aria-hidden="true"></i>'
                                );
                            }
                        }
                    },
                    maxWidth: 400,
                    minWidth: 200,
                    align: 'center',
                    cellWrap: true,
                    dataIndex: 'objectClass',
                    text: 'Object Class',
                    editor: {
                        xtype: 'combobox',
                        reference: 'objclsCombo',
                        anyMatch: true,
                        displayField: 'display',
                        forceSelection: true,
                        minChars: 1,
                        queryMode: 'local',
                        queryParam: 'filter',
                        valueField: 'code',
                        bind: {
                            store: '{objectClasses}'
                        }
                    }
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    cellWrap: true,
                    dataIndex: 'unitIssue',
                    text: 'Unit Issue'
                },
                {
                    xtype: 'booleancolumn',
                    hidden: true,
                    maxWidth: 120,
                    minWidth: 100,
                    dataIndex: 'isShippingCost',
                    text: 'Is Chemical'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function (
                        value,
                        metaData,
                        record,
                        rowIndex,
                        colIndex,
                        store,
                        view
                    ) {},
                    hidden: true,
                    maxWidth: 160,
                    minWidth: 130,
                    cellWrap: true,
                    dataIndex: 'shoppingCartFileId',
                    text: 'Is Shopping Cart'
                }
            ],
            plugins: [
                {
                    ptype: 'cellediting',
                    clicksToEdit: 1,
                    listeners: {edit: 'onCellEditingEdit'}
                }
            ]
        }
    ],
    listeners: {added: 'onViewAdded'}
});
