/*
 * File: app/view/GeneralInfoPanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define("bcp.view.GeneralInfoPanelViewController", {
    extend: "Ext.app.ViewController",
    alias: "controller.generalinfopanel",

    checkReqStatus: function (statusCode) {
        var changeBtn = this.lookupReference("btnChangeRequester"),
            userCombo = this.lookupReference("onBehalfCombo");
        if (statusCode === 1 || statusCode === 12) {
            changeBtn.show();
        } else {
            changeBtn.hide();
            //don't want to have both the combo and the hidden field for requesterId
            if (userCombo) {
                userCombo.destroy();
            }
        }
    },

    loadForm: function (rec) {
        var refs = this.getReferences(),
            radioGrp = refs.requesterRg,
            onBehalfCombo = refs.onBehalfCombo,
            comboType = refs.comboType,
            form = refs.form;
        if (rec.data.creatorId !== rec.data.requesterId) {
            radioGrp.setValue({
                whoVal: "notme"
            });
        } else {
            radioGrp.setValue({
                whoVal: "self"
            });
        }
        form.loadRecord(rec);
        //for strange reason, the loadrecord above doesn't set value in this combo
        //so do it manually here
        if (onBehalfCombo) {
            onBehalfCombo.setValue(rec.data.requesterId);
        }
        comboType.setValue(rec.data.purchaseTypeId);
    },

    onTypeChange: function (field, newValue, oldValue, eOpts) {
        var model = this.getViewModel(),
            record = model.get("record");
        if (field.selection) {
            var sel = field.selection.data;
            //set requester and requestFor;
            record.set("purchaseTypeId", sel.id);
            if (sel.id === 2) {
                record.set("isItPurchase", "Y");
            } else {
                record.set("isItPurchase", "N");
            }
        }
    },

    onChangeRequester: function (button, e, eOpts) {
        this.redirectTo("#changerequester", true);
    },

    onReqForChange: function (field, newValue, oldValue, eOpts) {
        var record = this.getViewModel().get("record"),
            requesterIdHf = this.lookupReference("requesterIdHf");

        if (newValue) {
            if (newValue.whoVal === "notme") {
                //for new request
                if (record.data.requestId === 0) {
                    //make it zero
                    record.set("requesterId", -1);
                } else {
                    //this is a saved request if the record show the request is
                    //saved in DB as for self and user now changes it to not me, then
                    //we need to show the combo. if the record shows it's saved as not me
                    //the change here is just the record load, then we don't want to erase
                    //the value for the requestFor
                    if (record.data.creatorId === record.data.requesterId) {
                        this.lookupReference("onBehalfCombo").reset();
                        /*
                        if(this.lookupReference('onBehalfCombo').getValue()===null){
                        for(var i=1; i<tabs.length; i++){
                        tabs[i].disable();
                        }
                        }*/
                        record.set("requesterId", -1);
                    }

                    //in case user changed back and forward
                    /*if(record.data.creatorId!==record.data.requesterId){
                    //saved request record just loaded to the form
                    var bcUser=new bcp.model.BcUser({"fullName":record.data.requesterName,"peopleId":record.data.requestedForId});
                    this.lookupReference('onBehalfCombo').store.add(bcUser);
                    this.lookupReference('onBehalfCombo').setValue(bcUser);
                }*/
                }
                requesterIdHf.disable();
            } else {
                //make it the same as creator's id
                //record.set('requestedForId',record.get('creatorId'));
                record.set("requesterId", record.get("creatorId"));
                requesterIdHf.enable();
            }

            /*
        if(record.modified){
        //detect if the requesterId is changed
        if(record.modified.requesterId===undefined){
            //disable all tabs except the first one since we need the user to
            //save the request record on the first tab in order to make other tabs work
            //after the record is saved, we enable the other tabs
            if(record.data.requestId!==0){
                for(var i=1; i<tabs.length; i++){
                    tabs[i].enable();
                }
            }else{
                for(var i=1; i<tabs.length; i++){
                    tabs[i].disable();
                }
            }
        }else{
            for(var i=1; i<tabs.length; i++){
                tabs[i].disable();
            }
        }
    }*/
        }
    },

    onReqForComboChange: function (field, newValue, oldValue, eOpts) {
        var model = this.getViewModel(),
            record = model.get("record");
        if (field.selection) {
            var sel = field.selection.data;

            //set requester and requestFor;
            record.set("requesterId", sel.peopleId);
            record.set("requesterName", sel.displayName);
        }

        /*
        //detect if the requesterId is changed
        if(record.modified && record.modified.requesterId===undefined){
            //disable all tabs except the first one since we need the user to
            //save the request record on the first tab in order to make other tabs work
            //after the record is saved, we enable the other tabs
            if(record.data.requestId!==0){
                for(var i=1; i<tabs.length; i++){
                    tabs[i].enable();
                }
            }else{
                for(var i=1; i<tabs.length; i++){
                    tabs[i].disable();
                }
            }
        }else{
            for(var i=1; i<tabs.length; i++){
                tabs[i].disable();
            }
        }
        */
    },

    onHomeAddrDeliveryOptChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences(),
            title = "";
        //due to PII concern, if deliver to home, home address cannot be stored in the
        //system. Instead, once the request is at BCH, an email will be sent to the
        //requester to ask for where to deliver to
        if (newValue && newValue === true) {
            //title='Delivery Address (For Home Address: Full Address)';
            //refs.rgDelAddr.hide();
            refs.fsDelivAddr.hide();
            refs.taDelivAddr.disable();
            refs.dfHomeAddr.show();
        } else {
            title = "Delivery Address (For NIST Site: Location, Bldg and Office#. For Non NIST site: Full Address)";
            //refs.rgDelAddr.show();
            refs.fsDelivAddr.show();
            refs.taDelivAddr.enable();
            refs.dfHomeAddr.hide();
        }

        refs.fsDelivAddr.setTitle(title);
    },

    onDelAddrChange: function (field, newValue, oldValue, eOpts) {
        var model = this.getViewModel(),
            user = model.get("loggedInUser"),
            addr = this.lookupReference("taDelivAddr");
        if (newValue && newValue.addr === "grsd") {
            addr.setValue(
                "Attn: GRSD\n" + "NIST\n" + "Bldg 245/H113\n" + "100 Bureau Drive\n" + "Gaithersburg, MD 20899"
            );
        } else if (newValue && newValue.addr === "ncnr") {
            var reqRg = this.lookupReference("requesterRg").getValue().whoVal,
                name = "";
            if (reqRg === "self") {
                name = user.lastName + ", " + user.firstName;
            } else {
                var comboName = this.lookupReference("onBehalfCombo"),
                    rec = comboName.getSelectedRecord();
                if (rec) {
                    name = rec.get("fullName");
                }
            }
            addr.setValue(
                name +
                    "\n" +
                    "c/o NCNR Health Physics\n" +
                    "NIST\n" +
                    "Bldg 235/A134\n" +
                    "100 Bureau Drive\n" +
                    "Gaithersburg, MD 20899"
            );
        }
    },

    onPurchaseTypeAfterRender: function (field, eOpts) {
        // get the info icon element
        var infoIconEl = Ext.get("giPurchaseTypeInfoBtn");

        // add click listener to the info icon
        if (infoIconEl) {
            infoIconEl.on("click", function () {
                Ext.Ajax.request({
                    url: "resources/htmls/purchaseTypeDefinition.html", // Path to your HTML file
                    method: "GET",
                    success: function (response) {
                        var htmlContent = response.responseText;
                        // Create and open a new window with the HTML content
                        var popupWindow = window.open(
                            "",
                            "PurchaseTypeDefinition",
                            "width=600,height=250,resizable=yes,scrollbars=yes"
                        );
                        //Wait for the window to fully load before setting the content.
                        setTimeout(function() {
                            popupWindow.document.body.innerHTML = htmlContent;
                        }, 600);
                        //the write function is deprecated
                        //popupWindow.document.write(htmlContent);
                        //popupWindow.document.close();
                    },
                    failure: function (response) {
                        bcp.util.CommonUtil.showError("Failed to load Purchase Type Definition.");
                    }
                });
            });
        }
    },

    onMcCategoryChange: function (field, newValue, oldValue, eOpts) {
        var model = this.getViewModel(),
            record = model.get("record");
        if (field.selection) {
            var sel = field.selection.data;
            record.set("missionCriticalCategoryId", sel.id);
        }
    },

    onMcCategoryAfterRender: function (field, eOpts) {
        // get the info icon element
        var infoIconEl = Ext.get("giMcCategoryInfoBtn");

        // add click listener to the info icon
        if (infoIconEl) {
            infoIconEl.on("click", function () {
                Ext.Ajax.request({
                    url: "resources/htmls/missionCriticalDefinitions.html", // Path to your HTML file
                    method: "GET",
                    success: function (response) {
                        var htmlContent = response.responseText;
                        // Create and open a new window with the HTML content
                        var popupWindow = window.open(
                            "",
                            "MissionCriticalDefinitions",
                            "width=600,height=520,resizable=yes,scrollbars=yes"
                        );
                        setTimeout(function() {
                            popupWindow.document.body.innerHTML = htmlContent;
                        }, 600);
                        //the write function is deprecated
                        //popupWindow.document.write(htmlContent);
                        //popupWindow.document.close();
                    },
                    failure: function (response) {
                       bcp.util.CommonUtil.showError("Failed to load Purchase Type Definition.");
                    }
                });
            });
        }
    },

    onDownloadClick: function (button, e, eOpts) {
        var model = this.getViewModel(),
            record = model.get("record"),
            reqId = record.get("requestId");

        bcp.util.DownloadFile.download({
            method: "GET",
            url: "/empbc/v1/requests/" + reqId + "/requestSummaryReport"
        });
    },

    onEditMcDataClick: function (button, e, eOpts) {
        var me = this,
            model = this.getViewModel(),
            refs = this.getReferences(),
            form = refs.form,
            record = me.getViewModel().get("record"),
            reqId = record.get("requestId"),
            store = this.getStore("mcCategories");

        var editmcwindow = Ext.create("widget.editmissioncriticalwindow", {
            reference: "editmcwindow",
            store: store
        });
        //set event listeners
        editmcwindow.on({
            cancel: {
                fn: function (data) {
                    editmcwindow.destroy();
                },
                scope: this,
                single: true
            }
        });

        editmcwindow.on({
            save: {
                fn: function (data) {
                    //set value
                    record.set("missionCriticalCategoryId", data.missionCriticalCategoryId);
                    record.set("missionCriticalJustification", data.missionCriticalJustification);

                    //update request record
                    Ext.Ajax.request({
                        url: bcp.config.Runtime.getServerBaseUrl() + "requests/" + reqId,
                        method: "PUT",
                        scope: this,
                        jsonData: Ext.encode(record.data),
                        success: function (response) {
                            bcp.util.CommonUtil.ajaxSuccessHandler(response, function (result) {
                                record = Ext.create("bcp.model.BcpRequest", result.data);
                                model.set("record", record);
                                form.loadRecord(record);

                                editmcwindow.destroy();
                            });
                        }
                    });
                },
                scope: this,
                single: true
            }
        });

        var mcCategoryCombo = editmcwindow.down("#mcCategoryCombo");
        var mcJustificationTextArea = editmcwindow.down("#mcJustificationTextArea");

        mcCategoryCombo.setValue(record.get("missionCriticalCategoryId"));
        mcJustificationTextArea.setValue(record.get("missionCriticalJustification"));

        //add to the parent view
        this.view.add(editmcwindow);

        // Show the window
        editmcwindow.show();
    },

    //BANK-560
    //fix a UI confusion when a user select a RAM address option, then decide to remove it, there's no reset
    //button and the user can only remove the text manually and the selected option is still there
    //adding this reset button will reset both the textarea and the radio optionss
    onResetAddr: function (button, e, eOpts) {
        var addr = this.lookupReference("taDelivAddr"),
            rgDelAddr = this.lookupReference("rgDelAddr");
        rgDelAddr.reset();
        addr.reset();
    },

    onViewAdded: function (component, container, pos, eOpts) {
        var model = this.getViewModel(),
            user = model.get("loggedInUser"),
            userId = user.peopleId,
            form = this.getView().getForm(),
            refs = this.getReferences(),
            layout = this.view.getLayout(),
            today = new Date(),
            record = model.get("record"),
            newRecord = {},
            currentStatus = 0,
            isDynamic = 0,
            routeId = "";

        //limit the date range for needed by date
        refs.neededByDf.minValue = today;

        /*tomorrow = new Date(today),
        theDateAfterTomorrow=new Date(today);

        tomorrow.setDate(today.getDate()+1);
        theDateAfterTomorrow.setDate(today.getDate()+2);
        */

        //check request status
        if (record) {
            currentStatus = record.get("statusCode");
            //check if it's a dynamic route such as ITSO or AA, which might carry the same status as fixed route
            isDynamic = record.get("isDynamic");
        }
        //check which main view this component is in
        var routeOwner = this.getView().up("[routeId]");
        routeId = routeOwner ? routeOwner.routeId : "";

        //if view is read only, show readonly view
        if (component.readOnly) {
            layout.setActiveItem(1);
            //issue 618, give reviewer, DC and DR the ability to update mission critical category and justification
            //when they review requests in their pending action
            if (
                routeId == "pendingrequests" &&
                isDynamic == 0 &&
                (currentStatus == 5 || currentStatus == 17 || currentStatus == 18)
            ) {
                refs.btnEditMcData.show();
            } else {
                refs.btnEditMcData.hide();
            }
        } else {
            //if view is editable, show form view
            layout.setActiveItem(0);
            if (user.staffType === "NIST Associate") {
                newRecord = Ext.create("bcp.model.BcpRequest", {
                    requestId: 0,
                    creatorId: userId,
                    requestedForId: userId,
                    requesterId: user.bossId
                });
                refs.requesterIdHf.disable();
                refs.notmeRb.setBoxLabel("NIST Federal Employee");
            } else {
                newRecord = Ext.create("bcp.model.BcpRequest", {
                    requestId: 0,
                    creatorId: userId,
                    requestedForId: -1,
                    requesterId: userId
                });
            }
            model.set("record", newRecord);

            // Clear form
            form.reset();
            // Set record
            form.loadRecord(newRecord);

            //if associates try to do it for someone else, that someone must be a fed
            if (user.staffType === "NIST Associate") {
                refs.requesterRg.setValue({
                    whoVal: "notme"
                });
                refs.selfRb.hide();
                refs.selfRb.disable();
                refs.onBehalfCombo.setValue(newRecord.get("requesterId"));
            } else {
                refs.selfRb.show();
                refs.selfRb.enable();
                refs.requesterRg.setValue({
                    whoVal: "self"
                });
            }

            //even if the form is editable (administrative staff need edit after submission), 
            // unless the request is not submitted yet, cannot allow editing MCC and MCJ 
            if(![0,1,12].includes(currentStatus)){
                refs.comboMcCategory.setReadOnly(true);
                refs.mcJustification.setReadOnly(true);
            }
        }
    }
});
