/*
 * File: app/view/ItemPanelViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.ItemPanelViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.itempanel',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory',
        'Ext.data.field.Field',
        'Ext.util.Sorter',
        'Ext.data.ChainedStore',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    stores: {
        chemicalForms: {
            autoLoad: true,
            data: [{name: 'solid'}, {name: 'liquid'}, {name: 'gas'}],
            proxy: {type: 'memory'},
            fields: [{name: 'name'}]
        },
        chemicalContainerTypes: {
            autoLoad: true,
            model: 'bcp.model.LookUpData',
            data: [
                {id: 1, name: 'Plastic bottle'},
                {id: 2, name: 'Steel drum'},
                {id: 3, name: 'Glass bottle or jug'},
                {id: 4, name: 'Bag'},
                {id: 5, name: 'Box'},
                {id: 6, name: 'Can'},
                {id: 7, name: 'Cylinder'},
                {id: 8, name: 'Fiber drum'},
                {id: 9, name: 'Plastic or non-metal drum'}
            ],
            proxy: {type: 'memory'},
            sorters: {property: 'name'}
        },
        itemStatuses: {source: 'LkItemStatus'},
        bcUsers: {source: 'OuAllStaffs'},
        bcUsers2: {source: 'OuAllStaffs'},
        bcpChemItems: {
            model: 'bcp.model.ChemicalItem',
            proxy: {
                type: 'ajax',
                url: '/empbc/v1/items/',
                reader: {type: 'json', rootProperty: 'data'}
            }
        }
    }
});
