/*
 * File: app/view/ItemPanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.ItemPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.itempanel',

    showView: function (view) {
        var layout = this.view.getLayout(),
            refs = this.getReferences(),
            list = refs.list,
            form = refs.form.getForm(),
            chemicalform = refs.chemicalform.getForm(),
            model = this.getViewModel();
        if (view == 'list') {
            list.setSelection(null);
            form.reset();
            chemicalform.reset();
            model.set(
                'iRecord',
                Ext.create('model.bcpitem', {
                    itemId: 0,
                    requestId: model.get('generalInfo').get('requestId')
                })
            );
        }
        layout.setActiveItem(this.lookupReference(view));
        Ext.getStore('LkItemStatus').load();
    },

    saveItem: function (saveAndAdd) {
        var store = Ext.getStore('RequestItems'),
            refs = this.getReferences(),
            form = refs.form.getForm(),
            record = form.getRecord(),
            url = '',
            me = this;

        // Valid
        if (form.isValid()) {
            // Update associated record with values
            form.updateRecord();

            //decide if it's a insert or update
            url = bcp.config.Runtime.getServerBaseUrl() + 'items';
            var method = 'POST';

            //update
            if (record.data.itemId !== 0) {
                method = 'PUT';
                url = url + '/' + record.data.itemId;
            } else {
                //new item, make actuals the same as estimates
                record.set('actualQuantity', record.data.quantity);
                record.set('actualPrice', record.data.unitPrice);
            }

            //for non shopping cart chemcial item
            if (
                record.data.isChemical &&
                record.data.shoppingCartFileId === 0
            ) {
                var chemForm = refs.chemicalform.getForm(),
                    chemRecord = chemForm.getRecord();
                //check if chemrecord is undefined. if the item was saved as a non chem item
                //and later update to chem item, the record is not set in the chem form yet
                if (!chemRecord) {
                    chemRecord = Ext.create('model.chemicalitem', {
                        itemId: record.get('itemId')
                    });
                    chemForm.loadRecord(chemRecord);
                }
                chemForm.updateRecord();

                //based on Andrea's change on 8/5/19, remove duplicate field
                //and make the item's catalog and quantity the same as chemical item
                chemRecord.data.chemicalCatalogNumber =
                    record.data.catalogNumber;
                chemRecord.data.quantityOfCatalogNumber = record.data.quantity;

                record.data.chemicalData = chemRecord.data;

                //MB-468 only validate catalogNumber when it's ibbr chemcial because it's required for ibbr api call
                var ibbrRoomId = record.get('ibbrRoomId');
                if (ibbrRoomId != null && ibbrRoomId.trim().length > 0) {
                    if (
                        record.get('catalogNumber') == null ||
                        record.get('catalogNumber').trim().length == 0
                    ) {
                        Ext.Msg.alert(
                            'Validation Error',
                            'Please enter [Catalog/Item Number] for chemical item used by IBBR.'
                        );
                        refs.tfCatalog.focus();
                        return;
                    }
                }
            }

            if (saveAndAdd) {
                Ext.Ajax.request({
                    url: url,
                    method: method,
                    jsonData: Ext.encode(record.data),
                    scope: this,
                    success: function (response) {
                        Ext.Msg.alert('Confirmation', 'Item Saved.');
                        store.reload();
                        me.add();
                    }
                });
            } else {
                //save it to the DB
                Ext.Ajax.request({
                    url: url,
                    method: method,
                    jsonData: Ext.encode(record.data),
                    scope: this,
                    success: function (response) {
                        Ext.Msg.alert('Confirmation', 'Item Saved.');
                        store.reload();
                        // Display record
                        me.showView('list');
                        this.fireViewEvent('showbbar');
                    }
                });
            }
        }
    },

    updatePurchasedItem: function (fieldName, newValue, action) {
        var model = this.getViewModel(),
            rec = model.get('iRecord'),
            store = Ext.getStore('RequestItems'),
            url =
                bcp.config.Runtime.getServerBaseUrl() +
                'items/' +
                rec.data.itemId +
                '/' +
                action,
            obj = {};
        //me = this;

        obj[fieldName] = newValue;

        if (rec.get(fieldName) !== newValue) {
            Ext.Ajax.request({
                url: url,
                method: 'PUT',
                jsonData: Ext.encode(obj),
                scope: this,
                success: function (response) {
                    store.reload();
                }
            });
        }
    },

    onRequestReapproval: function (button, e, eOpts) {
        var model = this.getViewModel(),
            req = Ext.getStore('CurrentRequest').first(),
            reqId = req.get('requestId'),
            actualTotal = model.get('actualTotal'),
            approvedAmount = req.get('approvalAmount'),
            me = this;

        if (actualTotal > 0) {
            actualTotal = actualTotal.toFixed(2);
        }
        if (approvedAmount > 0) {
            approvedAmount = approvedAmount.toFixed(2);
        }

        if (
            parseFloat(approvedAmount) > 0 &&
            parseFloat(approvedAmount) < parseFloat(actualTotal)
        ) {
            //MB-428 manual trigger the popup by BCH and condition met
            var newRoute = Ext.create('bcp.model.RequestRoute', {
                requestId: reqId,
                statusId: 6
            });
            newRoute.set('typeId', 2);
            newRoute.set('routeTo', req.get('bankcardApprovingOfficialId'));
            newRoute.set('routeToName', req.get('baoName'));
            newRoute.set('routeToName', req.get('baoName'));
            newRoute.set(
                'notes',
                'The total cost: $' +
                    actualTotal +
                    ', exceeds the approved amount: $' +
                    approvedAmount +
                    '. Route back to the Bankcard Approving Offcial for Re-approval'
            );
            // Ask user to confirm this action
            Ext.Msg.confirm(
                'Re-approval Confirmation',
                'The total cost of the request is $' +
                    actualTotal +
                    ', which is more than the approved amount of $' +
                    approvedAmount +
                    '. Do you want to route this request to the Bankcard Approving Official for re-approval?',
                function (result) {
                    // User confirmed yes
                    if (result == 'yes') {
                        Ext.Ajax.request({
                            url:
                                bcp.config.Runtime.getServerBaseUrl() +
                                'routes',
                            method: 'POST',
                            jsonData: Ext.encode(newRoute.data),
                            scope: this,
                            success: function (response) {
                                bcp.util.CommonUtil.ajaxSuccessHandler(
                                    response,
                                    function (result) {
                                        Ext.Msg.alert(
                                            'Success',
                                            'Your request was routed successfully.'
                                        );
                                        me.redirectTo('purchases', true);
                                    }
                                );
                            },
                            failure: function (response) {
                                Ext.Msg.alert(
                                    'Failed',
                                    response.result.statusText
                                );
                            }
                        });
                    }
                }
            );
        } else {
            Ext.Msg.alert(
                'Action not Needed',
                'The total cost of the request is $' +
                    actualTotal +
                    ', which is not more than the approved amount of $' +
                    approvedAmount +
                    '. You do not need to route this request to the Bankcard Approving Official for re-approval.'
            );
        }
    },

    add: function (button, e, eOpts) {
        var refs = this.getReferences(),
            model = this.getViewModel(),
            formPanel = refs.form,
            form = formPanel.getForm(),
            chemicalform = refs.chemicalform.getForm(),
            //    vendors = Ext.getStore('RequestVendors'),
            newRecord = Ext.create('model.bcpitem', {
                itemId: 0,
                requestId: model.get('generalInfo').get('requestId')
            }),
            chemRecord = Ext.create('model.chemicalitem', {itemId: 0});

        //if at least one vendor, auto select it for user per item (no need now)
        //if(vendors.getRange().length>=1){
        //    newRecord.set('vendorId',vendors.first().get('vendorId'));
        //}

        model.set('iRecord', newRecord);
        model.set('chemrecord', chemRecord);
        // Clear form
        form.reset();
        chemicalform.reset();
        // Set record
        form.loadRecord(newRecord);
        chemicalform.loadRecord(chemRecord);

        // Set title
        formPanel.setTitle('Add Item');

        refs.saveAndAddBtn.enable();

        // Show form
        this.showView('form');
        this.fireViewEvent('hidebbar');
    },

    editCredit: function (button, e, eOpts) {
        var cwindow = this.lookupReference('itemcreditwindow');
        var found = false;

        var store = Ext.getStore('RequestItems'),
            records = store.data;

        for (var i = 0; i < records.length; i++) {
            if (records.getAt(i).data.vendorId == '-9999') {
                cwindow
                    .queryById('itemId')
                    .setValue(records.getAt(i).data.itemId);
                var unitP = records.getAt(i).data.unitPrice;
                if (unitP < 0) unitP = -unitP;
                cwindow.queryById('unitPrice').setValue(unitP);
                cwindow
                    .queryById('projTask')
                    .setValue(records.getAt(i).data.projTask);
                found = true;
                //console.log ('found, itemId = ' + records.getAt(i).data.itemId + ', unitPrice = ' + records.getAt(i).data.unitPrice);
                break;
            }
        }

        //calculate the actual total
        var actualTotal = 0;
        for (i = 0; i < records.length; i++) {
            //if (records.getAt(i).data.vendorId < 1) actualTotal += records.getAt(i).data.unitPrice;
            //else actualTotal += records.getAt(i).data.unitPrice * records.getAt(i).data.quatity;
            actualTotal += records.getAt(i).data.actualAmount;
        }

        //console.log (actualTotal);
        cwindow.queryById('unitPrice').setBind({maxValue: '' + actualTotal});

        if (!found) {
            cwindow.queryById('itemId').setValue(0);
            cwindow.queryById('unitPrice').setValue(0);
        }
        // Show the window
        cwindow.show();
        this.fireViewEvent('hidebbar');
    },

    addShipping: function (button, e, eOpts) {
        var scwindow = this.lookupReference('shippingcostwindow');
        scwindow.queryById('itemId').setValue(0);
        scwindow.queryById('unitPrice').setValue(0);
        // Show the window
        scwindow.show();
        this.fireViewEvent('hidebbar');
    },

    /*MB-462 
      uploadCart: function (button, e, eOpts) {
          var model = this.getViewModel(),
              store = Ext.getStore('RequestItems'),
              fileStore = Ext.getStore('RequestFiles'),
              //vendorStore=Ext.getStore('RequestVendors'),
              reqId = model.get('generalInfo').get('requestId'),
              formWindow = Ext.create('Ext.window.Window', {
                  modal: true,
                  height: 320,
                  width: 480,
                  closable: false,
                  title: 'Upload Shopping Cart',

                  layout: {
                      type: 'vbox',
                      align: 'stretch'
                  }
              }),
              form = Ext.create('widget.fileuploadform'),
              newRecord = Ext.create('model.bcpfile', {
                  'requestId': reqId,
                  'fileCategoryId': 5
              }),
              me = this;


          //set record
          form.lookupController().getViewModel().set('record', newRecord);
          //bind vendor store (no need now)
          //form.lookupController().lookupReference('vendorCombo').bindStore(vendorStore);
          //load record
          form.getForm().loadRecord(newRecord);
          //set event listeners
          form.on({
              'cancelUpload': {
                  fn: function (win, data) {
                      formWindow.destroy();
                      me.fireViewEvent('showbbar');
                  },
                  scope: this,
                  single: true
              }
          });
          form.on({
              'uploaded': {
                  fn: function (win, data) {
                      formWindow.destroy();
                      store.reload();
                      fileStore.reload();
                      me.fireViewEvent('showbbar');
                  },
                  scope: this,
                  single: true
              }
          });
          //add form to window
          formWindow.add(form);
          //add window to view
          this.view.add(formWindow);
          //show window
          formWindow.show();
          this.fireViewEvent('hidebbar');
      },*/

    edit: function (button, e, eOpts) {
        var refs = this.getReferences(),
            model = this.getViewModel(),
            formPanel = refs.form,
            form = formPanel.getForm(),
            chemicalform = this.lookupReference('chemicalform').getForm(),
            record = model.get('iRecord'),
            chemStore = model.get('bcpChemItems'),
            chemRecord = Ext.create('model.chemicalitem', {itemId: 0});

        //this handles non shopping cart item edit
        if (record.data.shoppingCartFileId === 0) {
            //check if it's a shipping item
            if (record.data.isShippingCost) {
                if (button.text === 'View') {
                    //in view mode, no need to view shipping window since it's just a cost with no other info
                    return;
                }
                var scwindow = this.lookupReference('shippingcostwindow');
                scwindow.queryById('unitPrice').setValue(record.data.unitPrice);
                scwindow.queryById('itemId').setValue(record.data.itemId);
                scwindow.queryById('projTask').setValue(record.data.projTask);
                // Show the window
                scwindow.show();
            } else {
                // Load record model into form
                form.loadRecord(record);
                //if it's an chem item, get chemical item data and load it in the chemical item form
                if (record.data.isChemical) {
                    chemStore.proxy.url =
                        '/empbc/v1/items/' + record.data.itemId;
                    chemStore.load({
                        scope: this,
                        callback: function (records, operation, success) {
                            if (success && records.length > 0) {
                                model.set('chemrecord', records[0]);
                                //chemicalform.reset();
                                chemicalform.loadRecord(records[0]);
                            }
                        }
                    });
                } else {
                    //chemicalform.reset();
                    chemicalform.loadRecord(chemRecord);
                    model.set('chemrecord', chemRecord);
                }

                // Set title
                formPanel.setTitle(button.text + ' Item');
                refs.saveAndAddBtn.disable();

                // Show form
                this.showView('form');
            }
            this.fireViewEvent('hidebbar');
        } else {
            //disabled the edit button so shopping cart item could not get an edit
        }
    },

    updateStatuses: function (button, e, eOpts) {
        var model = this.getViewModel(),
            reqId = model.get('generalInfo').get('requestId'),
            store = Ext.getStore('RequestItems');

        var window = Ext.create('widget.itemstatuseswindow', {
            reference: 'itemstatuseswindow',
            store: store
        });

        var grid = window.query('gridpanel')[0];
        grid.bindStore(store);

        //set event listeners
        window.on({
            cancelStatusUpdate: {
                fn: function (data) {
                    window.destroy();
                },
                scope: this,
                single: true
            }
        });
        window.on({
            applyStatusUpdate: {
                fn: function (data) {
                    Ext.Ajax.request({
                        url:
                            bcp.config.Runtime.getServerBaseUrl() +
                            'requests/' +
                            reqId +
                            '/insertItemStatusTypes/',
                        method: 'POST',
                        jsonData: Ext.encode(data),
                        scope: this,
                        success: function (response) {
                            store.reload();
                            window.destroy();
                        },
                        failure: function (response) {
                            store.reload();
                            window.destroy();
                        }
                    });
                },
                scope: this,
                single: true
            }
        });

        //add to the parent view
        this.view.add(window);

        // Show the window
        window.show();
    },

    onPartialDelivery: function (button, e, eOpts) {
        var model = this.getViewModel(),
            store = Ext.getStore('RequestItems'),
            record = model.get('iRecord'),
            itemId = record.get('id');

        if (record.get('isShippingCost')) {
            Ext.Msg.alert(
                'Warning',
                'you cannot use partial delivery function on Shipping Cost.'
            );
            return;
        }

        if (record.get('shoppingCartFileId') > 0) {
            Ext.Msg.alert(
                'Warning',
                'The system currently cannot support partial delivery function on a Shopping Cart Item.'
            );
            return;
        }

        var window = Ext.create('widget.partialdeliverywindow', {
            reference: 'partialdeliverywindow'
        });

        //set event listeners
        window.on({
            cancelPartialDelivery: {
                fn: function (data) {
                    window.destroy();
                },
                scope: this,
                single: true
            }
        });
        window.on({
            applyPartialDelivery: {
                fn: function (data) {
                    Ext.Ajax.request({
                        url:
                            bcp.config.Runtime.getServerBaseUrl() +
                            'items/' +
                            itemId +
                            '/partialDelivery',
                        method: 'PUT',
                        jsonData: Ext.encode({deliveredQuantity: data}),
                        scope: this,
                        success: function (response) {
                            bcp.util.CommonUtil.ajaxSuccessHandler(
                                response,
                                function (result) {
                                    store.reload();
                                    window.destroy();
                                }
                            );
                        },
                        failure: function (response) {
                            store.reload();
                            window.destroy();
                        }
                    });
                },
                scope: this,
                single: true
            }
        });

        //add to the parent view
        this.view.add(window);

        // Show the window
        window.show();
    },

    remove: function (button, e, eOpts) {
        var model = this.getViewModel(),
            store = Ext.getStore('RequestItems'),
            fileStore = Ext.getStore('RequestFiles'),
            record = model.get('iRecord'),
            hasFile = record.data.shoppingCartFileId > 0,
            url = '',
            me = this;

        if (record.data.vendorId == -9999) {
            if (!bcp.util.CommonUtil.isUserInRole(['Bankcard Holder'])) {
                Ext.Msg.alert(
                    'Warning',
                    'Only bankcard holder can remove this credit item.'
                );
                return;
            }
        }

        // Ask user to confirm this action
        Ext.Msg.confirm(
            'Confirm Delete',
            'Are you sure you want to delete this item?',
            function (result) {
                // User confirmed yes
                if (result == 'yes') {
                    url =
                        bcp.config.Runtime.getServerBaseUrl() +
                        'items/' +
                        record.data.itemId;
                    var method = 'DELETE';
                    Ext.Ajax.request({
                        url: url,
                        method: method,
                        scope: this,
                        params: {fileId: record.data.shoppingCartFileId},
                        success: function (response) {
                            // reload store
                            store.reload();
                            //reload file store if shopping cart file removed
                            if (hasFile) {
                                fileStore.reload();
                            }
                            // Display record
                            me.showView('list');
                        }
                    });
                }
            }
        );
    },

    onPriceEditorBlur: function (component, event, eOpts) {
        this.updatePurchasedItem('actualPrice', component.value, 'process');
    },

    onQtEditorBlur: function (component, event, eOpts) {
        this.updatePurchasedItem('actualQuantity', component.value, 'process');
    },

    onItemStatusChange: function (field, newValue, oldValue, eOpts) {
        this.updatePurchasedItem('itemStatusTypeId', newValue, 'process');
    },

    onItemNoteChange: function (component, event, eOpts) {
        this.updatePurchasedItem('itemNotes', component.value, 'process');
    },

    onReceivedDateChange: function (field, newValue, oldValue, eOpts) {
        this.updatePurchasedItem(
            'dateReceived',
            newValue.toISOString(),
            'process'
        );
    },

    onStatementDateChange: function (field, newValue, oldValue, eOpts) {
        this.updatePurchasedItem(
            'statementDate',
            newValue.toISOString(),
            'billed'
        );
    },

    onTransactionNumberChange: function (component, event, eOpts) {
        this.updatePurchasedItem(
            'transactionNumber',
            component.value,
            'billed'
        );
    },

    select: function (rowmodel, record, index, eOpts) {
        // Set selected record
        this.getViewModel().set('iRecord', record);
    },

    save: function (button, e, eOpts) {
        this.saveItem(false);
    },

    saveAndAdd: function (button, e, eOpts) {
        this.saveItem(true);
    },

    cancelEdit: function (button, e, eOpts) {
        // Show details
        this.showView('list');
        this.fireViewEvent('showbbar');
    },

    onIsChemicalChange: function (field, newValue, oldValue, eOpts) {
        var chemForm = this.lookupReference('chemicalform');
        if (newValue) {
            chemForm.show();
            chemForm.enable();
        } else {
            chemForm.hide();
            chemForm.disable();
        }
    },

    onResetIbbrRoomClick: function (button, e, eOpts) {
        var model = this.getViewModel(),
            chemForm = this.getReferences().chemicalform.getForm(),
            chemRecord = model.get('chemrecord');

        chemForm.updateRecord();
        chemRecord.set('ibbrRoomName', '');
        chemRecord.set('ibbrRoomId', '');
        chemForm.loadRecord(chemRecord);

        return;
    },

    onIbbrRoomClick: function (button, e, eOpts) {
        var model = this.getViewModel(),
            store = Ext.getStore('RequestItems'),
            refs = this.getReferences();

        var ibbrwindow = Ext.create('widget.ibbrroomtreewindow', {
            reference: 'ibbrwindow',
            store: store
        });

        //set event listeners
        ibbrwindow.on({
            cancelIbbr: {
                fn: function (data) {
                    ibbrwindow.destroy();
                },
                scope: this,
                single: true
            }
        });
        ibbrwindow.on({
            applyIbbr: {
                fn: function (v, c, data) {
                    var form = refs.form.getForm(),
                        record = form.getRecord(),
                        chemForm = this.getReferences().chemicalform.getForm(),
                        chemRecord = model.get('chemrecord');
                    //check if chemrecord is undefined. if the item was saved as a non chem item
                    //and later update to chem item, the record is not set in the chem form yet
                    if (!chemRecord) {
                        chemRecord = Ext.create('model.chemicalitem', {
                            itemId: record.get('itemId')
                        });
                    }
                    chemForm.updateRecord();
                    chemRecord.set('ibbrRoomName', data.text);
                    chemRecord.set('ibbrRoomId', data.id);
                    chemForm.loadRecord(chemRecord);

                    ibbrwindow.destroy();
                },
                scope: this,
                single: true
            }
        });

        //add to the parent view
        this.view.add(ibbrwindow);
        // Show the window
        ibbrwindow.show();
    },

    onViewBeforeShow: function (component, eOpts) {
        var refs = this.getReferences(),
            model = this.getViewModel(),
            req = model.get('generalInfo').data,
            status = req.statusCode;

        //always show the list view first
        this.showView('list');

        //for requests that are processed, completed, archived, show actuals
        if (status == 8 || status == 9 || status == 13) {
            refs.aPriceCol.show();
            refs.aQtCol.show();
            refs.aAmtCol.show();
            refs.statusCol.show();
            refs.statementDateCol.show();
            refs.transactionNumberCol.show();
        } else {
            refs.aPriceCol.hide();
            refs.aQtCol.hide();
            refs.aAmtCol.hide();
            refs.statusCol.hide();
            refs.statementDateCol.hide();
            refs.transactionNumberCol.hide();
        }

        //item note and recieved date are for BH used when request status is 8, 9
        //MB-437 since item editors for item status is bind to [isPurchase] and cannot be granted
        //to AO (because it would give AO purchase view access), I removed the bind to [isPurchase]
        //for the updtItemStatusBtn instead and add AO check below which allow AO to use this button
        //to update status
        //MB-447 added 13 "received" for AOs to update status to EA
        if (status == 8 || status == 9 || status == 13) {
            refs.itemNoteCol.show();
            refs.receivedDateCol.show();
            if (
                bcp.util.CommonUtil.isUserInRole([
                    'Bankcard Holder',
                    'Administrative Officer'
                ])
            ) {
                refs.updtItemStatusBtn.show();
            }
        } else {
            refs.itemNoteCol.hide();
            refs.receivedDateCol.hide();
            //if not processed or completed, then the editors in the grid for BH functions
            //should be readonly
            //model.set('isBH',false);
        }

        //if (!model.get ('isBH')) refs.creditBtn.hide ();
        //if (!bcp.util.CommonUtil.isUserInRole(["Bankcard Holder", "Bankcard Approving Official"])) refs.creditBtn.hide();
        if (
            (status != 8 && status != 9) ||
            !bcp.util.CommonUtil.isUserInRole(['Bankcard Holder'])
        ) {
            refs.creditBtn.hide();
        }
    },

    onViewAdded: function (component, container, pos, eOpts) {
        var model = this.getViewModel(),
            store = Ext.getStore('RequestItems'),
            refs = this.getReferences(),
            list = refs.list,
            me = this;

        //prevent these buttons to show in new request when buttons were in menu
        if (container.xtype == 'newrequest') {
            refs.updtItemStatusBtn.destroy();
            refs.partialDeliveryBtn.destroy();
        }

        model.set('iRecord', null);

        //when view is created, determine if it's readonly or editable
        if (container.xtype == 'readonlyrequest' || component.readOnly) {
            //if read only, hide all buttons except the edit from the toolbar
            component.query('toolbar')[0].items.items.forEach(function (comp) {
                if (comp.text !== 'Edit') {
                    comp.hide();
                } else {
                    comp.text = 'View';
                }
            });
            //hide the save button on the form and rename the cancel button
            component.query('toolbar')[1].items.items.forEach(function (comp) {
                if (comp.text !== 'Cancel') {
                    comp.hide();
                } else {
                    comp.text = 'Go Back';
                }
            });
            //made all form fields readonly
            bcp.util.CommonUtil.makeFormReadOnly(
                this.lookupReference('form').form,
                true
            );
            bcp.util.CommonUtil.makeFormReadOnly(
                this.lookupReference('chemicalform').form,
                true
            );
        }

        var cwindow = Ext.create('widget.itemcreditwindow', {
            reference: 'itemcreditwindow'
        });
        //set event listeners
        cwindow.on({
            cancelC: {
                fn: function (data) {
                    cwindow.hide();
                    me.fireViewEvent('showbbar');
                },
                scope: this
            }
        });

        cwindow.on({
            saveC: {
                fn: function (data) {
                    var me = this,
                        model = this.getViewModel(),
                        url = bcp.config.Runtime.getServerBaseUrl() + 'items',
                        method = 'POST',
                        newRecord = null;
                    //create and add default values for the record
                    newRecord = Ext.create('model.bcpitem', {
                        itemId: 0,
                        itemName: 'Credit',
                        vendorId: -9999,
                        quantity: 1,
                        unitPrice: 0,
                        objectClass: '22-10-00-00',
                        isShippingCost: false,
                        isChemcial: false,
                        requestId: model.get('generalInfo').get('requestId')
                    });

                    //set the credit amount
                    var cAmount = data.unitPrice;
                    if (cAmount > 0) cAmount = -cAmount;
                    newRecord.set('itemId', data.itemId);
                    newRecord.set('unitPrice', cAmount);
                    //BANK-515
                    newRecord.set('projTask', data.projTask);

                    if (0 !== newRecord.get('itemId')) {
                        method = 'PUT';
                        url = url + '/' + newRecord.data.itemId;
                    }
                    //console.log ('url = ' + url);
                    //console.log ('newRecord.data = ' + JSON. stringify(newRecord.data));

                    Ext.Ajax.request({
                        url: url,
                        method: method,
                        jsonData: Ext.encode(newRecord.data),
                        scope: this,
                        success: function (response) {
                            store.reload();
                            list.setSelection(null);
                            cwindow.hide();
                            me.fireViewEvent('showbbar');
                        },
                        failure: function (response) {
                            store.reload();
                            list.setSelection(null);
                            cwindow.hide();
                            me.fireViewEvent('showbbar');
                        }
                    });
                },
                scope: this
            }
        });

        this.view.add(cwindow);

        var scwindow = Ext.create('widget.shippingcostwindow', {
            reference: 'shippingcostwindow'
        });
        //set event listeners
        scwindow.on({
            cancelSC: {
                fn: function (data) {
                    scwindow.hide();
                    me.fireViewEvent('showbbar');
                },
                scope: this
            }
        });

        scwindow.on({
            saveSC: {
                fn: function (data) {
                    var me = this,
                        //model = this.getViewModel(),
                        url = bcp.config.Runtime.getServerBaseUrl() + 'items',
                        method = 'POST',
                        newRecord = null;
                    //create and add default values for the record
                    newRecord = this.createDefaultShippingItem();
                    //set price for shipping
                    newRecord.set('itemId', data.itemId);
                    newRecord.set('unitPrice', data.unitPrice);
                    //BANK-515
                    newRecord.set('projTask', data.projTask);

                    if (0 !== newRecord.get('itemId')) {
                        method = 'PUT';
                        url = url + '/' + newRecord.data.itemId;
                    }

                    Ext.Ajax.request({
                        url: url,
                        method: method,
                        jsonData: Ext.encode(newRecord.data),
                        scope: this,
                        success: function (response) {
                            store.reload();
                            list.setSelection(null);
                            scwindow.hide();
                            me.fireViewEvent('showbbar');
                        },
                        failure: function (response) {
                            store.reload();
                            list.setSelection(null);
                            scwindow.hide();
                            me.fireViewEvent('showbbar');
                        }
                    });
                },
                scope: this
            }
        });

        //add to the parent view
        this.view.add(scwindow);
    },
    createDefaultShippingItem: function () {
        var model = this.getViewModel();
        var rec = Ext.create('model.bcpitem', {
            itemId: 0,
            itemName: 'Shipping & Handling',
            vendorId: 0, //-999, MB-442
            quantity: 1,
            unitPrice: 0,
            objectClass: '22-10-00-00',
            isShippingCost: true,
            isChemcial: false,
            requestId: model.get('generalInfo').get('requestId')
        });
        return rec;
    },
    autoCreateShipping: function (defaultShippingCost) {
        var rec = this.createDefaultShippingItem(),
            store = Ext.getStore('RequestItems');
        rec.set('unitPrice', defaultShippingCost);
        rec.set('itemNotes', 'auto generated division default shipping cost');
        Ext.Ajax.request({
            url: bcp.config.Runtime.getServerBaseUrl() + 'items',
            method: 'POST',
            jsonData: Ext.encode(rec.data),
            scope: this,
            success: function (response) {
                store.reload();
            },
            failure: function (response) {
                Ext.Msg.alert('Error', 'Auto creating shipping item failed.');
            }
        });
    }
});
