/*
 * File: app/view/ItemPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.ItemPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.itempanel',

    requires: [
        'bcp.view.ItemPanelViewModel',
        'bcp.view.ItemPanelViewController',
        'Ext.grid.Panel',
        'Ext.form.field.Display',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.toolbar.Separator',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.feature.Summary',
        'Ext.form.Panel',
        'Ext.Responsive',
        //'Ext.plugin.Responsive',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Hidden',
        'Ext.form.FieldSet'
    ],
    controller: 'itempanel',
    viewModel: {type: 'itempanel'},
    reference: 'itemPanel',
    shrinkWrap: 0,
    layout: 'card',
    collapsed: false,
    iconCls: 'fas fa-cart-plus',
    title: 'Item(s)',

    listeners: {beforeshow: 'onViewBeforeShow', added: 'onViewAdded'},

    initConfig: function (instanceConfig) {
        var me = this,
            config = {
                items: [
                    me.processList({
                        xtype: 'gridpanel',
                        reference: 'list',
                        stateful: true,
                        stateId: 'itemList',
                        store: 'RequestItems',
                        dockedItems: [
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'notepanel',
                                dock: 'top',
                                //collapseDirection: 'top',
                                collapsible: true,
                                reference: 'panelNote',
                                title: 'Note (Click to expand/collapse)',
                                listeners: {
                                    afterrender: function(panel) {
                                        // Add a click listener to the header
                                        panel.header.on('click', function() {
                                            if (panel.collapsed) {
                                                panel.expand(); // Expand the panel if it's collapsed
                                            } else {
                                                panel.collapse(); // Collapse the panel if it's expanded
                                            }
                                        });
                                    }
                                },
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        cls: 'bcp_notice',
                                        dock: 'top',
                                        fieldLabel: '',
                                        labelWidth: 60,
                                        value:
                                            'The Guidance and Policy links are provided to aid users in understanding various aspects of the Government Purchase Card Policies. <b><a href="Javascript: window.open(\'https://portal.cbs.nist.gov/government-purchase-card-policies-gpcp\')">Government Purchase Card (GPC) Basics and GPC Guidance Policy</a></b>' +
                                            '<ul><li>If requesting <b>Prescription Safety glasses (Feds only)</b>, please attach a completed <b>NIST-293S form</b>.</li>' +
                                            '<li>If requesting <b>Business Cards (Feds only)</b>, please attach a completed <b>NIST Business Card Order Form</b>. You can download the form here <b> <a href="Javascript: window.open(\'https://inet.nist.gov/forms/all-forms\')">NIST All Forms</a></b>.</li>' +
                                            '<li>Please make sure the items you are requesting are not in the <b><a href="Javascript: window.open(\'https://portal.cbs.nist.gov/sites/default/files/documents/Acquisition%20Management%20Division%20%28AMD%29/pdf/listing_of_purchase_card_restricted_items.pdf\')";>Bankcard Restricted Items List</a></b></li>' +
                                            '<li>Please make sure approval is received to purchase atypical expenses (unique or unusual, as opposed to an expense that NIST regularly incurs in the Ordinary course of business) prior to purchase. <b><a href="Javascript: window.open(\'https://portal.cbs.nist.gov/instructions-atypical-bankcard-purchase\')";>Instructions for Atypical Bankcard Purchase</a></b></li>' +
                                            '<li>Please read <b><a href="Javascript: window.open(\'https://nistgov.atlassian.net/wiki/spaces/MMLAdminPortal/pages/14516759/Requirements+for+Hazardous+Materials+and+Human+Subjects+Protection\')";>Requirements for Hazard Approval</a></b></li>' +
                                            '<li>See <b><a href="Javascript: window.open(\'https://nistgov.atlassian.net/wiki/spaces/MMLAdminPortal/pages/14517894/Purchase+Card+Checklist\')";>Purchase Card Checklist </a></b></li>' +
                                            '<li>See <b><a href="Javascript: window.open(\'https://portal.cbs.nist.gov/sites/default/files/2025-02/Form_IT%20Compliance%20in%20Acquisition%20Checklist%20v5.0-NIST_0.pdf\')";>IT Purchase Checklist </a></b></li>' +
                                            '<li>See <b><a href="Javascript: window.open(\'https://nistgov.atlassian.net/wiki/pages/viewpageattachments.action?pageId=14517297&preview=%2F14517297%2F14521900%2FSection508GPCChecklist.pdf\')";>508 Checklist</a></b>.  There are also several articles posted by the NIST 508 Coordinator on the NIST website <b><a href="Javascript: window.open(\'https://inet.nist.gov/adlp/508-did-you-know\')";>here</a></b></li>' +
                                            '<li>If requesting energy-consuming products, please conform to Energy Star availability from <b><a href="Javascript: window.open(\'https://www.energystar.gov/\')";>www.energystar.gov</a></b> as reasonably as possible.</li>'+
                                            '</ul>'
                                    },
                                ]
                            },
                            
                            {
                                xtype: 'toolbar',
                                reference: 'itemTbar',
                                dock: 'top',
                                defaultButtonUI: 'default',
                                enableOverflow: true,
                                overflowHandler: 'menu',
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'addItemBtn',
                                        reference: 'itemBtn',
                                        text: 'Add Item',
                                        bind: {disabled: '{isShoppingCart}'},
                                        listeners: {click: 'add'}
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'addShippingBtn',
                                        reference: 'shippingBtn',
                                        text: 'Add Shipping & Handling',
                                        tooltip:
                                            'Add the estimated shipping & handling cost.',
                                        bind: {disabled: '{hasShipping}'},
                                        listeners: {click: 'addShipping'}
                                    },
                                    {xtype: 'label', text: 'OR'},
                                    /*{
                    xtype: "button",
                    reference: "scBtn",
                    text: "Upload a Shopping Cart File",
                    tooltip: "If you have a long list of items and don't want to enter them one by one, you could save them in a file or image and upload it.",
                    bind: {
                      disabled: "{hasItem || isShoppingCart}",
                    },
                    listeners: {
                      click: "uploadCart",
                    },
                  },*/
                                    {xtype: 'tbseparator'},
                                    {
                                        xtype: 'button',
                                        id:'addCreditBtn',
                                        reference: 'creditBtn',
                                        text: 'Add/Edit Credit',
                                        tooltip:
                                            'Add/Edit Credit for this purchase.',
                                        listeners: {click: 'editCredit'}
                                    },
                                    {xtype: 'tbseparator'},
                                    {
                                        xtype: 'button',
                                        id: 'editItemBtn',
                                        reference: 'editBtn',
                                        text: 'Edit',
                                        bind: {
                                            disabled:
                                                '{!list.selection || iRecord.vendorId == -9999}',
                                            hidden: '{iRecord.shoppingCartFileId!==0}'
                                        },
                                        listeners: {click: 'edit'}
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'updateItemStatusBtn',
                                        reference: 'updtItemStatusBtn',
                                        text: 'Update Item Statuses',
                                        /*bind: {
                                            hidden: '{!isPurchase}'
                                        },*/
                                        listeners: {click: 'updateStatuses'}
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'partialDeliveryBtn',
                                        reference: 'partialDeliveryBtn',
                                        text: 'Partial Delivery',
                                        bind: {
                                            disabled: '{!list.selection}',
                                            hidden: '{!isPurchase}'
                                        },
                                        listeners: {click: 'onPartialDelivery'}
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'btnRequestReapproval',
                                        reference: 'btnRequestReapproval',
                                        text: 'Request Re-Approval',
                                        tooltip:
                                            'route the request back to the Bankcard Approving Official for Re-Approval because the actual cost exceeds the approved amount',
                                        bind: {hidden: '{!isPurchase}'},
                                        listeners: {
                                            click: 'onRequestReapproval'
                                        }
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'delItemBtn',
                                        reference: 'delBtn',
                                        text: 'Remove',
                                        bind: {
                                            //disabled: '{!list.selection || iRecord.vendorId == -9999}'
                                            disabled: '{!list.selection}'
                                        },
                                        listeners: {click: 'remove'}
                                    }
                                ]
                            }
                        ],
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                hidden: true,
                                dataIndex: 'itemId',
                                text: 'Item Id'
                            },
                            {
                                xtype: 'gridcolumn',
                                hidden: true,
                                dataIndex: 'requestId',
                                text: 'Request Id'
                            },
                            {
                                xtype: 'gridcolumn',
                                hidden: true,
                                dataIndex: 'vendorId',
                                text: 'Vendor Id'
                            },
                            {
                                xtype: 'gridcolumn',
                                minWidth: 200,
                                cellWrap: true,
                                dataIndex: 'itemName',
                                text: 'Item Name'
                            },
                            {
                                xtype: 'gridcolumn',
                                hidden: true,
                                cellWrap: true,
                                dataIndex: 'description',
                                text: 'Description'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 140,
                                cellWrap: true,
                                dataIndex: 'catalogNumber',
                                text: 'Catalog Number'
                            },
                            {
                                xtype: 'gridcolumn',
                                hidden: true,
                                cellWrap: true,
                                dataIndex: 'purpose',
                                text: 'Purpose'
                            },
                            {
                                xtype: 'gridcolumn',
                                /*renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    return bcp.util.CommonUtil.moneyRenderer(
                                        value
                                    );
                                },*/
                                minWidth: 80,
                                width: 100,
                                align: 'end',
                                dataIndex: 'unitPrice',
                                text: 'Unit Price'
                            },
                            {
                                xtype: 'numbercolumn',
                                minWidth: 80,
                                width: 60,
                                align: 'center',
                                dataIndex: 'quantity',
                                text: 'Quantity',
                                format: '00'
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    return bcp.util.CommonUtil.moneyRenderer(
                                        value
                                    );
                                },
                                summaryRenderer: function (
                                    val,
                                    params,
                                    data,
                                    metaData
                                ) {
                                    return (
                                        'Estimated Total: ' +
                                        bcp.util.CommonUtil.moneyRenderer(val)
                                    );
                                },
                                summaryType: 'sum',
                                minWidth: 200,
                                align: 'end',
                                dataIndex: 'amount',
                                exportSummaryRenderer: true,
                                text: 'Amount'
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    //console.log ('actualPrice = ' + record.get('vendorId'));
                                    if (
                                        !this.lookupViewModel().get(
                                            'isPurchase'
                                        ) ||
                                        record.get('vendorId') == '-9999'
                                    ) {
                                        return bcp.util.CommonUtil.moneyRenderer(
                                            value
                                        );
                                    } else {
                                        if (value === null || value === 0) {
                                            return (
                                                'Add ' +
                                                '<i class="fas fa-plus" aria-hidden="true"></i>'
                                            );
                                        } else {
                                            return (
                                                bcp.util.CommonUtil.moneyRenderer(
                                                    value
                                                ) +
                                                ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>'
                                            );
                                        }
                                    }
                                },
                                reference: 'aPriceCol',
                                hidden: true,
                                minWidth: 120,
                                align: 'end',
                                dataIndex: 'actualPrice',
                                text: '<b>Actual Price</b>',
                                editor: {
                                    xtype: 'numberfield',
                                    reference: 'aPriceEditor',
                                    allowExponential: false,
                                    minValue: 0,
                                    bind: {
                                        readOnly:
                                            '{!isPurchase || iRecord.vendorId == -9999}'
                                    },
                                    listeners: {blur: 'onPriceEditorBlur'}
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    if (
                                        !this.lookupViewModel().get(
                                            'isPurchase'
                                        ) ||
                                        record.get('vendorId') == '-9999'
                                    ) {
                                        return value;
                                    } else {
                                        if (value === null || value === 0) {
                                            return (
                                                'Add ' +
                                                '<i class="fas fa-plus" aria-hidden="true"></i>'
                                            );
                                        } else {
                                            return (
                                                value +
                                                ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>'
                                            );
                                        }
                                    }
                                },
                                reference: 'aQtCol',
                                hidden: true,
                                minWidth: 140,
                                align: 'center',
                                dataIndex: 'actualQuantity',
                                text: '<b>Actual Quantity</b>',
                                editor: {
                                    xtype: 'numberfield',
                                    reference: 'aQtEditor',
                                    allowDecimals: false,
                                    allowExponential: false,
                                    minValue: 1,
                                    bind: {
                                        readOnly:
                                            '{!isPurchase || iRecord.vendorId == -9999}'
                                    },
                                    listeners: {blur: 'onQtEditorBlur'}
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    return bcp.util.CommonUtil.moneyRenderer(
                                        record.get('actualPrice') *
                                            record.get('actualQuantity')
                                    );
                                },
                                summaryRenderer: function (
                                    val,
                                    params,
                                    data,
                                    metaData
                                ) {
                                    return (
                                        'Actual Total: ' +
                                        bcp.util.CommonUtil.moneyRenderer(val)
                                    );
                                },
                                summaryType: 'sum',
                                reference: 'aAmtCol',
                                hidden: true,
                                minWidth: 200,
                                align: 'end',
                                dataIndex: 'actualAmount',
                                text: '<b>Actual Amount</b>'
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    if (
                                        this.lookupViewModel().get('isPurchase')
                                    ) {
                                        return (
                                            record.get('itemStatus') +
                                            ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>'
                                        );
                                    } else {
                                        return record.get('itemStatus');
                                    }
                                },
                                reference: 'statusCol',
                                minWidth: 120,
                                dataIndex: 'itemStatusId',
                                text: 'Status',
                                editor: {
                                    xtype: 'combobox',
                                    reference: 'itemStatusCombo',
                                    displayField: 'name',
                                    store: 'LkItemStatus',
                                    valueField: 'id',
                                    bind: {readOnly: '{!isPurchase}'},
                                    listeners: {change: 'onItemStatusChange'}
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    if (
                                        this.lookupViewModel().get('isPurchase')
                                    ) {
                                        if (value) {
                                            return (
                                                value +
                                                ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>'
                                            );
                                        } else {
                                            return ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>';
                                        }
                                    } else {
                                        if (value) {
                                            return value;
                                        } else {
                                            return '';
                                        }
                                    }
                                },
                                reference: 'itemNoteCol',
                                width: 250,
                                cellWrap: true,
                                dataIndex: 'itemNotes',
                                text: 'Note',
                                editor: {
                                    xtype: 'textareafield',
                                    maxLength: 1000,
                                    reference: 'itemNoteTa',
                                    bind: {readOnly: '{!isPurchase}'},
                                    listeners: {blur: 'onItemNoteChange'}
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    if (
                                        this.lookupViewModel().get('isPurchase')
                                    ) {
                                        return (
                                            Ext.util.Format.date(
                                                value,
                                                'm/d/Y'
                                            ) +
                                            ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>'
                                        );
                                    } else {
                                        if (value) {
                                            return Ext.util.Format.date(
                                                value,
                                                'm/d/Y'
                                            );
                                        } else {
                                            return '';
                                        }
                                    }
                                },
                                reference: 'receivedDateCol',
                                width: 140,
                                cellWrap: true,
                                dataIndex: 'receivedDate',
                                text: 'Received Date',
                                editor: {
                                    xtype: 'datefield',
                                    reference: 'receivedDateDf',
                                    bind: {readOnly: '{!isPurchase}'},
                                    listeners: {change: 'onReceivedDateChange'}
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    if (
                                        this.lookupViewModel().get('isPurchase')
                                    ) {
                                        return (
                                            Ext.util.Format.date(
                                                value,
                                                'm/d/Y'
                                            ) +
                                            ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>'
                                        );
                                    } else {
                                        if (value) {
                                            return Ext.util.Format.date(
                                                value,
                                                'm/d/Y'
                                            );
                                        } else {
                                            return '';
                                        }
                                    }
                                },
                                reference: 'statementDateCol',
                                width: 140,
                                cellWrap: true,
                                dataIndex: 'statementDate',
                                text: 'Statement Date',
                                editor: {
                                    xtype: 'datefield',
                                    reference: 'statementDateDf',
                                    bind: {readOnly: '{!isPurchase}'},
                                    listeners: {change: 'onStatementDateChange'}
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function (
                                    value,
                                    metaData,
                                    record,
                                    rowIndex,
                                    colIndex,
                                    store,
                                    view
                                ) {
                                    if (
                                        this.lookupViewModel().get('isPurchase')
                                    ) {
                                        if (value) {
                                            return (
                                                value +
                                                ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>'
                                            );
                                        } else {
                                            return ' <i class="fas fa-pencil-alt fa-fw" aria-hidden="true"></i>';
                                        }
                                    } else {
                                        if (value) {
                                            return value;
                                        } else {
                                            return '';
                                        }
                                    }
                                },
                                reference: 'transactionNumberCol',
                                width: 250,
                                cellWrap: true,
                                dataIndex: 'transactionNumber',
                                text: 'Transaction Number',
                                editor: {
                                    xtype: 'textfield',
                                    reference: 'transactionNumberTf',
                                    maxLength: 150,
                                    bind: {readOnly: '{!isPurchase}'},
                                    listeners: {
                                        blur: 'onTransactionNumberChange'
                                    }
                                }
                            },
                            {
                                xtype: 'gridcolumn',
                                hidden: true,
                                cellWrap: true,
                                dataIndex: 'unitIssue',
                                text: 'Unit Issue'
                            },
                            {
                                xtype: 'booleancolumn',
                                minWidth: 100,
                                width: 120,
                                dataIndex: 'isChemical',
                                text: 'Is a Chemical',
                                falseText: 'No',
                                trueText: 'Yes'
                            }
                            /*{
                xtype: "gridcolumn",
                renderer: function (value,metaData,record,rowIndex,colIndex,store,view) {
                  if (value !== 0) {
                    return "Yes";
                  } else {
                    return "No";
                  }
                },
                maxWidth: 160,
                minWidth: 130,
                cellWrap: true,
                dataIndex: "shoppingCartFileId",
                text: "Is Shopping Cart",
              },*/
                        ],
                        listeners: {select: 'select'},
                        plugins: [{ptype: 'cellediting', clicksToEdit: 1}],
                        features: [{ftype: 'summary'}]
                    }),
                    {
                        xtype: 'form',
                        reference: 'form',
                        padding: 0,
                        scrollable: true,
                        responsiveConfig: {
                            'width >= 850': {
                                layout: {type: 'table', columns: 2}
                            },
                            'width < 850': {layout: {type: 'table', columns: 1}}
                        },
                        defaults: {
                            labelSeparator: '',
                            labelAlign: 'top',
                            padding: '0 0 0 10'
                        },
                        bodyPadding: 5,
                        title: 'Edit Item',
                        layout: {type: 'table', columns: 2},
                        dockedItems: [
                            {
                                xtype: 'toolbar',
                                reference: 'itemFormTbar',
                                dock: 'top',
                                defaultButtonUI: 'default',
                                enableOverflow: true,
                                overflowHandler: 'menu',
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'saveItemBtn',
                                        formBind: true,
                                        itemId: 'saveButton',
                                        margin: 5,
                                        minWidth: 100,
                                        text: 'Save',
                                        listeners: {click: 'save'}
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'saveAndAddItemBtn',
                                        reference: 'saveAndAddBtn',
                                        formBind: true,
                                        itemId: 'saveAndAdd',
                                        margin: 5,
                                        minWidth: 100,
                                        text: 'Save & Add Another',
                                        bind: {
                                            disabled: '{iRecord.itemId!==0}'
                                        },
                                        listeners: {click: 'saveAndAdd'}
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'cancelItemEditBtn',
                                        reference: 'cancelBtn',
                                        itemId: 'cancelButton',
                                        margin: 5,
                                        minWidth: 100,
                                        text: 'Cancel',
                                        listeners: {click: 'cancelEdit'}
                                    }
                                ]
                            }
                        ],
                        items: [
                            {
                                xtype: 'combobox',
                                colspan: 2,
                                reference: 'vendorCombo',
                                anchor: '100%',
                                disabled: true,
                                hidden: true,
                                minWidth: 380,
                                fieldLabel:
                                    'Vendor Name (no longer needed because only 1 vendor per request now)',
                                name: 'vendorId',
                                submitValue: false,
                                anyMatch: true,
                                displayField: 'vendorName',
                                forceSelection: true,
                                minChars: 2,
                                queryMode: 'local',
                                store: 'RequestVendors',
                                valueField: 'vendorName'
                            },
                            {
                                xtype: 'container',
                                colspan: 2,
                                layout: {type: 'hbox', align: 'stretch'},
                                items: [
                                    {
                                        xtype: 'textfield',
                                        flex: 1,
                                        id: 'itemNameTf',
                                        reference: 'itemNameTf',
                                        minWidth: 380,
                                        maxLength: 200,
                                        padding: '0 20 0 0',
                                        fieldLabel: 'Item Name',
                                        labelAlign: 'top',
                                        name: 'itemName',
                                        allowBlank: false,
                                        allowOnlyWhitespace: false
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        id:  'isTaggableEquipmentCf',
                                        flex: 1,
                                        fieldLabel: 'Is a Taggable Equipment',
                                        labelAlign: 'top',
                                        name: 'isTaggableEquipment',
                                        afterLabelTextTpl:
                                            '<i class="fa fa-info-circle fa-lg" aria-hidden="true" data-qtip="Taggable equipment refers to items that involve tracking the user\'s responsibility to maintain their good condition. The equipment is likely reusable, transferable and/or has a considerable cost. This would include items like computers, printers, firearms, or anything that is not permanently attached to a building and/or costs greater than or equal to $5,000 dollars."></i>'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        id:  'isChemicalCf',
                                        flex: 1,
                                        fieldLabel: 'Is a <br>Chemical',
                                        labelAlign: 'top',
                                        name: 'isChemical',
                                        listeners: {
                                            change: 'onIsChemicalChange'
                                        }
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                colspan: 2,
                                width: 500,
                                layout: {type: 'hbox', align: 'stretch'},
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id:  'unitIssueTf',
                                        padding: '0 20 0 0',
                                        fieldLabel: 'Unit',
                                        maxLength: 100,
                                        labelAlign: 'top',
                                        name: 'unitIssue'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        id:  'unitPriceNf',
                                        flex: 1,
                                        maxWidth: 140,
                                        padding: '0 20 0 0',
                                        width: '',
                                        fieldLabel: 'Unit Price',
                                        labelAlign: 'top',
                                        name: 'unitPrice',
                                        allowBlank: false,
                                        allowOnlyWhitespace: false,
                                        allowExponential: false,
                                        decimalPrecision: 3,
                                        minValue: 0,
                                        bind: {
                                            value: '{iRecord.unitPrice}',
                                            maxValue: '{purchaseLimit}'
                                        }
                                    },
                                    {
                                        xtype: 'numberfield',
                                        id:  'quantityNf',
                                        maxWidth: 140,
                                        padding: '0 20 0 0',
                                        fieldLabel: 'Quantity',
                                        labelAlign: 'top',
                                        name: 'quantity',
                                        allowBlank: false,
                                        allowOnlyWhitespace: false,
                                        allowDecimals: false,
                                        allowExponential: false,
                                        decimalPrecision: 0,
                                        maxValue: 10000,
                                        minValue: 1,
                                        bind: {value: '{iRecord.quantity}'}
                                    }
                                ]
                            },
                            {
                                xtype: 'displayfield',
                                renderer: function (value, displayField) {
                                    return Ext.util.Format.usMoney(value);
                                },
                                colspan: 2,
                                minWidth: 150,
                                fieldLabel: 'Amount',
                                labelAlign: 'top',
                                name: 'amount',
                                bind: {
                                    value: '{iRecord.unitPrice*iRecord.quantity}'
                                }
                            },
                            {
                                xtype: 'textareafield',
                                id:  'descriptionItemTa',
                                colspan: 2,
                                maxWidth: 670,
                                minWidth: 440,
                                maxLength: 1000,
                                width: 670,
                                fieldLabel: 'Purpose/Description',
                                name: 'description'
                            },
                            {
                                xtype: 'container',
                                colspan: 2,
                                width: 450,
                                layout: {type: 'hbox', align: 'stretch'},
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id:  'catalogNumberItemTf',
                                        padding: '0 20 0 0',
                                        width: 200,
                                        maxLength: 200,
                                        fieldLabel: 'Catalog/Item Number',
                                        labelAlign: 'top',
                                        name: 'catalogNumber',
                                        reference: 'tfCatalog'
                                    }
                                ]
                            },
                            {
                                xtype: 'form',
                                colspan: 2,
                                reference: 'chemicalform',
                                margin: '10 0 0 10',
                                padding: 0,
                                responsiveConfig: {
                                    'width >= 850': {
                                        layout: {type: 'table', columns: 2}
                                    },
                                    'width < 850': {
                                        layout: {type: 'table', columns: 1}
                                    }
                                },
                                defaults: {
                                    labelSeparator: '',
                                    labelAlign: 'top',
                                    padding: '0 0 0 10'
                                },
                                title: 'Chemical Information',
                                layout: {type: 'table', columns: 2},
                                bind: {
                                    disabled:
                                        '{!iRecord.isChemical || iRecord.shoppingCartFileId >0}',
                                    hidden: {
                                        bindTo: '{!iRecord.isChemical || iRecord.shoppingCartFileId >0}',
                                        deep: true
                                    }
                                },
                                items: [
                                    {
                                        xtype: 'combobox',
                                        colspan: 2,
                                        reference: 'chemicalOwnerCombo',
                                        width: 260,
                                        fieldLabel: 'Chemical Owner',
                                        name: 'chemicalOwnerId',
                                        allowBlank: false,
                                        allowOnlyWhitespace: false,
                                        emptyText: 'type staff name here',
                                        anyMatch: true,
                                        displayField: 'displayName',
                                        forceSelection: true,
                                        minChars: 2,
                                        queryMode: 'local',
                                        queryParam: 'filter',
                                        //typeAhead: true,
                                        valueField: 'peopleId',
                                        bind: {
                                            value: '{chemrecord.chemicalOwnerId}',
                                            store: '{bcUsers}'
                                        }
                                    },
                                    {
                                        xtype: 'combobox',
                                        colspan: 2,
                                        reference: 'primaryUserCombo',
                                        width: 260,
                                        fieldLabel: 'Primary User',
                                        name: 'primaryUserId',
                                        emptyText: 'type staff name here',
                                        anyMatch: true,
                                        displayField: 'displayName',
                                        forceSelection: true,
                                        minChars: 2,
                                        queryMode: 'local',
                                        queryParam: 'filter',
                                        //typeAhead: true,
                                        valueField: 'peopleId',
                                        bind: {
                                            value: '{chemrecord.primaryUserId}',
                                            store: '{bcUsers2}'
                                        }
                                    },
                                    {
                                        xtype: 'textfield',
                                        width: 260,
                                        fieldLabel:
                                            'Location Of Chemical (building/room)',
                                        name: 'locationOfChemical',
                                        allowBlank: false,
                                        allowOnlyWhitespace: false
                                    },
                                    {
                                        xtype: 'textfield',
                                        fieldLabel:
                                            ' Numbered location within room, if applicable',
                                        name: 'subLocation'
                                    },
                                    {
                                        xtype: 'textfield',
                                        width: 260,
                                        fieldLabel: 'IBBR Room',
                                        name: 'ibbrRoomName',
                                        readOnly: true,
                                        bind: {
                                            value: '{chemrecord.ibbrRoomName}'
                                        }
                                    },
                                    {
                                        xtype: 'container',
                                        //rowspan: 2,
                                        //width: 700,
                                        layout: {
                                            type: 'vbox'
                                            //align: 'bottom'
                                        },
                                        items: [
                                            {
                                                xtype: 'title',
                                                height: 18,
                                                text: ''
                                            },
                                            {
                                                xtype: 'container',
                                                colspan: 2,
                                                width: 700,
                                                layout: {
                                                    type: 'hbox',
                                                    align: 'bottom'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        margin: 10,
                                                        height: 28,
                                                        //padding: '70 0 0 0',
                                                        text: 'Select a IBBR Room',
                                                        listeners: {
                                                            click: 'onIbbrRoomClick'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        margin: 10,
                                                        height: 28,
                                                        //padding: '40 0 0 0',
                                                        text: 'Clear the IBBR Room',
                                                        listeners: {
                                                            click: 'onResetIbbrRoomClick'
                                                        }
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        name: 'ibbrRoomId',
                                        colspan: 2
                                    },

                                    {
                                        xtype: 'textfield',
                                        fieldLabel: 'CAS#',
                                        name: 'casNumber',
                                        allowBlank: false,
                                        allowOnlyWhitespace: false
                                    },
                                    {
                                        xtype: 'textfield',
                                        disabled: true,
                                        hidden: true,
                                        fieldLabel: 'Chemical Name',
                                        name: 'chemicalName',
                                        submitValue: false,
                                        allowBlank: false,
                                        allowOnlyWhitespace: false
                                    },
                                    {
                                        xtype: 'textfield',
                                        width: 380,
                                        fieldLabel: 'Manufacturer Name',
                                        name: 'manufacturerName'
                                    },
                                    {
                                        xtype: 'textfield',
                                        disabled: true,
                                        hidden: true,
                                        fieldLabel: 'Vendor Name',
                                        name: 'vendorName',
                                        submitValue: false
                                    },
                                    {
                                        xtype: 'combobox',
                                        colspan: 2,
                                        fieldLabel: 'Container Type',
                                        name: 'containerType',
                                        grow: true,
                                        displayField: 'name',
                                        forceSelection: true,
                                        minChars: 1,
                                        queryMode: 'local',
                                        //typeAhead: true,
                                        valueField: 'name',
                                        bind: {
                                            store: '{chemicalContainerTypes}'
                                        },
                                        allowBlank: false,
                                        allowOnlyWhitespace: false
                                    },
                                    {
                                        xtype: 'fieldset',
                                        colspan: 2,
                                        padding: 0,
                                        responsiveConfig: {
                                            'width >= 750': {
                                                layout: {
                                                    type: 'table',
                                                    columns: 2
                                                }
                                            },
                                            'width < 750': {
                                                layout: {
                                                    type: 'table',
                                                    columns: 1
                                                }
                                            }
                                        },
                                        defaults: {
                                            labelWidth: 110,
                                            labelAlign: 'top',
                                            labelSeparator: '',
                                            padding: '0 0 0 10'
                                        },
                                        layout: {type: 'table', columns: 2},
                                        items: [
                                            {
                                                xtype: 'hiddenfield',
                                                width: 270,
                                                fieldLabel: 'Catalog Number',
                                                name: 'chemicalCatalogNumber'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                fieldLabel:
                                                    'Quantity Of Catalog# (e.g. 3 of S7653-25G)',
                                                name: 'quantityOfCatalogNumber'
                                            },
                                            {
                                                xtype: 'textfield',
                                                width: 290,
                                                fieldLabel:
                                                    'Containers Per Package  (e.g., 12 per case)',
                                                name: 'containersPerPackage',
                                                maxLength:50,
                                                allowBlank: false,
                                                allowOnlyWhitespace: false
                                            },
                                            {
                                                xtype: 'textfield',
                                                fieldLabel:
                                                    'Amount and Unit Per Container (e.g., 5 mL)',
                                                name: 'amountAndUnitPerContainer',
                                                allowBlank: false,
                                                allowOnlyWhitespace: false
                                            },
                                            {
                                                xtype: 'numberfield',
                                                colspan: 2,
                                                width: 530,
                                                fieldLabel:
                                                    'Total Number of Containers (i.e., Quantity multiplied by Containers Per Package)',
                                                name: 'containerTotal'
                                            }
                                        ],
                                        plugins: [{ptype: 'responsive'}]
                                    },
                                    {
                                        xtype: 'numberfield',
                                        colspan: 2,
                                        width: 260,
                                        fieldLabel:
                                            'Number Of Barcode Labels Needed',
                                        labelAlign: 'top',
                                        name: 'numOfLabelsOrBarcodesNeeded'
                                    },
                                    {
                                        xtype: 'datefield',
                                        colspan: 2,
                                        hidden: true,
                                        minWidth: 220,
                                        fieldLabel:
                                            'Expiration Date  (if applicable) ',
                                        labelAlign: 'top',
                                        name: 'expirationDate',
                                        submitValue: false
                                    },
                                    {
                                        xtype: 'textareafield',
                                        colspan: 2,
                                        anchor: '',
                                        maxWidth: 670,
                                        minWidth: 440,
                                        width: 670,
                                        fieldLabel:
                                            'Remarks for CIMS Power User',
                                        name: 'cisproRemarks',
                                        maxLength: 500,
                                        submitValue: false
                                    },
                                    {
                                        xtype: 'textareafield',
                                        colspan: 2,
                                        anchor: '',
                                        maxWidth: 670,
                                        minWidth: 440,
                                        width: 670,
                                        fieldLabel: 'Special Instructions',
                                        maxLength: 500,
                                        name: 'specialInstructions'
                                    },
                                    {
                                        xtype: 'textareafield',
                                        colspan: 2,
                                        anchor: '',
                                        maxWidth: 670,
                                        minWidth: 440,
                                        width: 670,
                                        maxLength: 500,
                                        fieldLabel:
                                            'Web URL for Vendor Product Page (so CIMS Power User can obtain SDS)',
                                        name: 'productUrl'
                                    }
                                ],
                                plugins: [{ptype: 'responsive'}]
                            }
                        ],
                        plugins: [{ptype: 'responsive'}]
                    }
                ]
            };
        if (instanceConfig) {
            me.self.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processList: function (config) {
        config.viewConfig = {enableTextSelection: true};
        //since itempanel is included in many containers(new request, purchase...), to
        //save the state for each would requrire a different state id.
        config.stateId = 'itemlist' + window.location.hash;
        return config;
    }
});
