/*
 * File: app/view/JustificationPanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define("bcp.view.JustificationPanelViewController", {
    extend: "Ext.app.ViewController",
    alias: "controller.justificationpanel",

    updateView: function (hasJustification) {
        var model = this.getViewModel(),
            store = Ext.getStore("RequestJustifications"),
            refs = this.getReferences(),
            view = this.view,
            layout = view.getLayout(),
            formPanel = refs.form,
            form = formPanel.getForm(),
            rec = null;

        //if Justification data exists
        if (hasJustification) {
            rec = store.first();
            model.set("jrecord", rec);
            var vid = rec.get("builtInVendor");

            //for built in vendors
            if (vid && vid < 0) {
                if (vid == -99) {
                    refs.cardBuiltInVendor.setFieldLabel("IT Buying Service");
                } else if (vid == -100) {
                    refs.cardBuiltInVendor.setFieldLabel("UNICOR");
                }
                layout.setActiveItem(refs.cardBuiltInVendor);
                refs.tb.hide();
            } else {
                /*else if(rec.get('convenienceCheck')){
                //for convenience Check
                refs.formCvChk.loadRecord(rec);
                refs.taConvenienceCheck.setValue(rec.get('convenienceCheckJust'));
                layout.setActiveItem(refs.formCvChk);
                if(view.readOnly){
                    refs.tb.hide();
                }else{
                    refs.tb.show();
                }
            }*/
                //for regular justification or convenience Check
                if (view.readOnly) {
                    refs.tb.hide();
                    bcp.util.CommonUtil.makeFormReadOnly(form, true);
                } else {
                    refs.tb.show();
                    bcp.util.CommonUtil.makeFormReadOnly(form, false);
                }

                //if convenience Check, show convenience Check justification field
                if (rec.get("convenienceCheck")) {
                    refs.taConvenienceCheck.show();
                    refs.taConvenienceCheck.enable();
                } else {
                    //hide and disable it
                    refs.taConvenienceCheck.hide();
                    refs.taConvenienceCheck.disable();
                }

                // Load record model into form
                form.loadRecord(rec);
                if (rec.data.professionalOrg) {
                    refs.poRg.setValue("1");
                } else {
                    refs.poRg.setValue("0");
                }

                if (rec.data.gsaSchedule) {
                    refs.gsaRg.setValue("1");
                } else {
                    refs.gsaRg.setValue("0");
                }

                /*if (rec.data.commercialVendor) {
                    refs.cvRg.setValue("1");
                } else {
                    refs.cvRg.setValue("0");
                }*/

                if (rec.data.thirdPartyVendor) {
                    refs.tpRg.setValue("1");
                } else {
                    refs.tpRg.setValue("0");
                }
                /*
                if (rec.data.smallBusiness) {
                    refs.sbRg.setValue("1");
                } else {
                    refs.sbRg.setValue("0");
                }
                */

                // Show form
                layout.setActiveItem(refs.form);
            }
        } else {
            model.set("jrecord", null);

            //if no record yet, hide ck just field
            refs.taConvenienceCheck.hide();
            refs.taConvenienceCheck.disable();

            // Load record model into form
            form.reset();
            rec = Ext.create("bcp.model.RequestJustification", {requestId: 0});
            form.loadRecord(rec);
            //no Justification yet
            layout.setActiveItem(refs.form);

            if (view.readOnly) {
                refs.tb.hide();
                bcp.util.CommonUtil.makeFormReadOnly(form, true);
            } else {
                refs.tb.show();
                bcp.util.CommonUtil.makeFormReadOnly(form, false);
            }
        }
    },

    save: function (button, e, eOpts) {
        var model = this.getViewModel(),
            reqId = model.get("generalInfo").get("requestId"),
            refs = this.getReferences(),
            view = this.view,
            layout = view.getLayout(),
            formPanel = refs.form,
            form = formPanel.getForm(),
            formData = form.getValues(),
            record = form.getRecord(),
            store = Ext.getStore("RequestJustifications"),
            method = "POST",
            url = "";

        var currentCard = layout.getActiveItem();

        if (currentCard.reference == "cardBuiltInVendor") {
            //since save button should be hidden, it should not come here
            return;
        } else {
            /*else if(currentCard.reference=='formCvChk'){
            //convenience check justification
            form=currentCard.getForm();
            record= form.getRecord();
            form.updateRecord();
        }*/
            //normal justification
            // Valid
            if (form.isValid()) {
                // Update associated record with values
                form.updateRecord();

                if (formData.isPo === "1") {
                    record.set("professionalOrg", true);
                    record.set("gsaSchedule", false);
                    record.set("smallBusiness", false);
                } else {
                    record.set("professionalOrg", false);
                    //set justification flag values
                    record.set("gsaSchedule", formData.isGsa == "1");
                    record.set("smallBusiness", formData.isSb == "1");

                    //set justification values
                    //if is GSA, set these two justs to empty string
                    if (formData.isGsa === "1") {
                        record.set("gsaScheduleJust", "");
                        record.set("priceIsReasonableJust", "");
                        record.set("thirdPartyVendor", false);
                        record.set("thirdPartyVendorJust", "");
                    } else {
                        //if not third party
                        if (formData.isTp !== "1") {
                            record.set("thirdPartyVendor", false);
                            record.set("thirdPartyVendorJust", "");
                        } else {
                            record.set("thirdPartyVendor", true);
                        }

                        //BANK-544
                        //if not Commercial Vendor
                        /*if (formData.isCv !== "1") {
                            record.set('commercialVendor', false);
                            record.set('commercialVendorJust', "");
                        } else {
                            record.set('commercialVendor', true);
                        }*/
                    }

                    //if is small business
                    if (formData.isSb === "1") {
                        record.set("smallBusinessJust", "");
                    }
                }
            } else {
                bcp.util.CommonUtil.showValidationError("Please fix the invalid data in the Justification Form.");
                return;
            }
        }

        url = bcp.config.Runtime.getServerBaseUrl() + "vendors/justification/" + reqId;

        //request id in the form decide whether this is a insert or update operation
        if (record.data.requestId != 0) {
            method = "PUT";
        } else {
            method = "POST";
            record.data.requestId = reqId;
        }

        Ext.Ajax.request({
            url: url,
            method: method,
            jsonData: Ext.encode(record.data),
            scope: this,
            success: function (response) {
                bcp.util.CommonUtil.ajaxSuccessHandler(response, function (result) {
                    store.reload();
                });
            }
        });
    },

    //BANK-519
    remove: function (button, e, eOpts) {
        var model = this.getViewModel(),
            reqId = model.get("generalInfo").get("requestId"),
            store = Ext.getStore("RequestJustifications"),
            url = "",
            me = this;

        // Ask user to confirm this action
        Ext.Msg.confirm(
            "Confirm Remove",
            "Are you sure you want to remove, which deletes all previously saved justification inputs for the request?",
            function (result) {
                // User confirmed yes
                if (result == "yes") {
                    url = bcp.config.Runtime.getServerBaseUrl() + "vendors/justification/" + reqId;
                    var method = "DELETE";
                    Ext.Ajax.request({
                        url: url,
                        method: method,
                        scope: this,
                        success: function (response) {
                            // reload store
                            store.reload();
                            //refresh view
                            me.updateView();
                        }
                    });
                }
            }
        );
    },

    onIsPoChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences();
        if (newValue === undefined || newValue === "1") {
            refs.ctnJust.hide();
            refs.ctnJust.disable();
        } else {
            refs.ctnJust.show();
            refs.ctnJust.enable();
            refs.gsaRg.reset();
            //refs.sbRg.reset();
        }

        if (newValue === "1") {
            refs.poVendorNote.show();
        } else {
            refs.poVendorNote.hide();
        }
    },

    onIsGsaChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences(),
            model = this.getViewModel(),
            req = model.get("generalInfo"),
            isItPurchase = req.get("purchaseTypeId") == 2;

        if (newValue === undefined || newValue === "1") {
            refs.nonGsaJustTa.hide();
            refs.nonGsaJustCtn.hide();
            refs.cvJustCtn.hide();
            refs.tpRg.reset();
            refs.tpRg.hide();
            refs.tpTa.hide();
            refs.tpJustCtn.hide();
            //refs.cvRg.reset();
            //refs.cvRg.hide();
            //refs.cvTa.hide();
            //refs.cvJustCtn.hide();
            refs.priceTa.hide();
            refs.priceJustCtn.hide();
            //issue 684
            if (newValue === "1") {
                refs.gsaNote.show();
            } else {
                refs.gsaNote.hide();
            }
        } else {
            refs.gsaNote.hide();
            //BANK-544
            //if no, show this note
            if (isItPurchase) {
                refs.cvJustCtn.show();
            } else {
                refs.cvJustCtn.hide();
            }
            refs.nonGsaJustCtn.show();
            refs.nonGsaJustTa.show();

            refs.tpRg.show();
            if (refs.tpRg.value === "1") {
                refs.tpJustCtn.show();
                refs.tpTa.show();
            } else {
                refs.tpJustCtn.hide();
                refs.tpTa.hide();
            }

            //refs.cvRg.show();
            /*
            if (refs.cvRg.value === "1") {
                refs.cvJustCtn.show();
                refs.cvTa.show();
            } else {
                refs.cvJustCtn.hide();
                refs.cvTa.hide();
            }
            */
            refs.priceJustCtn.show();
            refs.priceTa.show();
        }
    },

    onComboGSAJustChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences();
        refs.nonGsaJustTa.setValue(newValue);
    },

    onComboPriceJustChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences();
        refs.priceTa.setValue(newValue);
        bcp.util.CommonUtil.showAlert(
            "Info",
            "For proof of price is fair and reasonable, please obtain at least <b>two quotes</b> from other vendors, past experience, or GSA Contract # and attach documents to this request."
        );
    },

    onTpRgChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences();
        if (newValue && newValue === "1") {
            refs.tpJustCtn.show();
            refs.tpTa.show();
        } else {
            refs.tpTa.hide();
            refs.tpJustCtn.hide();
        }
    },
    //BANK-509
    //BANK-544
    /*onCvRgChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences(),
            model = this.getViewModel(),
            req = model.get('generalInfo'),
            isItPurchase = req.get('isItPurchase');
        if (newValue && newValue === "1" && isItPurchase && isItPurchase == 'Y') {
            refs.cvJustCtn.show();
            //refs.cvTa.show();
        } else {
            //refs.cvTa.hide();
            refs.cvJustCtn.hide();
        }
    },*/

    onComboTpJustChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences();
        refs.tpTa.setValue(newValue);
    },

    /*
    onComboCvJustChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences();
        refs.cvTa.setValue(newValue);
    },
    */

    /*onSbRgChange: function (field, newValue, oldValue, eOpts) {
        var refs = this.getReferences();
        if (newValue && newValue === "0") {
            refs.nonSbTa.show();
            refs.nonSbJustCtn.show();
        } else {
            refs.nonSbJustCtn.hide();
            refs.nonSbTa.hide();
        }
    },
    */
    /*
        onComboNonSbJustChange: function (field, newValue, oldValue, eOpts) {
            var refs = this.getReferences();
            refs.nonSbTa.setValue(newValue);
        },
        */

    onViewAdded: function (component, container, pos, eOpts) {
        var model = this.getViewModel(),
            refs = this.getReferences(),
            view = this.view,
            layout = view.getLayout();

        //set a null justification record value in the model initally
        model.set("jrecord", null);
        layout.setActiveItem(refs.cardBlank);
    },

    onViewBeforeShow: function (component, eOpts) {
        var model = this.getViewModel(),
            reqId = model.get("generalInfo").get("requestId"),
            store = Ext.getStore("RequestJustifications"),
            refs = this.getReferences(),
            view = this.view,
            layout = view.getLayout(),
            me = this;

        layout.setActiveItem(refs.cardBlank);

        if (model.get("hasVendor")) {
            store.proxy.url = bcp.config.Runtime.getServerBaseUrl() + "vendors/justification/" + reqId;
            store.load(function () {
                me.updateView(model.get("hasJustification"));
            });
        } else {
            layout.setActiveItem(refs.cardNoVendor);
            refs.tb.hide();
        }
    }
});
