/*
 * File: app/view/NewRequestViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define("bcp.view.NewRequestViewController", {
    extend: "Ext.app.ViewController",
    alias: "controller.newrequest",

    updateRequest: function () {
        var refs = this.getReferences(),
            view = this.view,
            model = this.getViewModel(),
            currentStep = view.getLayout().getActiveItem(),
            form = refs.generalPanel,
            formModel = form.getController().getViewModel(),
            record = model.get("generalInfo"),
            rec = {},
            method = "PUT",
            url = bcp.config.Runtime.getServerBaseUrl() + "requests/" + record.data.requestId;

        if (currentStep.reference == "generalPanel") {
            // check form Valid only for generalpanel which is a form, other tabs are not forms
            if (form.isValid()) {
                //MB-389 for new request take the user's selection
                rec = form.getRecord();
                //console.log ('before update, rec.requesterId = ' + rec.data.requesterId);
                var field = form.down("#requesterId");
                var fieldDesc = form.down("#description");
                //console.log ('before update, field.getValue () = ' + field.getValue ());
                if (field != undefined) rec.data.requesterId = field.getValue();
                if (fieldDesc != undefined) rec.data.description = fieldDesc.getValue();
                //if (Ext.getCmp ('genRequester_Id') != undefined) rec.data.requesterId = Ext.getCmp ('genRequester_Id').getValue ();
                form.updateRecord();
                rec = form.getRecord();
                //console.log ('after update, rec.requesterId = ' + rec.data.requesterId);

                //check if any modification is done
                if (!rec.dirty) {
                    return true;
                }
            } else {
                //general form validation error
                return false;
            }
        } else if (currentStep.reference == "routePanel") {
            //if not from the generalinfo tab, need update if the tab is the routepanel
            //where we moved the comments field to that tab and user could add/change it
            var comments = currentStep.query("textarea[reference=commentsTa]")[0].value;
            if (comments != null && comments.trim().length > 1000) {
                Ext.Msg.alert(
                    "Validation Error",
                    "Maximum allowed characters for the [Additional Comment] field in [Route View] is 1000."
                );
                return false;
            }

            if (comments != record.get("comments")) {
                record.set("comments", comments);
            }
            rec = record;
        } else {
            //other tabs won't change request record
            return true;
        }

        //just update the request record
        Ext.Ajax.request({
            url: url,
            method: method,
            scope: this,
            jsonData: Ext.encode(rec.data),
            success: function (response) {
                bcp.util.CommonUtil.ajaxSuccessHandler(response, function (result) {
                    if (result.data) {
                        rec = Ext.create("bcp.model.BcpRequest", result.data);
                        model.set("generalInfo", rec);
                        formModel.set("record", rec);
                        form.loadRecord(rec);
                    } else {
                        Ext.Msg.alert("Failure", "The request was not updated.");
                    }
                });
            }
        });
    },

    navigate: function (direction) {
        var refs = this.getReferences(),
            layout = this.view.getLayout(),
            progressItems = this.view.tabBar.items.items,
            i,
            activeItem,
            activeIndex,
            count,
            title,
            form;
        //make sure tabs are enabled
        for (i = 1; i < progressItems.length; i++) {
            progressItems[i].enable();
        }

        //before move back a tab, check for if current is a form and if there are form validation error
        activeItem = layout.getActiveItem();
        title = activeItem.getTitle();
        try {
            //for this to work, all sub views must have a formpanel with referenc set to 'form' under the parent container
            //the subview itself cannot be the formpanel
            form = activeItem.lookupReference("form") || activeItem.getForm();
            if (form && form.isVisible() && !form.isValid()) {
                Ext.Msg.alert("Form Validation Error", "Please fix the invalid data in the " + title + " Form");
                //bcp.util.CommonUtil.getInvalidFieldsAlert(activeItem);
                return;
            }
            //same as layout.next() .prev()
            layout[direction]();
        } catch (error) {
            //doesn't have a form
            //NOTE: if form is undefined or form is the element of  formpanel, which makes form.isVisible() undefined
            //the error will bring the code here, which made the current subview blank; if other logic keeps the user
            //in the current subview, user will see the blank view. so try not to be here!
            layout[direction]();
        }

        //same as layout.next() .prev()
        //layout[direction]();

        //find out which tab is active
        activeItem = layout.getActiveItem();
        activeIndex = this.view.items.indexOf(activeItem);
        count = this.view.items.length;

        //for the first tab, disable the prec button, for the last tab, disable the next button
        refs.prevBtn.setDisabled(activeIndex === 0);
        refs.nextBtn.setDisabled(activeIndex === count - 1);
    },

    onShowSubmitBtn: function () {
        this.lookupReference("submitBtn").show();
    },

    onHideSubmitBtn: function () {
        this.lookupReference("submitBtn").hide();
    },

    onHidebbar: function () {
        this.lookupReference("bbar").hide();
        this.getView().tabBar.hide();
        this.getView().getHeader().hide();
    },

    onShowbbar: function () {
        this.lookupReference("bbar").show();
        this.getView().tabBar.show();
        this.getView().getHeader().show();
    },

    onPrev: function (button, e, eOpts) {
        this.navigate("prev");
    },

    onDiscard: function (button, e, eOpts) {
        var me = this,
            refs = this.getReferences(),
            form = refs.generalPanel.getForm(),
            requestId = Number(form.getValues().requestId);
        Ext.MessageBox.show({
            title: "Discard Request Confirmation",
            msg: "This request will be deleted and you won't be able to recover it after the deletion, proceed?",
            width: 350,
            buttons: Ext.MessageBox.YESNO,
            data: requestId,
            fn: function (btn, data, self) {
                if (btn == "yes") {
                    var recordId = self.data;
                    Ext.Ajax.request({
                        url: bcp.config.Runtime.getServerBaseUrl() + "requests/" + recordId,
                        method: "DELETE",
                        success: function (response) {
                            bcp.util.CommonUtil.ajaxSuccessHandler(response, function () {
                                me.redirectTo("#dashboard");
                                Ext.Msg.alert("Success", "The request was deleted successfully.");
                            });
                        },
                        failure: function (response) {
                            me.redirectTo("#dashboard");
                            Ext.Msg.alert("Failure", "The delete request operation failed due to an unexpected error.");
                        }
                    });
                }
            }
        });
    },

    onFileAttachment: function (button, e, eOpts) {
        var model = this.getViewModel(),
            req = model.get("generalInfo");
        var formWindow = this.lookupReference("fileAttachmentsWin");
        if (!formWindow) {
            formWindow = Ext.create("widget.fileattachments", {
                reference: "fileAttachmentsWin",
                bcpReq: req
            });
            this.view.add(formWindow);
        }

        //show window
        formWindow.show();
    },

    onQuickRoute: function (button, e, eOpts) {
        var model = this.getViewModel(),
            reqId = model.get("generalInfo").get("requestId");
        window.open(
            "mailto:MML.SystemsHelp@nist.gov?subject=Question About Bankcard Purchase Request " + reqId + "&body="
        );
        //check if default bankcard holder data is there. If not, show a dropdown for users to
        //select a bankcard holder from a list. Then create a route for the request and return the user
        //to the home view once route is successful
        /*var model=this.getViewModel(),
        reqId= model.get('generalInfo').get('requestId'),
        formWindow=Ext.create('widget.routewindow'),
        //2,'The Bankcard Holder fills out the form'
        newRecord = Ext.create('bcp.model.RequestRoute',{'requestId': reqId,'statusId':2}),
        defaultRoute=model.get('defaultRouteInfo');

        //check if bankcard holder is provided by NIST ORG
        if(defaultRoute.bankcardHolder){
            newRecord.set('typeId',9); //reassigned
            newRecord.set('routeTo',defaultRoute.bankcardHolder.personId);
            newRecord.set('routeToName',defaultRoute.bankcardHolder.name);


            //set record
            formWindow.lookupController().getViewModel().set('record',newRecord);

            //if route to is unknown and the user clicked the button, we need to show and
            //populate the route to combo
            //bind routeTo store if needed
            //formWindow.lookupController().lookupReference('routeToCombo').bindStore(this.getStore('requestVendors'));

            //load record
            formWindow.lookupController().lookupReference('form').getForm().loadRecord(newRecord);
            //set event listeners
            formWindow.on({'cancelRoute':{
                fn: function(win,data){
                    formWindow.destroy();
                },
                scope:this,
            single:true}});
            formWindow.on({'routed':{
                fn: function(win,data){
                    formWindow.destroy();
                    //send user to home view
                    this.redirectTo('#dashboard');
                },
                scope:this,
            single:true}});
            //add window to view
            this.view.add(formWindow);
            //show window
            formWindow.show();
        }else{
            Ext.Msg.alert("Warning", "The system cannot perform this operation because the Bankcard Holder is not defined. "+
            "Please contact your AO or Office Manager. They can define who is the Bankcard Holder for you "+
            "using the NIST Org application");
        }



        /*
        Ext.MessageBox.show({
        title: 'Route Confirmation',
        msg: "This request will be routed to the bankcard holder "+"Sally"+" to fill out the rest of the form, proceed?",
        width:350,
        buttons: Ext.MessageBox.YESNO,
        data: reqId,
        fn: function(btn, data, self){
        if(btn=='yes'){
        Ext.Ajax.request({
        url: (bcp.config.Runtime.getServerBaseUrl()+'request/route'),
        params: {"requestId":reqId},
        success: function (response) {
        bcp.util.CommonUtil.ajaxSuccessHandler(response, function(){
        me.redirectTo('#homeview');
        Ext.Msg.alert('Sucess', 'Request routed successfully.');
        });

        }
        });

        }
        }
        });*/
    },

    onSubmit: function (button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            view = me.view,
            currentStep = view.getLayout().getActiveItem();

        if (currentStep.reference == "routePanel") {
            //submit the request
            refs.routePanel.lookupController().onSubmit();
        } else {
            //why we disallow submit in views other than routepanel?
            //because if user is edit something in a form, the data won't be saved if submit
        }
    },

    //save & continue
    onNext: function (button, e, eOpts) {
        this.navigate("next");
    },

    onTabChange: function (tabPanel, newCard, oldCard, eOpts) {
        //control bottom buttonbar's buttons to make sure the "prev" and "save & continue" are disabled when
        //the user is in first and last tab
        var refs = this.getReferences(),
            layout = this.view.getLayout(),
            activeItem = layout.getActiveItem(),
            activeIndex = this.view.items.indexOf(activeItem),
            count = this.view.items.length;

        refs.prevBtn.setDisabled(activeIndex === 0);
        refs.nextBtn.setDisabled(activeIndex === count - 1);
    },

    onViewAdded: function (component, container, pos, eOpts) {
        //this method only works ONCE when the view is added
        var refs = this.getReferences(),
            form = refs.generalPanel,
            model = this.getViewModel(),
            rec = model.get("currentRequest"),
            formModel = form.getController().getViewModel();

        //disable previous button
        refs.prevBtn.disable();

        //ensure that no one does the ordered item update (BH functions) in this view's item view
        //item use isPurchase; no longer need this
        //model.set('isBaoBch',false);

        //make sure to start with the first panel
        this.view.getLayout().setActiveItem(0);

        //MB-358 since we called the create vo method, the converter outputs the
        //approval amount = estimated total and causes ths issue when update items
        //the approval amount stays the same and the estimate total sometime is greater
        //than the approval amount. See MB-350 for detail.
        //for a saved request, we don't want to update the approval amount
        //it should only be updated when BAO approves the request.

        //TODO: a better way to do this is to create a separate method just to
        //update the approval amount, use backend code to make sure the user calls
        //this method is a BAO and remove approval amount from the common update method
        rec.data.approvalAmount = 0;

        //need to have a generalInfo (request record) in the module view
        //because the request would be updated in it and there are bindings using it
        model.set("generalInfo", rec);

        //form use record
        formModel.set("record", rec);

        form.getController().loadForm(rec);
        form.getController().checkReqStatus(rec.data.statusCode);

        //BANK-488
        var pref = bcp.util.CommonFunctions.getDivisionPreferences(rec.get("divisionId"));

        //add these tabs after the main view is added
        //if not doing it this way and include them in the view directly
        //the child view's added event gets called first, which mess up lots of things
        this.view.add({
            xtype: "vendorpanel",
            listeners: {hidebbar: "onHidebbar", showbbar: "onShowbbar"}
        });

        //BANK-488
        if (pref.get("justPrefVal") == "O" || pref.get("justPrefVal") == "Y") {
            this.view.add({xtype: "justificationpanel"});
        }

        var itemTab = Ext.create("bcp.view.ItemPanel", {
            listeners: {hidebbar: "onHidebbar", showbbar: "onShowbbar"}
        });
        this.view.add(itemTab);

        //BANK-488
        if (pref.get("financePrefVal") == "O" || pref.get("financePrefVal") == "Y") {
            this.view.add({xtype: "financepanel"});
        }

        this.view.add({
            xtype: "routepanel",
            listeners: {
                showSubmitBtn: "onShowSubmitBtn",
                hideSubmitBtn: "onHideSubmitBtn"
            }
        });
    },

    onBeforeTabChange: function (tabPanel, newCard, oldCard, eOpts) {
        var model = this.getViewModel(),
            refs = this.getReferences(),
            layout = this.view.getLayout(),
            rec = model.get("currentRequest"),
            pref = bcp.util.CommonFunctions.getDivisionPreferences(rec.get("divisionId"));

        if (oldCard.reference == "generalPanel") {
            var form = refs.generalPanel;
            if (form.isValid()) {
                //update the request since some data may change in the generalPanel form
                this.updateRequest();
            } else {
                //form value wrong, stay on this view
                bcp.util.CommonUtil.showValidationError("Please fix the invalid data in the [General Info View].");
                return false;
            }
        } else if (oldCard.reference == "routePanel") {
            var comments = oldCard.query("textarea[reference=commentsTa]")[0].value;
            if (comments != null && comments.trim().length > 1000) {
                bcp.util.CommonUtil.showValidationError(
                    "Maximum allowed characters for the [Additional Comment] field in [Route View] is 1000."
                );
                return false;
            } else {
                //update the request since some data may change in the route view
                this.updateRequest();
            }
        } else if (oldCard.reference == "vendorPanel") {
            var vcontroller = oldCard.lookupController(),
                vform = vcontroller.lookupReference("form"),
                saveBtn = vcontroller.lookupReference("btnSave");
            if (vform.isVisible() && saveBtn && saveBtn.isVisible()) {
                if (vform.isValid()) {
                    //update the vendor since some data may change in the vendor form
                    vcontroller.saveVendor();
                } else {
                    bcp.util.CommonUtil.showValidationError("Please fix the invalid data in the Vendor Form");
                    return false;
                }
            }
        } else if (oldCard.reference == "justificationPanel") {
            var jcontroller = oldCard.lookupController(),
                jform = jcontroller.lookupReference("form"),
                jSaveBtn = jcontroller.lookupReference("btnSave");
            //only check form valid if user started filling the form(select a value for the first question isCv);
            //otherwise, let it go through without showing the validation error. This is because when switching tab, sometimes
            //the hasShipping prompt could cause the user to stay in a empty justification tab with a popup error msg asking
            //the user to fix justificaiton data in the form
            //previously used the way of checking justification record to solve this problem but it would create a problem of
            //not saving justification data when user switch tabs
            if (jform.isVisible() && jSaveBtn && jSaveBtn.isVisible()) {
                if (jform.isValid()) {
                    //update the vendor since some data may change in the vendor form
                    jcontroller.save();
                } else {
                    var vals = jform.getForm().getValues();
                    if (vals.isPo !== undefined) {
                        bcp.util.CommonUtil.showValidationError(
                            "Please fix the invalid data in the Justification Form."
                        );
                        return false;
                    } else {
                        //user hasn't fill anything yet, let it go through
                        return true;
                    }
                }
            }
        } else if (oldCard.reference == "itemPanel") {
            //if no shipping entered, prompt the user to enter one instead of wait until submission
            if (pref.get("shippingCostPrefVal") != "A" && !model.get("hasShipping")) {
                var userResp = Ext.Msg.show({
                    title: "Warning",
                    msg:
                        "Shipping and handling cost is required for submitting a request. " +
                        "Would you like to add it now?",
                    width: 300,
                    closable: false,
                    buttons: Ext.Msg.YESNO,
                    multiline: false,
                    fn: function (buttonValue, inputText, showConfig) {
                        if (buttonValue === "yes") {
                            layout.setActiveItem(oldCard);
                            oldCard.lookupController().addShipping();
                            return false;
                        } else {
                            return true;
                        }
                    },
                    icon: Ext.Msg.WARNING
                });
                return userResp;
            }
        }

        if (newCard.reference == "itemPanel") {
            if (!model.get("hasShipping")) {
                //BANK-488
                if (pref.get("shippingCostPrefVal") == "A") {
                    var icontroller = newCard.lookupController();
                    icontroller.autoCreateShipping(pref.get("shippingCostPrefValDetail"));
                }
            }
        }
    }
});
