/*
 * File: app/view/PartialDeliveryWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.PartialDeliveryWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.partialdeliverywindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    config: {store: {}},

    modal: true,
    height: 261,
    width: 329,
    defaultFocus: 'noButton',
    layout: 'card',
    closable: false,
    defaultButton: 'noBtn',
    title: 'Partial Delivery',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            flex: 1,
            bodyPadding: 10,
            layout: {type: 'vbox', align: 'stretch'},
            items: [
                {
                    xtype: 'displayfield',
                    value: 'Please specify the quantity of the delivered item below. The system will split the select item into two items. One item will have the delivered quantity. The other item will have the undelivered quantity. '
                },
                {
                    xtype: 'numberfield',
                    reference: 'delQuantityNf',
                    fieldLabel: 'Delivered Quantity',
                    labelWidth: 150,
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    allowDecimals: false,
                    allowExponential: false,
                    minValue: 1
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    defaultButtonUI: 'default',
                    layout: {type: 'hbox', pack: 'center'},
                    items: [
                        {
                            xtype: 'button',
                            reference: 'noBtn',
                            itemId: 'noButton',
                            width: 80,
                            text: 'Cancel',
                            listeners: {click: 'onNoButtonClick'}
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            width: 80,
                            text: 'Apply',
                            listeners: {click: 'onApplyButtonClick'}
                        }
                    ]
                }
            ]
        }
    ],

    onNoButtonClick: function (button, e, eOpts) {
        this.fireEvent('cancelPartialDelivery');
    },

    onApplyButtonClick: function (button, e, eOpts) {
        var quantity = this.query('numberfield')[0].value;
        if (quantity === 0) {
            Ext.Msg.alert(
                'Warning',
                'The quantity of the delivered item cannot be zero.'
            );
        } else {
            this.fireEvent('applyPartialDelivery', quantity);
        }
    }
});
