/*
 * File: app/view/PersonAsVendorWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.PersonAsVendorWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.personasvendorwindow',

    requires: [
        'bcp.view.PersonAsVendorWindowViewModel',
        'bcp.view.PersonAsVendorWindowViewController',
        'Ext.form.field.Display',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'personasvendorwindow',
    viewModel: {type: 'personasvendorwindow'},
    modal: true,
    height: 353,
    padding: 10,
    width: 513,
    layout: 'anchor',
    closable: false,
    title: 'Add a Convenience Check',

    items: [
        {
            xtype: 'displayfield',
            reference: 'note',
            cls: 'bcp_notice',
            value: 'For adding a person such as a guest speaker as a vendor, only fill these fields so the system <b>does not store PII</b>'
        },
        {
            xtype: 'form',
            reference: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'vendorId'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'convenienceCheck'
                },
                {
                    xtype: 'textfield',
                    reference: 'personNameTf',
                    anchor: '100%',
                    fieldLabel: 'Name of Vendor/Individual',
                    labelAlign: 'top',
                    name: 'vendorName',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    reference: 'checkNumberTf',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Convenience Check Number',
                    name: 'convenienceCheckNumber'
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    name: 'convenienceCheckJust',
                    maxLength: 1000,
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText:
                        'Provide justification for not using electronic payment'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    defaultButtonUI: 'default',
                    layout: {type: 'hbox', pack: 'center'},
                    items: [
                        {
                            xtype: 'button',
                            anchor: '100%',
                            minWidth: 100,
                            text: 'Cancel',
                            listeners: {click: 'onCancel'}
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            anchor: '100%',
                            minWidth: 100,
                            text: 'Save',
                            listeners: {click: 'onSave'}
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {show: 'onWindowShow'}
});
