/*
 * File: app/view/PtcWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.PtcWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.ptcwindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    modal: true,
    height: 214,
    width: 400,
    defaultFocus: 'noButton',
    layout: 'card',
    closable: false,
    defaultButton: 'noBtn',
    title: 'Apply Project Task Code to All Items',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            flex: 1,
            bodyPadding: 10,
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'comboPtc',
                    fieldLabel: 'Project Task Code',
                    labelAlign: 'top',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    anyMatch: true,
                    displayField: 'display',
                    minChars: 2,
                    queryMode: 'local',
                    queryParam: 'filter',
                    store: 'ProjectTaskCodes',
                    valueField: 'code'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    defaultButtonUI: 'default',
                    layout: {type: 'hbox', pack: 'center'},
                    items: [
                        {
                            xtype: 'button',
                            reference: 'noBtn',
                            itemId: 'noButton',
                            width: 80,
                            text: 'Cancel',
                            listeners: {click: 'onNoButtonClick'}
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            width: 80,
                            text: 'Apply',
                            listeners: {click: 'onApplyButtonClick'}
                        }
                    ]
                }
            ]
        }
    ],

    onNoButtonClick: function (button, e, eOpts) {
        this.fireEvent('cancelPTC');
    },

    onApplyButtonClick: function (button, e, eOpts) {
        var val = this.query('combobox')[0].value.trim();

        var v = new RegExp('^[a-zA-Z0-9]{7}-[a-zA-Z0-9]{3}$', 'i');
        if (!v.test(val)) {
            Ext.Msg.alert(
                'Validation Error',
                'A valid project task code should be in the xxxxxxx-xxx format where [x] is a alphanumeric character.'
            );
            return;
        }
        this.fireEvent('applyPTC', this.query('combobox')[0].value);
    }
});
