/*
 * File: app/view/SavedRequestsViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.SavedRequestsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.savedrequests',

    requires: ['Ext.data.ChainedStore'],

    data: {viewState: 'list'},

    stores: {savedRequests: {source: 'SavedRequests'}}
});
