/*
 * File: app/view/SavedRequestsViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.SavedRequestsViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.savedrequests',

    onAddNew: function (button, e, eOpts) {
        this.redirectTo('#createrequest');
    },

    onResume: function (button, e, eOpts) {
        var model = this.getViewModel(),
            requestId = model.get('record').data.requestId;
        this.redirectTo('#newrequest/' + requestId);
    },

    onDiscard: function (button, e, eOpts) {
        var store = Ext.getStore('SavedRequests'),
            requestId = this.getViewModel().get('record').data.requestId;
        Ext.MessageBox.show({
            title: 'Discard Request Confirmation',
            msg: "This request will be deleted and you won't be able to recover it after the deletion, proceed?",
            width: 350,
            buttons: Ext.MessageBox.YESNO,
            data: requestId,
            fn: function (btn, data, self) {
                if (btn == 'yes') {
                    var recordId = self.data;
                    Ext.Ajax.request({
                        url:
                            bcp.config.Runtime.getServerBaseUrl() +
                            'requests/' +
                            recordId,
                        method: 'DELETE',
                        success: function (response) {
                            Ext.Msg.alert(
                                'Sucess',
                                'Request deleted successfully.'
                            );
                            store.reload();
                        },
                        failure: function (response) {
                            Ext.Msg.alert(
                                'Failed',
                                'The delete request operation failed due to an unexpected error.'
                            );
                            store.reload();
                        }
                    });
                }
            }
        });
    },

    onViewAdded: function (component, container, pos, eOpts) {
        var model = this.getViewModel();
        //when actions within the view or its subview finishes, it should return to
        model.set('returnToView', this.view.routeId);
    }
});
