/*
 * File: app/view/VendorsViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.VendorsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.vendors',

    requires: ['Ext.data.ChainedStore', 'Ext.util.Filter'],

    stores: {
        sharedLvls: {
            source: 'LkSharedLevels',
            filters: {operator: '!=', property: 'id', value: 0}
        },
        sharedVendors: {source: 'SharedVendors'},
        groups: {source: 'Groups'},
        divisions: {source: 'Divisions'},
        ous: {source: 'Ous'}
    }
});
