/*
 * File: app/view/VendorsViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.view.VendorsViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.vendors',

    showView: function (view) {
        var layout = this.getReferences().display.getLayout();
        layout.setActiveItem(this.lookupReference(view));
    },

    add: function (button, e, eOpts) {
        var list = this.lookupReference('list'),
            rowEditing = list.getPlugin('rowEditPlugin'),
            store = Ext.getStore('SharedVendors'),
            model = this.getViewModel(),
            user = model.get('loggedInUser');

        rowEditing.cancelEdit();

        // Create a model instance
        var r = Ext.create('model.vendor', {
            vendorName: '',
            vendorId: 0,
            ouId: user.ouId,
            divisionId: user.divisionId,
            groupId: user.groupId,
            shared: 3,
            isActive: true
        });

        //filter will prevent the new row to show
        this.onReset();

        //make sure inserted row is at the top
        store.sort('vendorName', 'ASC');

        store.insert(0, r);
        rowEditing.startEdit(0, 0);
    },

    remove: function (button, e, eOpts) {
        var list = this.lookupReference('list'),
            rowEditing = list.getPlugin('rowEditPlugin'),
            store = Ext.getStore('SharedVendors'),
            model = this.getViewModel(),
            rec = list.selModel.lastSelected,
            recOuId = 0,
            loggedInUser = model.get('loggedInUser'),
            userOuId = loggedInUser.ouId,
            vendorId = 0;

        rowEditing.cancelEdit();

        if (rec) {
            vendorId = rec.get('vendorId');

            if (vendorId === 0) {
                store.remove(rec);
            } else {
                recOuId = rec.get('ouId');
                //remove vendor shared by other OUs is not allowed
                if (userOuId != recOuId) {
                    Ext.Msg.alert(
                        'Privilege Error',
                        'You can do remove vendors shared by other OUs.'
                    );
                    return;
                }
                // Ask user to confirm this action
                Ext.Msg.confirm(
                    'Confirm Delete',
                    'Are you sure you want to delete this vendor?',
                    function (result) {
                        // User confirmed yes
                        if (result == 'yes') {
                            Ext.Ajax.request({
                                url: '/empbc/v1/vendors/shared/' + vendorId,
                                method: 'DELETE',
                                success: function (response) {
                                    Ext.getStore('SharedVendors').reload();
                                }
                            });
                        }
                    }
                );
            }
        }
    },

    onVendorTfFilterChange: function (field, newValue, oldValue, eOpts) {
        this.lookupReference('list').store.filter([
            {
                filterFn: function (record) {
                    if (newValue !== null && newValue.length > 0) {
                        var val = newValue.toLowerCase();
                        return (
                            record
                                .get('vendorName')
                                .toLowerCase()
                                .indexOf(val) > -1
                        );
                    } else {
                        return true;
                    }
                },
                id: 'vendortextflt'
            }
        ]);
    },

    onReset: function (button, e, eOpts) {
        this.lookupReference('list').store.clearFilter();
        this.lookupReference('tfFilter').reset();
    },

    select: function (rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);
        // Show details
        //this.showView('details');
    },

    onRowEditingCanceledit: function (editor, context, eOpts) {
        // Canceling editing of a locally added, unsaved record: remove it
        if (context.record.phantom) {
            var store = this.getStore('vendors');
            store.remove(context.record);
        }
    },

    onRowEditingEdit: function (editor, context, eOpts) {
        //only update if users changed something
        if (context.record.dirty) {
            var vname = context.record.get('vendorName').trim(),
                store = this.lookupReference('list').store,
                v = new RegExp('^' + vname + '$', 'i'),
                hasDup = -1;
            //for create a new vendor, do a check
            if (context.record.id === 0) {
                hasDup = store.findBy(function (rec, id) {
                    //the record itself is already in the store, so we have to check id!=0
                    if (v.test(rec.data.vendorName.trim()) && rec.id !== 0)
                        return true;
                    else return false;
                });
            }

            if (hasDup === -1) {
                Ext.Ajax.request({
                    url: '/empbc/v1/vendors/shared',
                    jsonData: Ext.encode(context.record.data),
                    method: context.record.id === 0 ? 'POST' : 'PUT',
                    scope: this,
                    success: function (response) {
                        Ext.getStore('SharedVendors').reload();
                    }
                });
            } else {
                context.record.reject();
                Ext.Msg.alert(
                    'Validation Error',
                    'A Vendor with the exact name of [' +
                        vname +
                        '] already exists.'
                );
            }
        }
    },

    onRowEditingBeforeEdit: function (editor, context, eOpts) {
        //NOTE: more privilege checks maybe needed here
        var recOuId = context.record.get('ouId'),
            model = this.getViewModel(),
            loggedInUser = model.get('loggedInUser'),
            userOuId = loggedInUser.ouId;

        //edit vendor shared by other OUs not allowed
        if (userOuId != recOuId) {
            Ext.Msg.alert(
                'Privilege Error',
                'You cannot edit vendors shared by other OUs.'
            );
            return false;
        }
    },

    onViewAdded: function (component, container, pos, eOpts) {
        var store = Ext.getStore('SharedVendors'),
            model = this.getViewModel(),
            loggedInUser = model.get('loggedInUser'),
            ouStore = this.getStore('ous'),
            divStore = this.getStore('divisions'),
            grpStore = this.getStore('groups');

        store.load();

        ouStore.addFilter({
            operator: '==',
            property: 'ouId',
            value: loggedInUser.ouId
        });

        divStore.addFilter({
            operator: '==',
            property: 'ouId',
            value: loggedInUser.ouId
        });

        grpStore.addFilter({
            operator: '==',
            property: 'ouId',
            value: loggedInUser.ouId
        });
    }
});
