/* Formatted on 9/6/2018 2:14:03 PM (QP5 v5.318) */
CREATE OR REPLACE FORCE VIEW BCPMS_OWNER.V_OBJCLASS
(
    CODE,
    DESCRIPTION
)
BEQUEATH DEFINER
AS
    SELECT code, description
      FROM OBJECT_CLASS
     WHERE active_status = 'Y';


CREATE OR REPLACE SYNONYM BCPMS_APP.V_OBJCLASS FOR BCPMS_OWNER.V_OBJCLASS;


AUDIT RENAME ON BCPMS_OWNER.V_OBJCLASS BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.V_OBJCLASS BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT SELECT ON BCPMS_OWNER.V_OBJCLASS TO BCPMS_APP;