/* Formatted on 9/6/2018 2:14:04 PM (QP5 v5.318) */
CREATE OR REPLACE FORCE VIEW BCPMS_OWNER.V_PROJTSK
(
    PROJECT_CODE,
    FUND_CODE,
    P_ORG1_CODE,
    P_ORG2_CODE,
    P_ORG3_CODE,
    P_ORG4_CODE,
    P_ORG5_CODE,
    P_ORG6_CODE,
    P_ORG7_CODE,
    PROJECT_DESCR,
    PROJECT_TYPE,
    TASK_CODE,
    TASK_DESCR,
    BEGIN_DATE
)
BEQUEATH DEFINER
AS
    SELECT "PROJECT_CODE",
           "FUND_CODE",
           "P_ORG1_CODE",
           "P_ORG2_CODE",
           "P_ORG3_CODE",
           "P_ORG4_CODE",
           "P_ORG5_CODE",
           "P_ORG6_CODE",
           "P_ORG7_CODE",
           "PROJECT_DESCR",
           "PROJECT_TYPE",
           "TASK_CODE",
           "TASK_DESCR",
           "BEGIN_DATE"
      FROM PROJECT_TASK;


CREATE OR REPLACE SYNONYM BCPMS_APP.V_PROJTSK FOR BCPMS_OWNER.V_PROJTSK;


AUDIT RENAME ON BCPMS_OWNER.V_PROJTSK BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.V_PROJTSK BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT SELECT ON BCPMS_OWNER.V_PROJTSK TO BCPMS_APP;