DROP TABLE BCPMS_OWNER.BCH_INIT_PREFERENCES CASCADE CONSTRAINTS;

CREATE TABLE BCPMS_OWNER.BCH_INIT_PREFERENCES
(
  ID         INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 61 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  DIV_ID     NUMBER                             NOT NULL,
  PEOPLE_ID  NUMBER                             NOT NULL,
  INITIALS   VARCHAR2(2 BYTE)                   NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX BCPMS_OWNER.BCH_INIT_PREFERENCES_PK ON BCPMS_OWNER.BCH_INIT_PREFERENCES
(ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX BCPMS_OWNER.IDX_DIVID_INIT ON BCPMS_OWNER.BCH_INIT_PREFERENCES
(DIV_ID, INITIALS)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX BCPMS_OWNER.IDX_DIVID_PID ON BCPMS_OWNER.BCH_INIT_PREFERENCES
(DIV_ID, PEOPLE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE BCPMS_OWNER.BCH_INIT_PREFERENCES ADD (
  CONSTRAINT BCH_INIT_PREFERENCES_PK
  PRIMARY KEY
  (ID)
  USING INDEX BCPMS_OWNER.BCH_INIT_PREFERENCES_PK
  ENABLE VALIDATE);
  
  GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.BCH_INIT_PREFERENCES TO BCPMS_APP;