--
-- EMAIL_PKG  (Package) 
--
--  Dependencies: 
--   APP_SETTINGS (Table)
--   DB_ERROR (Table)
--   GET_USER_EMAIL (Function)
--   GET_USER_NAME (Function)
--   NIST_USER (Table)
--   NIST_USER_ACTIVE (Table)
--   PREFERENCES (Table)
--   REQUEST (Table)
--   ROUTE (Table)
--   SYSTEM_VARS (Table)
--   V_REQUEST_CURRENT_ROUTE (View)
--   DBMS_OUTPUT (Synonym)
--   DUAL (Synonym)
--   UTL_MAIL (Synonym)
--   STANDARD (Package)
--
/* Formatted on 2/28/2022 9:13:07 PM (QP5 v5.360) */
CREATE OR REPLACE PACKAGE EMAIL_PKG
AS
    PROCEDURE REMINDER_CHECK;

    PROCEDURE NOTIFY_BCH_OF_UP_ORDER;

    PROCEDURE CHECK_REQUEST_FOR_NO_BCH;

    PROCEDURE CHECK_REQUEST_FOR_INVALID_BCH;
END EMAIL_PKG;
/


--
-- EMAIL_PKG  (Package Body) 
--
/* Formatted on 2/28/2022 9:13:07 PM (QP5 v5.360) */
CREATE OR REPLACE PACKAGE BODY EMAIL_PKG
AS
    /*
    Created Date:                   October 2020
    Creator:                        ppg
    Purpose:                        Handles all email notifications for the NIST Employee Bankcard application

    10/7/21:                        added a check in CHECK_REQUEST_FOR_NO_BCH so if no match found, no email out
    */

    g_sid                         VARCHAR2 (20) := '';
    g_prod                        BOOLEAN := FALSE;
    g_app_url                     VARCHAR2 (200) := '';
    g_dfweekday                   VARCHAR2 (9) := 'TUESDAY';

    g_from                        VARCHAR2 (100) := 'empbc@nist.gov';
    g_to                          VARCHAR2 (300) := '';
    g_cc                          VARCHAR2 (300) := '';
    g_bcc                         VARCHAR2 (300) := '';
    s_subject_reminder            VARCHAR2 (500) := 'REMINDER NOTIFICATION';
    s_subject_notify              VARCHAR2 (500)
                                      := 'NOTIFICATION OF UPCOMING NEED BY DATE';
    s_subject_check_no_bch        VARCHAR2 (500) := 'CHECK_REQUEST_FOR_NO_BCH';
    s_subject_check_invalid_bch   VARCHAR2 (500)
                                      := 'CHECK_REQUEST_FOR_INVALID_BCH';
    g_subject                     VARCHAR2 (500) := '';
    g_header                      VARCHAR2 (1000) := 'Dear ';
    s_msg_reminder                VARCHAR2 (3000)
        := 'This is a reminder that a bankcard purchase request $1 is waiting for you';
    s_msg_notify                  VARCHAR2 (3000)
        := 'This is a notification that a bankcard purchase request $1 has a need by date on $2 but the purchase is still not made.';
    s_msg_check_no_bch            VARCHAR2 (3000)
        := 'This is to notify you that the following requests have no BCH:<br><br>$1';
    s_msg_check_invalid_bch       VARCHAR2 (3000)
        := 'This is to notify you that the following requests have an invalid BCH:<br><br>$1';
    g_msg                         VARCHAR2 (3000) := '';
    g_msg_end                     VARCHAR2 (20) := '';
    g_footer                      VARCHAR2 (400)
        := '<br><br>This message is auto generated by the MML Bankcard Request and Approval system. Please do not reply to this email.';
    g_to_name                     VARCHAR2 (30) := '';
    g_errcode                     VARCHAR2 (20) := '';
    g_errmsg                      VARCHAR2 (2000) := '';

    FUNCTION IS_PROD
        RETURN BOOLEAN
    IS
    BEGIN
        IF g_sid IS NOT NULL
        THEN
            RETURN g_prod;
        END IF;

        SELECT UPPER (SYS_CONTEXT ('USERENV', 'DB_NAME'))
          INTO g_sid
          FROM DUAL;

        IF g_sid = 'MML2PDI'
        THEN
            g_prod := TRUE;
        END IF;

        RETURN g_prod;
    END;

    PROCEDURE GET_APP_URL
    IS
    BEGIN
        SELECT APP_URL INTO g_app_url FROM APP_SETTINGS;

        g_app_url := g_app_url || '#pendingrequests/';
    END;

    PROCEDURE UPDATE_LAST_EMAIL_DATE (route_id IN ROUTE.ROUTE_ID%TYPE)
    IS
    BEGIN
        IF route_id IS NULL OR route_id < 1
        THEN
            RETURN;
        END IF;

        UPDATE ROUTE
           SET LAST_EMAIL_DATE = SYSDATE
         WHERE ROUTE_ID = route_id;
    EXCEPTION
        WHEN OTHERS
        THEN
            g_errcode := SQLCODE;
            g_errmsg := SUBSTR (SQLERRM, 1, 2000);

            INSERT INTO db_error (source,
                                  user_id,
                                  code,
                                  MESSAGE)
                 VALUES ('SEND_EMAIL',
                         route_id,
                         g_errcode,
                         g_errmsg);
    END;

    PROCEDURE SEND_EMAIL
    IS
    BEGIN
        IF    g_from IS NULL
           OR LENGTH (g_from) < 5
           OR g_to IS NULL
           OR LENGTH (g_to) < 5
        THEN
            RETURN;
        END IF;

        IF    g_subject IS NULL
           OR LENGTH (g_subject) < 10
           OR g_msg IS NULL
           OR LENGTH (g_msg) < 10
        THEN
            RETURN;
        END IF;

        UTL_MAIL.SEND (sender       => g_from,
                       recipients   => g_to,
                       bcc          => g_bcc,
                       subject      => g_subject,
                       mime_type    => 'text/html',
                       MESSAGE      => g_msg);
    EXCEPTION
        WHEN OTHERS
        THEN
            g_errcode := SQLCODE;
            g_errmsg := SUBSTR (SQLERRM, 1, 2000);

            INSERT INTO db_error (source,
                                  user_id,
                                  code,
                                  MESSAGE)
                 VALUES ('SEND_EMAIL',
                         0,
                         g_errcode,
                         g_errmsg);
    END;

    PROCEDURE REMINDER_CHECK
    /*
    Created Date:                   October 2020
    Creator:                        ppg
    Purpose:                        periodically send email notifications to remind the reviewers, BAOs and BCHs of a pending action
    To test:                        exec BCPMS_OWNER.EMAIL_PKG.REMINDER_CHECK;
    */
    IS
        l_request_id        INTEGER := 0;
        l_route_type_id     INTEGER := 0;
        l_to_id             INTEGER := 0;
        l_route_date        DATE := NULL;
        l_last_email_date   DATE := NULL;
        l_today_weekday     VARCHAR2 (10) := '';
        l_pref_weekday      VARCHAR2 (10) := '';
        l_counter           INTEGER := 0;
        l_today             VARCHAR2 (9) := '';
    BEGIN
        get_app_url;

        SELECT TRIM (TO_CHAR (SYSDATE, 'DAY')) INTO l_today FROM DUAL;

        DECLARE
            CURSOR cur_route IS
                  SELECT REQUEST_ID,
                         ROUTE_ID,
                         ROUTE_TYPE_ID,
                         ROUTE_BY,
                         REROUTE_BY,
                         ROUTE_TO,
                         ROUTE_DATE,
                         LAST_EMAIL_DATE
                    FROM ROUTE r
                         LEFT OUTER JOIN PREFERENCES p
                             ON r.ROUTE_TO = p.PEOPLE_ID
                   WHERE     (   p.PREF_VALUE IS NULL AND l_today = g_dfweekday
                              OR UPPER (p.PREF_VALUE) = l_today)
                         AND ROUTE_TYPE_ID IN (1,
                                               2,
                                               3,
                                               11)
                         AND TRUNC (route_date) > SYSDATE - 120 --add this condition to stop reminders for requests older than 120 days
                         AND r.ROUTE_ID = (  SELECT ROUTE_ID
                                               FROM ROUTE s
                                              WHERE r.REQUEST_ID = s.REQUEST_ID
                                           ORDER BY ROUTE_ID DESC
                                              FETCH FIRST ROWS ONLY)
                ORDER BY REQUEST_ID;
        BEGIN
            FOR rec IN cur_route
            LOOP
                l_request_id := rec.REQUEST_ID;
                l_route_date := rec.ROUTE_DATE;
                l_last_email_date := rec.LAST_EMAIL_DATE;

                l_route_type_id := rec.ROUTE_TYPE_ID;
                l_to_id := rec.ROUTE_TO;
                g_to := get_user_email (l_to_id);
                g_to_name := get_user_name (l_to_id);

                IF l_route_type_id = 1 OR l_route_type_id = 11
                THEN
                    g_msg_end := ' to review.';
                ELSIF l_route_type_id = 2
                THEN
                    g_msg_end := ' to approve.';
                ELSIF l_route_type_id = 3
                THEN
                    g_msg_end := ' to order.';
                END IF;

                g_subject := s_subject_reminder;

                IF NOT is_prod
                THEN
                    l_counter := l_counter + 1;
                    --if l_counter > 3 then continue; end if; --in dev and test we don't want to receive too many emails

                    g_to := 'xinweiw@nist.gov';
                    g_bcc := g_to;
                    g_subject :=
                           '(#'
                        || l_counter
                        || ' Sent from '
                        || g_sid
                        || ') '
                        || s_subject_reminder;
                END IF;

                g_msg :=
                       g_header
                    || g_to_name
                    || ':<br><br>'
                    || REPLACE (
                           s_msg_reminder,
                           '$1',
                              l_request_id
                           || ' ('
                           || g_app_url
                           || l_request_id
                           || ')')
                    || g_msg_end
                    || g_footer;

                send_email;

                update_last_email_date (rec.ROUTE_ID);
            END LOOP;
        END;
    EXCEPTION
        WHEN OTHERS
        THEN
            g_errcode := SQLCODE;
            g_errmsg := SUBSTR (SQLERRM, 1, 2000);

            INSERT INTO db_error (source,
                                  user_id,
                                  code,
                                  MESSAGE)
                 VALUES ('REMINDER_CHECK',
                         l_request_id,
                         g_errcode,
                         g_errmsg);
    END;

    PROCEDURE NOTIFY_BCH_OF_UP_ORDER
    /*
    Created Date:                   Decemberber 2020
    Creator:                        ppg
    Purpose:                        Notify BCHs of upcoming unpurchased orders when their need_by_date is within a defined number of days
    To test:                        exec BCPMS_OWNER.EMAIL_PKG.NOTIFY_BCH_OF_UP_ORDER;

    6/11/2021: changed to use v_request_current_route becuase the original query doesn't exclude records correctly
               e.g. run original query on 6/11/21, request 36604 was purchased on 6/8/21 but was still showing in the
               returned records. (Megan reported)
    */
    IS
        l_request_id   INTEGER := 0;
        l_to_id        INTEGER := 0;
        l_nbd          VARCHAR2 (10) := '';
        l_threshold    INTEGER := 7;
        l_counter      INTEGER := 0;
    BEGIN
        get_app_url;

        SELECT TO_NUMBER (SYS_VALUE)
          INTO l_threshold
          FROM SYSTEM_VARS
         WHERE SYS_KEY = 'NEED_BY_DATE_THRESHOLD';

        IF l_threshold IS NULL OR l_threshold < 1 OR l_threshold > 14
        THEN
            l_threshold := 7;
        END IF;

        DECLARE
            CURSOR cur_route IS
                  SELECT r.REQUEST_ID,
                         BANKCARD_HOLDER_ID,
                         TO_CHAR (NEEDED_BY_DATE, 'mm/dd/yyyy')     AS nbd
                    FROM v_request_current_route r, --route r
                                                    REQUEST q
                   WHERE     r.REQUEST_ID = q.REQUEST_ID
                         AND q.needed_by_date IS NOT NULL
                         AND q.bankcard_holder_id IS NOT NULL
                         AND EXISTS
                                 (SELECT *
                                    FROM NIST_USER
                                   WHERE q.bankcard_holder_id = people_id)
                         AND TRUNC (NEEDED_BY_DATE) - TRUNC (SYSDATE) =
                             l_threshold
                         --and trunc (NEEDED_BY_DATE) - trunc (sysdate) < l_threshold -- for testing
                         AND r.ROUTE_TYPE_ID IN (1,
                                                 2,
                                                 3,
                                                 11)
                --and r.ROUTE_ID = (
                --    select ROUTE_ID from ROUTE s
                --    where r.REQUEST_ID = s.REQUEST_ID
                --    order by r.ROUTE_ID desc fetch first rows only)
                ORDER BY r.REQUEST_ID;
        BEGIN
            FOR rec IN cur_route
            LOOP
                l_request_id := rec.REQUEST_ID;
                l_to_id := rec.BANKCARD_HOLDER_ID;

                l_nbd := rec.nbd;
                g_to := get_user_email (l_to_id);
                g_to_name := get_user_name (l_to_id);

                g_msg :=
                       g_header
                    || g_to_name
                    || ':<br><br>'
                    || s_msg_notify
                    || g_footer;
                g_msg :=
                    REPLACE (
                        g_msg,
                        '$1',
                           l_request_id
                        || ' ('
                        || g_app_url
                        || l_request_id
                        || ')');
                g_msg := REPLACE (g_msg, '$2', l_nbd);

                g_subject := s_subject_notify;

                IF NOT is_prod
                THEN
                    l_counter := l_counter + 1;

                    IF l_counter > 3
                    THEN
                        CONTINUE;
                    END IF; --in dev and test we don't want to receive too many emails

                    g_to := 'xinweiw@nist.gov';
                    g_bcc := g_to;
                    g_subject :=
                           '(#'
                        || l_counter
                        || ' Sent from '
                        || g_sid
                        || ') '
                        || s_subject_notify;
                END IF;

                send_email;
            --dbms_output.put_line ('request id = ' || l_request_id);
            END LOOP;
        END;
    EXCEPTION
        WHEN OTHERS
        THEN
            g_errcode := SQLCODE;
            g_errmsg := SUBSTR (SQLERRM, 1, 2000);

            INSERT INTO db_error (source,
                                  user_id,
                                  code,
                                  MESSAGE)
                 VALUES ('NOTIFY_BCH_OF_UP_ORDER',
                         l_request_id,
                         g_errcode,
                         g_errmsg);

            DBMS_OUTPUT.put_line (
                   g_errcode
                || ' - '
                || 'NOTIFY_BCH_OF_UP_ORDER, request id = '
                || l_request_id
                || ', '
                || g_errmsg);
    END;

    PROCEDURE CHECK_REQUEST_FOR_NO_BCH
    /*
    Created Date:                   January 2021
    Creator:                        ppg
    Purpose:                        Check requests for null BCH, if found, notify the MML Systems Support
    To test:                        exec BCPMS_OWNER.EMAIL_PKG.CHECK_REQUEST_FOR_NO_BCH;
    */
    IS
        l_request_id   INTEGER := 0;
        l_msg          VARCHAR2 (3000) := '';
        is_found_rec   BOOLEAN := FALSE;
    BEGIN
        DECLARE
            CURSOR cur_route IS
                  SELECT r.REQUEST_ID, BANKCARD_HOLDER_ID
                    FROM v_request_current_route r, REQUEST q
                   WHERE     r.REQUEST_ID = q.REQUEST_ID
                         AND q.bankcard_holder_id IS NULL
                         AND r.ROUTE_TYPE_ID IN (1,
                                                 2,
                                                 3,
                                                 11)
                --and r.ROUTE_ID = (
                --    select ROUTE_ID from ROUTE s
                --    where r.REQUEST_ID = s.REQUEST_ID
                --    order by r.ROUTE_ID desc fetch first rows only)
                ORDER BY r.REQUEST_ID;
        BEGIN
            FOR rec IN cur_route
            LOOP
                is_found_rec := TRUE;
                l_request_id := rec.REQUEST_ID;

                IF l_msg IS NOT NULL
                THEN
                    l_msg := l_msg || ',<br>';
                END IF;

                l_msg := l_msg || l_request_id;
            END LOOP;

            g_subject := s_subject_check_no_bch;
            g_to := 'MML.SystemsHelp@nist.gov';
            g_bcc := 'xinwei.wen@nist.gov';
            g_msg :=
                   g_header
                || 'MML Systems Supports:<br><br>'
                || REPLACE (s_msg_check_no_bch, '$1', l_msg)
                || g_footer;

            IF NOT is_prod
            THEN
                g_to := 'xinweiw@nist.gov';
                g_bcc := g_to;
                g_subject :=
                    '(Sent from ' || g_sid || ') ' || s_subject_check_no_bch;
            END IF;

            --use this to check for any match found; if no match, we don't really need to send the email
            IF is_found_rec
            THEN
                send_email;
            END IF;
        END;
    EXCEPTION
        WHEN OTHERS
        THEN
            g_errcode := SQLCODE;
            g_errmsg := SUBSTR (SQLERRM, 1, 2000);

            INSERT INTO db_error (source,
                                  user_id,
                                  code,
                                  MESSAGE)
                 VALUES ('CHECK_REQUEST_FOR_NO_BCH',
                         l_request_id,
                         g_errcode,
                         g_errmsg);

            DBMS_OUTPUT.put_line (
                   g_errcode
                || ' - '
                || 'CHECK_REQUEST_FOR_NO_BCH, request id = '
                || l_request_id
                || ', '
                || g_errmsg);
    END;

    PROCEDURE CHECK_REQUEST_FOR_INVALID_BCH
    /*
    Created Date:                   January 2021
    Creator:                        ppg
    Purpose:                        Check requests for invalid BCH, if found, notify the MML Systems Support
    To test:                        exec BCPMS_OWNER.EMAIL_PKG.CHECK_REQUEST_FOR_INVALID_BCH;
    */
    IS
        l_request_id   INTEGER := 0;
        l_msg          VARCHAR2 (3000) := '';
    BEGIN
        DECLARE
            CURSOR cur_route IS
                  SELECT r.REQUEST_ID, BANKCARD_HOLDER_ID
                    FROM ROUTE r, REQUEST q
                   WHERE     r.REQUEST_ID = q.REQUEST_ID
                         AND q.bankcard_holder_id IS NOT NULL
                         AND NOT EXISTS
                                 (SELECT *
                                    FROM NIST_USER_ACTIVE
                                   WHERE q.bankcard_holder_id = people_id)
                         AND r.ROUTE_TYPE_ID IN (1,
                                                 2,
                                                 3,
                                                 11)
                         AND r.ROUTE_ID = (  SELECT ROUTE_ID
                                               FROM ROUTE s
                                              WHERE r.REQUEST_ID = s.REQUEST_ID
                                           ORDER BY r.ROUTE_ID DESC
                                              FETCH FIRST ROWS ONLY)
                ORDER BY r.REQUEST_ID;
        BEGIN
            FOR rec IN cur_route
            LOOP
                l_request_id := rec.REQUEST_ID;

                IF l_msg IS NOT NULL
                THEN
                    l_msg := l_msg || ',<br>';
                END IF;

                l_msg := l_msg || l_request_id;
            END LOOP;

            g_subject := s_subject_check_invalid_bch;
            g_to := 'MML.SystemsHelp@nist.gov';
            g_bcc := 'xinwei.wen@nist.gov';
            g_msg :=
                   g_header
                || 'MML Systems Supports:<br><br>'
                || REPLACE (s_msg_check_invalid_bch, '$1', l_msg)
                || g_footer;

            IF NOT is_prod
            THEN
                g_to := 'xinweiw@nist.gov';
                g_subject :=
                       '(Sent from '
                    || g_sid
                    || ') '
                    || s_subject_check_invalid_bch;
            END IF;

            send_email;
        END;
    EXCEPTION
        WHEN OTHERS
        THEN
            g_errcode := SQLCODE;
            g_errmsg := SUBSTR (SQLERRM, 1, 2000);

            INSERT INTO db_error (source,
                                  user_id,
                                  code,
                                  MESSAGE)
                 VALUES ('CHECK_REQUEST_FOR_INVALID_BCH',
                         l_request_id,
                         g_errcode,
                         g_errmsg);

            DBMS_OUTPUT.put_line (
                   g_errcode
                || ' - '
                || 'CHECK_REQUEST_FOR_INVALID_BCH, request id = '
                || l_request_id
                || ', '
                || g_errmsg);
    END;
END EMAIL_PKG;
/
