CREATE TABLE BCPMS_OWNER.ROUTE
(
  ROUTE_ID         INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 36858 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  REQUEST_ID       INTEGER                      NOT NULL,
  ROUTE_TYPE_ID    INTEGER                      NOT NULL,
  ROUTE_NOTES      NVARCHAR2(1000),
  ROUTE_BY         INTEGER,
  ROUTE_DATE       DATE,
  ROUTE_STATUS_ID  INTEGER,
  ROUTE_TO         INTEGER,
  REROUTE_BY       INTEGER
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX BCPMS_OWNER.IX_REQUEST_APPROVAL ON BCPMS_OWNER.ROUTE
(REQUEST_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IX_ROUTE_BY ON BCPMS_OWNER.ROUTE
(ROUTE_BY)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IX_ROUTE_DATE ON BCPMS_OWNER.ROUTE
(ROUTE_DATE)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX BCPMS_OWNER.IX_ROUTE_ID ON BCPMS_OWNER.ROUTE
(ROUTE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IX_ROUTE_STATUS_ID ON BCPMS_OWNER.ROUTE
(ROUTE_STATUS_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IX_ROUTE_TO ON BCPMS_OWNER.ROUTE
(ROUTE_TO)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IX_ROUTE_TYPE_ID ON BCPMS_OWNER.ROUTE
(ROUTE_TYPE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );



CREATE OR REPLACE SYNONYM BCPMS_APP.ROUTE FOR BCPMS_OWNER.ROUTE;


ALTER TABLE BCPMS_OWNER.ROUTE ADD (
  CONSTRAINT KEY5
  PRIMARY KEY
  (ROUTE_ID)
  USING INDEX BCPMS_OWNER.IX_ROUTE_ID
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.ROUTE BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.ROUTE BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.ROUTE TO BCPMS_APP;