CREATE TABLE BCPMS_OWNER.REQUISITION_NUMBER
(
  DIVISION_CODE  CHAR(3 BYTE),
  NEXT_NUMBER    INTEGER
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index BCPMS_OWNER.SYS_C0039051.
--  The object is created when the parent object is created.

CREATE OR REPLACE SYNONYM BCPMS_APP.REQUISITION_NUMBER FOR BCPMS_OWNER.REQUISITION_NUMBER;


ALTER TABLE BCPMS_OWNER.REQUISITION_NUMBER ADD (
  PRIMARY KEY
  (DIVISION_CODE)
  USING INDEX
    TABLESPACE BCPMS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.REQUISITION_NUMBER BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.REQUISITION_NUMBER BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.REQUISITION_NUMBER TO BCPMS_APP;