CREATE TABLE BCPMS_OWNER.FILE_ATTACHMENT
(
  CREATED_DATE      DATE                        DEFAULT sysdate               NOT NULL,
  FILE_ID           INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 6052 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  REQUEST_ID        INTEGER,
  FILE_CATEGORY_ID  INTEGER,
  FILE_NAME         NVARCHAR2(100),
  FILE_TYPE_CODE    VARCHAR2(100 BYTE),
  FILE_SIZE         INTEGER,
  FILE_LOCATION     BFILE,
  FILE_CONTENT      BLOB,
  CREATED_BY        INTEGER                     NOT NULL,
  FILE_DESCRIPTION  VARCHAR2(100 BYTE)
)
LOB (FILE_CONTENT) STORE AS SECUREFILE (
  TABLESPACE  BCPMS_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN BCPMS_OWNER.FILE_ATTACHMENT.FILE_LOCATION IS 'http://www.databasejournal.com/features/oracle/article.php/3305771/Storing-Word-Documents-in-Oracle.htm';


CREATE UNIQUE INDEX BCPMS_OWNER.KEY4 ON BCPMS_OWNER.FILE_ATTACHMENT
(FILE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.FILE_ATTACHMENT FOR BCPMS_OWNER.FILE_ATTACHMENT;


ALTER TABLE BCPMS_OWNER.FILE_ATTACHMENT ADD (
  CONSTRAINT FILE_ATTACHMENT_PK
  PRIMARY KEY
  (FILE_ID)
  USING INDEX BCPMS_OWNER.KEY4
  ENABLE VALIDATE);

ALTER TABLE BCPMS_OWNER.FILE_ATTACHMENT ADD (
  CONSTRAINT REQUEST_FILE_R01 
  FOREIGN KEY (REQUEST_ID) 
  REFERENCES BCPMS_OWNER.REQUEST (REQUEST_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.FILE_ATTACHMENT BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.FILE_ATTACHMENT BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.FILE_ATTACHMENT TO BCPMS_APP;