CREATE TABLE BCPMS_OWNER.LKUP_FILE_CATEGORY
(
  FILE_CATEGORY_ID    INTEGER,
  FILE_CATEGORY_NAME  NVARCHAR2(100)
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE SYNONYM BCPMS_APP.LKUP_FILE_CATEGORY FOR BCPMS_OWNER.LKUP_FILE_CATEGORY;


AUDIT RENAME ON BCPMS_OWNER.LKUP_FILE_CATEGORY BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.LKUP_FILE_CATEGORY BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.LKUP_FILE_CATEGORY TO BCPMS_APP;