CREATE TABLE BCPMS_OWNER.REQUEST
(
  REQUEST_ID                      INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 22331 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  NOTES                           VARCHAR2(500 BYTE),
  REQUESTER_ID                    INTEGER       NOT NULL,
  CREATED_BY                      INTEGER       NOT NULL,
  CREATED_FOR                     INTEGER,
  CREATED_DATE                    DATE          DEFAULT sysdate               NOT NULL,
  IS_SHOPPING_CART                CHAR(1 BYTE)  DEFAULT 'N'                   NOT NULL,
  REFERENCE_ID                    INTEGER,
  UPDATED_BY                      INTEGER       NOT NULL,
  UPDATED_DATE                    DATE          DEFAULT sysdate               NOT NULL,
  DELIVER_ADDRESS                 NVARCHAR2(200),
  REQUISITION_NUMBER              CHAR(30 BYTE),
  NEEDED_BY_DATE                  DATE,
  REVIEWER_ID                     INTEGER,
  BANKCARD_APPROVING_OFFICIAL_ID  INTEGER,
  BANKCARD_HOLDER_ID              INTEGER,
  ESTIMATED_TIME_OF_ARRIVAL       DATE,
  ORDER_NUMBER                    VARCHAR2(100 BYTE),
  GSA_SESSION_NUMBER              VARCHAR2(200 BYTE),
  PURCHASE_ORDER_NUMBER           VARCHAR2(100 BYTE),
  SUBMITTED_DATE                  DATE,
  BCH_COMMENTS                    VARCHAR2(2000 BYTE),
  APPROVAL_AMOUNT                 NUMBER(10,2),
  FY                              INTEGER       DEFAULT substr(extract(year from add_months (SYSDATE, + 3)), 3),
  DELIVER_TO_HOME                 VARCHAR2(1 BYTE) DEFAULT 'N'
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;



CREATE INDEX BCPMS_OWNER.IDX_CREATED_BY ON BCPMS_OWNER.REQUEST
(CREATED_BY)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX BCPMS_OWNER.IDX_CREATED_FOR ON BCPMS_OWNER.REQUEST
(CREATED_FOR)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX BCPMS_OWNER.IDX_REQUEST_ID ON BCPMS_OWNER.REQUEST
(REQUESTER_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX BCPMS_OWNER.IDX_UPDATED_BY ON BCPMS_OWNER.REQUEST
(UPDATED_BY)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX BCPMS_OWNER.KEY1 ON BCPMS_OWNER.REQUEST
(REQUEST_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.REQUEST FOR BCPMS_OWNER.REQUEST;


ALTER TABLE BCPMS_OWNER.REQUEST ADD (
  CONSTRAINT KEY1
  PRIMARY KEY
  (REQUEST_ID)
  USING INDEX BCPMS_OWNER.KEY1
  ENABLE VALIDATE);

ALTER TABLE BCPMS_OWNER.REQUEST ADD (
  CONSTRAINT REQUEST_VENDOR_R01 
  FOREIGN KEY (REQUEST_ID) 
  REFERENCES BCPMS_OWNER.REQUEST (REQUEST_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.REQUEST BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.REQUEST BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.REQUEST TO BCPMS_APP;