CREATE TABLE BCPMS_OWNER.LKUP_ITEM_STATUS_TYPE
(
  ITEM_STATUS_TYPE_ID    INTEGER,
  ITEM_STATUS_TYPE_NAME  NVARCHAR2(100)
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index BCPMS_OWNER.SYS_C0039045.
--  The object is created when the parent object is created.

CREATE OR REPLACE SYNONYM BCPMS_APP.LKUP_ITEM_STATUS_TYPE FOR BCPMS_OWNER.LKUP_ITEM_STATUS_TYPE;


ALTER TABLE BCPMS_OWNER.LKUP_ITEM_STATUS_TYPE ADD (
  PRIMARY KEY
  (ITEM_STATUS_TYPE_ID)
  USING INDEX
    TABLESPACE BCPMS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.LKUP_ITEM_STATUS_TYPE BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.LKUP_ITEM_STATUS_TYPE BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.LKUP_ITEM_STATUS_TYPE TO BCPMS_APP;