CREATE TABLE BCPMS_OWNER.REQUEST_VENDOR
(
  REQUEST_ID                INTEGER,
  VENDOR_ID                 INTEGER,
  CONVENIENCE_CHECK         CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  CONVENIENCE_CHECK_JUST    NVARCHAR2(1000),
  GSA_SCHEDULE              CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  GSA_SCHEDULE_JUST         NVARCHAR2(1000),
  THIRD_PARTY_VENDOR        CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  THIRD_PARTY_VENDOR_JUST   NVARCHAR2(1000),
  PRICE_IS_REASONABLE_JUST  NVARCHAR2(1000),
  SMALL_BUSINESS            CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  SMALL_BUSINESS_JUST       NVARCHAR2(1000),
  CREATED_BY                INTEGER             NOT NULL,
  CREATED_DATE              DATE                DEFAULT sysdate               NOT NULL,
  UPDATED_BY                INTEGER             NOT NULL,
  UPDATED_DATE              DATE                DEFAULT sysdate               NOT NULL,
  CONVENIENCE_CHECK_NUMBER  NVARCHAR2(50),
  DIVISION_ORG_ID           INTEGER,
  PROFESSIONAL_ORG          CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.KEY_REQUEST_VENDOR ON BCPMS_OWNER.REQUEST_VENDOR
(REQUEST_ID, VENDOR_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.REQUEST_VENDOR FOR BCPMS_OWNER.REQUEST_VENDOR;


ALTER TABLE BCPMS_OWNER.REQUEST_VENDOR ADD (
  CONSTRAINT REQUEST_VENDOR_PK
  PRIMARY KEY
  (REQUEST_ID, VENDOR_ID)
  USING INDEX BCPMS_OWNER.KEY_REQUEST_VENDOR
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.REQUEST_VENDOR BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.REQUEST_VENDOR BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.REQUEST_VENDOR TO BCPMS_APP;