CREATE TABLE BCPMS_OWNER.DB_ERROR
(
  DB_ERROR_ID  INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 1183 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  SOURCE       VARCHAR2(100 BYTE)               NOT NULL,
  USER_ID      INTEGER,
  CODE         VARCHAR2(20 BYTE),
  MESSAGE      VARCHAR2(2000 BYTE),
  ERROR_DATE   TIMESTAMP(6)                     DEFAULT sysdate
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.DB_ERROR_PK ON BCPMS_OWNER.DB_ERROR
(DB_ERROR_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.DB_ERROR FOR BCPMS_OWNER.DB_ERROR;


ALTER TABLE BCPMS_OWNER.DB_ERROR ADD (
  CONSTRAINT DB_ERROR_PK
  PRIMARY KEY
  (DB_ERROR_ID)
  USING INDEX BCPMS_OWNER.DB_ERROR_PK
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.DB_ERROR BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.DB_ERROR BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.DB_ERROR TO BCPMS_APP;