CREATE TABLE BCPMS_OWNER.APP_SETTINGS
(
  APP_ENV           VARCHAR2(10 BYTE),
  APP_URL           VARCHAR2(100 BYTE),
  NOTIFICATION_BCC  VARCHAR2(200 BYTE)
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


AUDIT RENAME ON BCPMS_OWNER.APP_SETTINGS BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.APP_SETTINGS BY ACCESS WHENEVER NOT SUCCESSFUL;