ALTER TABLE BCPMS_OWNER.NIST_USER_ACTIVE
 DROP PRIMARY KEY CASCADE;

DROP TABLE BCPMS_OWNER.NIST_USER_ACTIVE CASCADE CONSTRAINTS;

CREATE TABLE BCPMS_OWNER.NIST_USER_ACTIVE
(
  PEOPLE_ID             NUMBER                  NOT NULL,
  FIRST_NAME            VARCHAR2(60 BYTE)       NOT NULL,
  LAST_NAME             VARCHAR2(60 BYTE)       NOT NULL,
  MID_NAME              VARCHAR2(100 BYTE)      NOT NULL,
  OU_ORG_ID             NUMBER(6)               NOT NULL,
  DIV_ORG_ID            NUMBER(6)               NOT NULL,
  GRP_ORG_ID            NUMBER                  NOT NULL,
  USERNAME              VARCHAR2(100 BYTE)      NOT NULL,
  EMAIL                 VARCHAR2(100 BYTE)      ,
  PHONE                 VARCHAR2(20 BYTE),
  SUPERVISOR_YN         VARCHAR2(1 BYTE)        NOT NULL,
  LAST_UPDATE_DT        DATE                    NOT NULL,
  IS_DIVISION_CHIEF     CHAR(1 BYTE),
  IS_AO                 CHAR(1 BYTE),
  IS_AA                 CHAR(1 BYTE),
  IS_GROUP_LEADER       CHAR(1 BYTE),
  IS_SECRETARY          CHAR(1 BYTE),
  STAFF_TYPE            VARCHAR2(50 BYTE)       NOT NULL,
  SUPERVISOR_PEOPLE_ID  NUMBER
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.ALL_USER_PK ON BCPMS_OWNER.NIST_USER_ACTIVE
(PEOPLE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_DIV_ID ON BCPMS_OWNER.NIST_USER_ACTIVE
(DIV_ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_FNAME ON BCPMS_OWNER.NIST_USER_ACTIVE
(FIRST_NAME)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_GRP_ID ON BCPMS_OWNER.NIST_USER_ACTIVE
(GRP_ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_IS_SUPERVISOR ON BCPMS_OWNER.NIST_USER_ACTIVE
(SUPERVISOR_YN)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_LNAME ON BCPMS_OWNER.NIST_USER_ACTIVE
(LAST_NAME)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_OU_ID ON BCPMS_OWNER.NIST_USER_ACTIVE
(OU_ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_STAFF_TYPE ON BCPMS_OWNER.NIST_USER_ACTIVE
(STAFF_TYPE)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_SUPERVISOR_PID ON BCPMS_OWNER.NIST_USER_ACTIVE
(SUPERVISOR_PEOPLE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_AU_UNAME ON BCPMS_OWNER.NIST_USER_ACTIVE
(USERNAME)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE BCPMS_OWNER.NIST_USER_ACTIVE ADD (
  CONSTRAINT ALL_USER_PK
  PRIMARY KEY
  (PEOPLE_ID)
  USING INDEX BCPMS_OWNER.ALL_USER_PK
  ENABLE VALIDATE);

GRANT SELECT ON BCPMS_OWNER.NIST_USER_ACTIVE TO ADMIN_PORTAL_OWNER;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.NIST_USER_ACTIVE TO BCPMS_APP;

CREATE OR REPLACE SYNONYM BCPMS_APP.NIST_USER_ACTIVE FOR BCPMS_OWNER.NIST_USER_ACTIVE;
