CREATE TABLE BCPMS_OWNER.ITEM_STATUS
(
  ITEM_STATUS_ID       INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 13297 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  ITEM_ID              INTEGER,
  ITEM_STATUS_TYPE_ID  INTEGER                  NOT NULL,
  ITEM_STATUS_NOTES    NVARCHAR2(200),
  CREATED_BY           INTEGER                  NOT NULL,
  CREATED_DATE         DATE                     DEFAULT sysdate               NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.KEY6 ON BCPMS_OWNER.ITEM_STATUS
(ITEM_STATUS_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.ITEM_STATUS FOR BCPMS_OWNER.ITEM_STATUS;


ALTER TABLE BCPMS_OWNER.ITEM_STATUS ADD (
  CONSTRAINT ITEM_STATUS_PK
  PRIMARY KEY
  (ITEM_STATUS_ID)
  USING INDEX BCPMS_OWNER.KEY6
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.ITEM_STATUS BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.ITEM_STATUS BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.ITEM_STATUS TO BCPMS_APP;