CREATE TABLE BCPMS_OWNER.PROJECT_TASK
(
  PROJECT_CODE   VARCHAR2(21 BYTE),
  FUND_CODE      VARCHAR2(16 BYTE),
  P_ORG1_CODE    VARCHAR2(6 BYTE),
  P_ORG2_CODE    VARCHAR2(6 BYTE),
  P_ORG3_CODE    VARCHAR2(12 BYTE),
  P_ORG4_CODE    VARCHAR2(8 BYTE),
  P_ORG5_CODE    VARCHAR2(8 BYTE),
  P_ORG6_CODE    VARCHAR2(8 BYTE),
  P_ORG7_CODE    VARCHAR2(8 BYTE),
  PROJECT_DESCR  VARCHAR2(120 BYTE),
  PROJECT_TYPE   VARCHAR2(18 BYTE),
  TASK_CODE      VARCHAR2(9 BYTE),
  TASK_DESCR     VARCHAR2(120 BYTE),
  BEGIN_DATE     DATE
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BCPMS_OWNER.IDX_PJTSK_BDATE ON BCPMS_OWNER.PROJECT_TASK
(BEGIN_DATE)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

AUDIT RENAME ON BCPMS_OWNER.PROJECT_TASK BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.PROJECT_TASK BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT SELECT ON BCPMS_OWNER.PROJECT_TASK TO BCPMS_APP;