CREATE TABLE REVIEWER
(
  PEOPLE_ID             NUMBER                  NOT NULL,
  FIRST_NAME            VARCHAR2(60 BYTE)       NOT NULL,
  LAST_NAME             VARCHAR2(60 BYTE)       NOT NULL,
  MID_NAME              VARCHAR2(100 BYTE)      NOT NULL,
  OU_ORG_ID             NUMBER(6)               NOT NULL,
  DIV_ORG_ID            NUMBER(6)               NOT NULL,
  GRP_ORG_ID            NUMBER                  NOT NULL,
  USERNAME              VARCHAR2(100 BYTE)      NOT NULL,
  EMAIL                 VARCHAR2(100 BYTE)      NOT NULL,
  PHONE                 VARCHAR2(20 BYTE),
  SUPERVISOR_YN         VARCHAR2(1 BYTE)        NOT NULL,
  LAST_UPDATE_DT        DATE                    NOT NULL,
  IS_DIVISION_CHIEF     CHAR(1 BYTE),
  IS_AO                 CHAR(1 BYTE),
  IS_AA                 CHAR(1 BYTE),
  IS_GROUP_LEADER       CHAR(1 BYTE),
  IS_SECRETARY          CHAR(1 BYTE),
  STAFF_TYPE            VARCHAR2(50 BYTE)       NOT NULL,
  SUPERVISOR_PEOPLE_ID  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX REVIEWER_PK ON REVIEWER
(PEOPLE_ID)
LOGGING
NOPARALLEL;


ALTER TABLE REVIEWER ADD (
  CONSTRAINT REVIEWER_PK
  PRIMARY KEY
  (PEOPLE_ID)
  USING INDEX REVIEWER_PK
  ENABLE VALIDATE);
  
  GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.REVIEWER TO BCPMS_APP;
  
  CREATE OR REPLACE SYNONYM BCPMS_APP.REVIEWER FOR BCPMS_OWNER.REVIEWER;