CREATE TABLE BCPMS_OWNER.ROUTE_PULLBACK_LOG
(
  ROUTE_ID         INTEGER                      NOT NULL,
  REQUEST_ID       INTEGER                      NOT NULL,
  ROUTE_TYPE_ID    INTEGER                      NOT NULL,
  ROUTE_NOTES      NVARCHAR2(1000),
  ROUTE_BY         INTEGER,
  ROUTE_DATE       DATE,
  ROUTE_STATUS_ID  INTEGER,
  ROUTE_TO         INTEGER,
  PULLBACK_BY      INTEGER,
  PULLBACK_DATE    DATE                         DEFAULT sysdate
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE SYNONYM BCPMS_APP.ROUTE_PULLBACK_LOG FOR BCPMS_OWNER.ROUTE_PULLBACK_LOG;


AUDIT RENAME ON BCPMS_OWNER.ROUTE_PULLBACK_LOG BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.ROUTE_PULLBACK_LOG BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT INSERT, SELECT ON BCPMS_OWNER.ROUTE_PULLBACK_LOG TO BCPMS_APP;