CREATE TABLE BCPMS_OWNER.ROUTE_ERROR_LOG
(
  ERROR_LOG_ID   INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  ERROR_TYPE_ID  INTEGER,
  ROUTE_ID       INTEGER
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index BCPMS_OWNER.SYS_C0039054.
--  The object is created when the parent object is created.

CREATE OR REPLACE SYNONYM BCPMS_APP.ROUTE_ERROR_LOG FOR BCPMS_OWNER.ROUTE_ERROR_LOG;


ALTER TABLE BCPMS_OWNER.ROUTE_ERROR_LOG ADD (
  PRIMARY KEY
  (ERROR_LOG_ID)
  USING INDEX
    TABLESPACE BCPMS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.ROUTE_ERROR_LOG BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.ROUTE_ERROR_LOG BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.ROUTE_ERROR_LOG TO BCPMS_APP;