CREATE TABLE BCPMS_OWNER.LKUP_ERROR_TYPE
(
  ERROR_TYPE_ID           INTEGER               NOT NULL,
  ERROR_TYPE_DESCRIPTION  NVARCHAR2(100)        NOT NULL,
  ERROR_TYPE_CATEGORY     NVARCHAR2(100)        NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.LKUP_ERROR_TYPE_PK ON BCPMS_OWNER.LKUP_ERROR_TYPE
(ERROR_TYPE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.LKUP_ERROR_TYPE FOR BCPMS_OWNER.LKUP_ERROR_TYPE;


ALTER TABLE BCPMS_OWNER.LKUP_ERROR_TYPE ADD (
  CONSTRAINT LKUP_ERROR_TYPE_PK
  PRIMARY KEY
  (ERROR_TYPE_ID)
  USING INDEX BCPMS_OWNER.LKUP_ERROR_TYPE_PK
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.LKUP_ERROR_TYPE BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.LKUP_ERROR_TYPE BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.LKUP_ERROR_TYPE TO BCPMS_APP;