CREATE TABLE BCPMS_OWNER.OBJECT_CLASS
(
  CODE               VARCHAR2(35 BYTE),
  DESCRIPTION        VARCHAR2(120 BYTE),
  OMB_OBJECT_CLASS   NUMBER(3,1),
  CF_CATEGORY        NUMBER(3,1),
  GOVERNMENTAL_FLAG  VARCHAR2(3 BYTE),
  ACTIVE_STATUS      VARCHAR2(3 BYTE),
  STATUS_DATE        DATE,
  USER_NAME          VARCHAR2(90 BYTE),
  MODIFICATION_DATE  DATE,
  DEVICE_NAME        VARCHAR2(90 BYTE)
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BCPMS_OWNER.IDX_OJC_ACTIVE_YN ON BCPMS_OWNER.OBJECT_CLASS
(ACTIVE_STATUS)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

AUDIT RENAME ON BCPMS_OWNER.OBJECT_CLASS BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.OBJECT_CLASS BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT SELECT ON BCPMS_OWNER.OBJECT_CLASS TO BCPMS_APP;