CREATE TABLE BCPMS_OWNER.USER_SESSION
(
  TOKEN        NVARCHAR2(50)                    NOT NULL,
  PEOPLE_ID    INTEGER,
  ACCESS_TIME  TIMESTAMP(6)
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.USER_SESSION_PK ON BCPMS_OWNER.USER_SESSION
(TOKEN)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.USER_SESSION FOR BCPMS_OWNER.USER_SESSION;


ALTER TABLE BCPMS_OWNER.USER_SESSION ADD (
  CONSTRAINT USER_SESSION_PK
  PRIMARY KEY
  (TOKEN)
  USING INDEX BCPMS_OWNER.USER_SESSION_PK
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.USER_SESSION BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.USER_SESSION BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.USER_SESSION TO BCPMS_APP;