ALTER TABLE BCPMS_OWNER.NIST_USER
 DROP PRIMARY KEY CASCADE;

DROP TABLE BCPMS_OWNER.NIST_USER CASCADE CONSTRAINTS;

CREATE TABLE BCPMS_OWNER.NIST_USER
(
  PEOPLE_ID             NUMBER                  NOT NULL,
  FIRST_NAME            VARCHAR2(60 BYTE)       NOT NULL,
  LAST_NAME             VARCHAR2(60 BYTE)       NOT NULL,
  MID_NAME              VARCHAR2(100 BYTE)      NOT NULL,
  OU_ORG_ID             NUMBER(6)               NOT NULL,
  DIV_ORG_ID            NUMBER(6)               NOT NULL,
  GRP_ORG_ID            NUMBER                  NOT NULL,
  USERNAME              VARCHAR2(100 BYTE)      NOT NULL,
  EMAIL                 VARCHAR2(100 BYTE)      ,
  PHONE                 VARCHAR2(20 BYTE),
  SUPERVISOR_YN         VARCHAR2(1 BYTE)        NOT NULL,
  LAST_UPDATE_DT        DATE                    NOT NULL,
  IS_DIVISION_CHIEF     CHAR(1 BYTE),
  IS_AO                 CHAR(1 BYTE),
  IS_AA                 CHAR(1 BYTE),
  IS_GROUP_LEADER       CHAR(1 BYTE),
  IS_SECRETARY          CHAR(1 BYTE),
  STAFF_TYPE            VARCHAR2(50 BYTE)       NOT NULL,
  SUPERVISOR_PEOPLE_ID  NUMBER,
  ACTIVE_YN             CHAR(1 BYTE)            NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX BCPMS_OWNER.IDX_DIV_ID ON BCPMS_OWNER.NIST_USER
(DIV_ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_FNAME ON BCPMS_OWNER.NIST_USER
(FIRST_NAME)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_GRP_ID ON BCPMS_OWNER.NIST_USER
(GRP_ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_IS_SUPERVISOR ON BCPMS_OWNER.NIST_USER
(SUPERVISOR_YN)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_LNAME ON BCPMS_OWNER.NIST_USER
(LAST_NAME)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_OU_ID ON BCPMS_OWNER.NIST_USER
(OU_ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_STAFF_TYPE ON BCPMS_OWNER.NIST_USER
(STAFF_TYPE)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_SUPERVISOR_PID ON BCPMS_OWNER.NIST_USER
(SUPERVISOR_PEOPLE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX BCPMS_OWNER.IDX_UNAME ON BCPMS_OWNER.NIST_USER
(USERNAME)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX BCPMS_OWNER.NIST_USER_PK ON BCPMS_OWNER.NIST_USER
(PEOPLE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE SYNONYM BCPMS_APP.NIST_USER FOR BCPMS_OWNER.NIST_USER;


ALTER TABLE BCPMS_OWNER.NIST_USER ADD (
  CONSTRAINT NIST_USER_PK
  PRIMARY KEY
  (PEOPLE_ID)
  USING INDEX BCPMS_OWNER.NIST_USER_PK
  ENABLE VALIDATE);

GRANT SELECT ON BCPMS_OWNER.NIST_USER TO ADMIN_PORTAL_OWNER;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.NIST_USER TO BCPMS_APP;
