CREATE TABLE BCPMS_OWNER.ITEM
(
  REQUEST_ID             INTEGER                NOT NULL,
  ITEM_TYPE              CHAR(1 BYTE)           DEFAULT 'R'                   NOT NULL,
  VENDOR_ID              INTEGER,
  CATELOG_NUMBER         NVARCHAR2(50),
  ITEM_NAME              NVARCHAR2(200)         NOT NULL,
  ITEM_DESCRIPTION       NVARCHAR2(500),
  PRICE                  NUMBER(10,2)           DEFAULT 0.00,
  QUANTITY               INTEGER                DEFAULT 0,
  PURPOSE                NVARCHAR2(200),
  CHEMICAL               CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  PROJECT_TASK           NVARCHAR2(200),
  SHOPPING_CART_FILE_ID  INTEGER,
  ITEM_STATUS_ID         INTEGER,
  OBJECT_CLASS           NVARCHAR2(220),
  IS_PRECIOUS_METAL      INTEGER                DEFAULT 0                     NOT NULL,
  IS_SHIPPING            CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  PRICE_ORDERED          NUMBER(10,2)           DEFAULT 0.00,
  QUANTITY_ORDERED       NUMBER(38)             DEFAULT 0,
  ITEM_NOTES             VARCHAR2(500 BYTE),
  DATE_RECEIVED          DATE,
  TRANSACTION_NUMBER     VARCHAR2(100 BYTE),
  STATEMENT_DATE         DATE,
  ITEM_ID                INTEGER                DEFAULT "BCPMS_OWNER"."SEQ_ITEM_ID"."NEXTVAL" NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.ITEM_PK ON BCPMS_OWNER.ITEM
(ITEM_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.ITEM FOR BCPMS_OWNER.ITEM;


ALTER TABLE BCPMS_OWNER.ITEM ADD (
  CONSTRAINT ITEM_OLD_PK
  PRIMARY KEY
  (ITEM_ID)
  USING INDEX BCPMS_OWNER.ITEM_PK
  ENABLE VALIDATE);

ALTER TABLE BCPMS_OWNER.ITEM ADD (
  CONSTRAINT REQUEST_ITEM_R01 
  FOREIGN KEY (REQUEST_ID) 
  REFERENCES BCPMS_OWNER.REQUEST (REQUEST_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.ITEM BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.ITEM BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.ITEM TO BCPMS_APP;