CREATE TABLE BCPMS_OWNER.ROUTE_RULES
(
  ROUTE_STATUS_ID  INTEGER                      NOT NULL,
  REVIEW           INTEGER                      DEFAULT 0                     NOT NULL,
  APPROVAL         INTEGER                      DEFAULT 0                     NOT NULL,
  PROCESS          INTEGER                      DEFAULT 0                     NOT NULL,
  ACCEPT           INTEGER                      DEFAULT 0                     NOT NULL,
  REJECT           INTEGER                      DEFAULT 0                     NOT NULL,
  REROUTE          INTEGER                      DEFAULT 0                     NOT NULL,
  COMPLETE         INTEGER                      DEFAULT 0                     NOT NULL,
  ARCHIVE          INTEGER                      DEFAULT 0                     NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.ROUTE_RULES_PK ON BCPMS_OWNER.ROUTE_RULES
(ROUTE_STATUS_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.ROUTE_RULES FOR BCPMS_OWNER.ROUTE_RULES;


ALTER TABLE BCPMS_OWNER.ROUTE_RULES ADD (
  CONSTRAINT ROUTE_RULES_PK
  PRIMARY KEY
  (ROUTE_STATUS_ID)
  USING INDEX BCPMS_OWNER.ROUTE_RULES_PK
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.ROUTE_RULES BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.ROUTE_RULES BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.ROUTE_RULES TO BCPMS_APP;