CREATE TABLE BCPMS_OWNER.USER_PRIVILEGES
(
  USERNAME      NVARCHAR2(50)                   NOT NULL,
  CHANGE_PTC    VARCHAR2(1 BYTE)                DEFAULT 'N'                   NOT NULL,
  REROUTE       VARCHAR2(1 BYTE)                DEFAULT 'N'                   NOT NULL,
  ACCESS_GROUP  VARCHAR2(1 BYTE)                DEFAULT 'N'                   NOT NULL,
  ACCESS_DIV    VARCHAR2(1 BYTE)                DEFAULT 'N'                   NOT NULL,
  ACCESS_OU     VARCHAR2(1 BYTE)                DEFAULT 'N'                   NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.USER_PRIVILEGES_PK ON BCPMS_OWNER.USER_PRIVILEGES
(USERNAME)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.USER_PRIVILEGES FOR BCPMS_OWNER.USER_PRIVILEGES;


AUDIT RENAME ON BCPMS_OWNER.USER_PRIVILEGES BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.USER_PRIVILEGES BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.USER_PRIVILEGES TO BCPMS_APP;