CREATE TABLE BCPMS_OWNER.NIST_OU
(
  ORG_ID          NUMBER(6)                     NOT NULL,
  ORG_CD          VARCHAR2(20 BYTE)             NOT NULL,
  ORG_NAME        VARCHAR2(200 BYTE)            NOT NULL,
  EFFECTIVE_DT    DATE,
  ORG_ACRNM       VARCHAR2(6 BYTE),
  ACTIVE_YN       CHAR(1 BYTE)                  NOT NULL,
  AD_ORG_ID       NUMBER,
  LAST_UPDATE_DT  DATE                          NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BCPMS_OWNER.IDX_OU_ACTIVE_YN ON BCPMS_OWNER.NIST_OU
(ACTIVE_YN)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX BCPMS_OWNER.IDX_OU_BDATE ON BCPMS_OWNER.NIST_OU
(EFFECTIVE_DT)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX BCPMS_OWNER.NIST_OU_PK ON BCPMS_OWNER.NIST_OU
(ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.NIST_OU FOR BCPMS_OWNER.NIST_OU;


ALTER TABLE BCPMS_OWNER.NIST_OU ADD (
  CONSTRAINT NIST_OU_PK
  PRIMARY KEY
  (ORG_ID)
  USING INDEX BCPMS_OWNER.NIST_OU_PK
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.NIST_OU BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.NIST_OU BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT SELECT ON BCPMS_OWNER.NIST_OU TO BCPMS_APP;