CREATE TABLE BCPMS_OWNER.VENDOR
(
  VENDOR_ID           INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 5746 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  VENDOR_NAME         NVARCHAR2(100)            NOT NULL,
  STREET              NVARCHAR2(200),
  CITY                NVARCHAR2(100),
  STATE               NVARCHAR2(20),
  ZIP                 NVARCHAR2(10),
  WEB_URL             NVARCHAR2(200),
  CONTACT_PERSON      NVARCHAR2(50),
  PHONE               NVARCHAR2(30),
  FAX                 NVARCHAR2(30),
  EMAIL               NVARCHAR2(50),
  ACCOUNT_NUMBER      NVARCHAR2(100),
  CREATED_BY          INTEGER                   NOT NULL,
  CREATED_DATE        DATE                      DEFAULT sysdate               NOT NULL,
  UPDATED_BY          INTEGER                   NOT NULL,
  UPDATED_DATE        DATE                      DEFAULT sysdate               NOT NULL,
  IS_FOREIGN_ADDRESS  CHAR(1 BYTE),
  FOREIGN_ADDRESS     NVARCHAR2(500),
  IS_ACTIVE           INTEGER                   DEFAULT 1                     NOT NULL,
  DUNS_NUMBER         VARCHAR2(50 BYTE),
  IMPORTED_FROM       VARCHAR2(50 BYTE)
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.KEY3 ON BCPMS_OWNER.VENDOR
(VENDOR_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.VENDOR FOR BCPMS_OWNER.VENDOR;


ALTER TABLE BCPMS_OWNER.VENDOR ADD (
  CONSTRAINT KEY3
  PRIMARY KEY
  (VENDOR_ID)
  USING INDEX BCPMS_OWNER.KEY3
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.VENDOR BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.VENDOR BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.VENDOR TO BCPMS_APP;