CREATE TABLE BCPMS_OWNER.ITEM_CHEMICAL
(
  ITEM_ID                     INTEGER           NOT NULL,
  OWNER_ID                    INTEGER,
  LOCATION                    VARCHAR2(200 BYTE),
  SUB_LOCATION                NVARCHAR2(200),
  CAS_NUMBER                  NVARCHAR2(200),
  CHEMICAL_FORM               NVARCHAR2(200),
  CHEMICAL_GRADE              NVARCHAR2(200),
  MANUFACTURER_NAME           NVARCHAR2(200),
  CATALOG_NUMBER              NVARCHAR2(200),
  CATALOG_NUMBER_QUANTITY     NVARCHAR2(50),
  CONTAINERS_PER_PACKAGE      NVARCHAR2(50),
  AMOUNT_PER_CONTAINER        NVARCHAR2(50),
  LABLES_NEEDED               INTEGER,
  CONTAINER_TYPE              NVARCHAR2(200),
  EXPIRATION_DATE             DATE,
  HEALTH_NFPA_VALUE           NVARCHAR2(200),
  FLAMMABILITY_NFPA_VALUE     NVARCHAR2(200),
  REACTIVITY_NFPA_VALUE       NVARCHAR2(200),
  SPECIAL_CODE_NFPA_VALUE     VARCHAR2(200 BYTE),
  IS_RADIOACTIVE_MATERIAL     CHAR(1 BYTE),
  BIOHAZARD_REGISTRATION_REQ  CHAR(1 BYTE),
  SPECIAL_INSTRUCTION         NVARCHAR2(500),
  IBBR_ROOM_ID                INTEGER,
  IBBR_ROOM_NAME              VARCHAR2(100 BYTE),
  PRIMARY_USER_ID             INTEGER,
  CISPRO_REMARKS              VARCHAR2(500 BYTE),
  CONTAINER_TOTAL             INTEGER,
  PRODUCT_URL                 VARCHAR2(500 BYTE)
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.KEY12 ON BCPMS_OWNER.ITEM_CHEMICAL
(ITEM_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.ITEM_CHEMICAL FOR BCPMS_OWNER.ITEM_CHEMICAL;


ALTER TABLE BCPMS_OWNER.ITEM_CHEMICAL ADD (
  CONSTRAINT ITEM_CHEMICAL_PK
  PRIMARY KEY
  (ITEM_ID)
  USING INDEX BCPMS_OWNER.KEY12
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.ITEM_CHEMICAL BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.ITEM_CHEMICAL BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.ITEM_CHEMICAL TO BCPMS_APP;