CREATE TABLE BCPMS_OWNER.USER_ROLE
(
  PEOPLE_ID  INTEGER,
  ROLE_ID    INTEGER
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BCPMS_OWNER.PK_ROLE_TYPE ON BCPMS_OWNER.USER_ROLE
(PEOPLE_ID, ROLE_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.USER_ROLE FOR BCPMS_OWNER.USER_ROLE;


ALTER TABLE BCPMS_OWNER.USER_ROLE ADD (
  CONSTRAINT PK_ROLE_TYPE
  PRIMARY KEY
  (PEOPLE_ID, ROLE_ID)
  USING INDEX BCPMS_OWNER.PK_ROLE_TYPE
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.USER_ROLE BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.USER_ROLE BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.USER_ROLE TO BCPMS_APP;