CREATE TABLE BCPMS_OWNER.NIST_GROUP
(
  ORG_ID          NUMBER(6)                     NOT NULL,
  ORG_CD          VARCHAR2(20 BYTE)             NOT NULL,
  ORG_NAME        VARCHAR2(200 BYTE)            NOT NULL,
  EFFECTIVE_DT    DATE,
  ORG_ACRNM       VARCHAR2(6 BYTE),
  OU_ORG_ID       NUMBER(6)                     NOT NULL,
  DIV_ORG_ID      NUMBER(6)                     NOT NULL,
  ACTIVE_YN       CHAR(1 BYTE)                  NOT NULL,
  LAST_UPDATE_DT  DATE                          NOT NULL
)
TABLESPACE BCPMS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX BCPMS_OWNER.IDX_GRP_ACTIVE_YN ON BCPMS_OWNER.NIST_GROUP
(ACTIVE_YN)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX BCPMS_OWNER.IDX_GRP_BDATE ON BCPMS_OWNER.NIST_GROUP
(EFFECTIVE_DT)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX BCPMS_OWNER.IDX_GRP_DIV_ID ON BCPMS_OWNER.NIST_GROUP
(DIV_ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX BCPMS_OWNER.IDX_GRP_OU_ID ON BCPMS_OWNER.NIST_GROUP
(OU_ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX BCPMS_OWNER.IDX_GRP_UPDT_DT ON BCPMS_OWNER.NIST_GROUP
(LAST_UPDATE_DT)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX BCPMS_OWNER.NIST_GROUP_PK ON BCPMS_OWNER.NIST_GROUP
(ORG_ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE SYNONYM BCPMS_APP.NIST_GROUP FOR BCPMS_OWNER.NIST_GROUP;


ALTER TABLE BCPMS_OWNER.NIST_GROUP ADD (
  CONSTRAINT NIST_GROUP_PK
  PRIMARY KEY
  (ORG_ID)
  USING INDEX BCPMS_OWNER.NIST_GROUP_PK
  ENABLE VALIDATE);

AUDIT RENAME ON BCPMS_OWNER.NIST_GROUP BY ACCESS WHENEVER SUCCESSFUL;
AUDIT RENAME ON BCPMS_OWNER.NIST_GROUP BY ACCESS WHENEVER NOT SUCCESSFUL;

GRANT SELECT ON BCPMS_OWNER.NIST_GROUP TO BCPMS_APP;