/* Formatted on 3/5/2025 10:28:36 AM (QP5 v5.396) */
CREATE OR REPLACE FUNCTION BCPMS_OWNER.GET_MISSION_CRITICAL_CATEGORY_NAME (
    p_MISSION_CRITICAL_CATEGORY_ID   IN LKUP_MISSION_CRITICAL_CATEGORY.MISSION_CRITICAL_CATEGORY_ID%TYPE)
    RETURN NVARCHAR2
IS
    l_MISSION_CRITICAL_CATEGORY_NAME   NVARCHAR2 (200) := '';
BEGIN
    SELECT MISSION_CRITICAL_CATEGORY_NAME
      INTO l_MISSION_CRITICAL_CATEGORY_NAME
      FROM LKUP_MISSION_CRITICAL_CATEGORY m
     WHERE m.MISSION_CRITICAL_CATEGORY_ID = p_MISSION_CRITICAL_CATEGORY_ID;

    RETURN l_MISSION_CRITICAL_CATEGORY_NAME;
END;
/
