SET DEFINE OFF;
CREATE TABLE BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY
(
  MISSION_CRITICAL_CATEGORY_ID    INTEGER,
  MISSION_CRITICAL_CATEGORY_NAME  NVARCHAR2(500)
);

CREATE UNIQUE INDEX BCPMS_OWNER.PK_LKUP_MISSION_CRITICAL_CATEGORY ON BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY
(MISSION_CRITICAL_CATEGORY_ID);

ALTER TABLE BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY ADD (
  CONSTRAINT PK_LKUP_MISSION_CRITICAL_CATEGORY
  PRIMARY KEY
  (MISSION_CRITICAL_CATEGORY_ID)
  USING INDEX BCPMS_OWNER.PK_LKUP_MISSION_CRITICAL_CATEGORY
  ENABLE VALIDATE);


Insert into BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY
   (MISSION_CRITICAL_CATEGORY_ID, MISSION_CRITICAL_CATEGORY_NAME)
 Values
   (1, 'Time Critical, Mission critical Research Need');
Insert into BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY
   (MISSION_CRITICAL_CATEGORY_ID, MISSION_CRITICAL_CATEGORY_NAME)
 Values
   (2, 'Life safety');
Insert into BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY
   (MISSION_CRITICAL_CATEGORY_ID, MISSION_CRITICAL_CATEGORY_NAME)
 Values
   (3, 'Physical and IT infrastructure maintenance and repair');
Insert into BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY
   (MISSION_CRITICAL_CATEGORY_ID, MISSION_CRITICAL_CATEGORY_NAME)
 Values
   (4, 'Other');
COMMIT;


GRANT SELECT ON BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY TO ADMIN_PORTAL_OWNER;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY TO BCPMS_APP;

GRANT SELECT ON BCPMS_OWNER.LKUP_MISSION_CRITICAL_CATEGORY TO BCPMS_READ;

