/*
 * File: app/store/DashSettings.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.store.BcpAppVersion', {
    extend: 'Ext.data.Store',

    requires: ['Ext.data.proxy.LocalStorage', 'Ext.data.field.Field'],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'BcpAppVersion',
                    autoLoad: true,
                    autoSync: true,
                    proxy: {type: 'localstorage', id: 'bcpAppVersionLocal'},
                    fields: [
                        {name: 'version'},
                        {name: 'lastUsed', type: 'date'}
                    ]
                },
                cfg
            )
        ]);
    }
});
