/*
 * File: app/store/LkUserRolesNotUsed.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.store.LkUserRolesNotUsed', {
    extend: 'Ext.data.Store',

    requires: [
        'bcp.model.UserRole',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'LkUserRolesNotUsed',
                    autoLoad: true,
                    model: 'bcp.model.UserRole',
                    data: [
                        {id: 1, name: 'Director', category: 'Organizational'},
                        {
                            id: 2,
                            name: 'Deputy Director',
                            category: 'Organizational'
                        },
                        {
                            id: 3,
                            name: 'Administrative Officer',
                            category: 'Administrative'
                        },
                        {
                            id: 4,
                            name: 'Group Office Manager',
                            category: 'Administrative'
                        },
                        {
                            id: 5,
                            name: 'Division Chief',
                            category: 'Organizational'
                        },
                        {
                            id: 7,
                            name: 'Deputy Chief',
                            category: 'Organizational'
                        },
                        {
                            id: 11,
                            name: 'Group Leader',
                            category: 'Organizational'
                        },
                        {
                            id: 13,
                            name: 'Senior Management Advisor',
                            category: 'Administrative'
                        },
                        {
                            id: 19,
                            name: 'Division Office Manager',
                            category: 'Administrative'
                        },
                        {
                            id: 20,
                            name: 'Laboratory Office Manager',
                            category: 'Administrative'
                        },
                        {id: 27, name: 'Update Access', category: 'NIST Org'},
                        {
                            id: 37,
                            name: 'Bankcard Approving Official',
                            category: 'Acquisitions'
                        },
                        {
                            id: 38,
                            name: 'Bankcard Holder',
                            category: 'Acquisitions'
                        },
                        {
                            id: 51,
                            name: 'Administrative Office Assistant',
                            category: 'Administrative'
                        },
                        {id: 52, name: 'CISPro Power User', category: 'Safety'}
                    ],
                    proxy: {type: 'memory', reader: {type: 'json'}}
                },
                cfg
            )
        ]);
    }
});
