/*
 * File: app/store/FileCategories.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.store.MissionCriticalCategories', {
    extend: 'Ext.data.Store',

    requires: [
        'bcp.model.LookUpData',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'MissionCriticalCategories',
                    autoLoad: true,
                    model: 'bcp.model.LookUpData',
                    data: [
                        {id: 1, name: 'Time-critical, mission critical research needs',description:'Critical purchases are required to directly support critical, time-sensitive research. This includes chemicals and cryogens, other consumables required to directly support the related research activities, research equipment, and research equipment construction and maintenance. Without these purchases, mission-critical research would stop. '},
                        {id: 2, name: 'Life safety',description:'Supplies, equipment, and services to support life safety and related regulatory compliance activities. Without these purchases, NIST staff cannot perform their jobs safely.'},
                        {id: 3, name: 'Physical and IT infrastructure maintenance and repair',description:'Infrastructure maintenance and repair: parts, supplies, equipment, and services required to maintain facilities. Without these purchases, mission-critical facilities and IT infrastructure would risk damage or failure.'},
                        {id: 4, name: 'Other'}
                    ],
                    proxy: {type: 'memory', reader: {type: 'json'}}
                },
                cfg
            )
        ]);
    }
});
