/*
 * File: app/store/OuEmployees.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*Ext.define('bcp.store.OuEmployees', {
    extend: 'Ext.data.Store',

    requires: [
        'bcp.model.BcUser',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'OuEmployees',
                    model: 'bcp.model.BcUser',
                    proxy: {
                        type: 'ajax',
                        noCache: false,
                        limitParam: false,
                        pageParam: false,
                        startParam: false,
                        // @sw-cache {handler: "fastest", options: { cache: { name: 'ouEmps', maxAgeSeconds: 86400} } }
                        url: '/empbc/v1/users/nistEmployees',
                        reader: {type: 'json', rootProperty: 'data'}
                    }
                },
                cfg
            )
        ]);
    }
});*/

Ext.define('bcp.store.OuEmployees', {
    extend: 'Ext.data.ChainedStore', // Changed to ChainedStore

    requires: [
        'bcp.model.BcUser',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'OuEmployees',
                    // Removed the model configuration because it will inherit it from the source store.
                    source: 'OuAllStaffs', // Set the source store
                    //add a filter to make this store only show NIST Employees
                    filters: [
                        function(item){
                            return item.get('staffType') === 'NIST Employee';
                        }
                    ]
                },
                cfg
            )
        ]);
    }
});
