/*
 * File: app/store/RequestStatuses.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.store.RequestStatuses', {
    extend: 'Ext.data.Store',

    requires: ['Ext.data.proxy.Memory', 'Ext.data.field.Field'],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'RequestStatuses',
                    autoLoad: true,
                    //route type data
                    data: [
                        {id: 1, text: 'submitted'},
                        {id: 2, text: 'reviewed'},
                        {id: 3, text: 'approved'},
                        {id: 4, text: 'ordered'},
                        {id: 5, text: 'rejected'},
                        {id: 6, text: 'delivered'},
                        {id: 7, text: 'received'},
                        {id: 8, text: 'canceled'},
                        {
                            id: 9,
                            text: 'reassigned' //'rerouted'
                        },
                        {id: 12, text: 'prepared'},
                        {id: 13, text: 'returned'}
                    ],
                    proxy: {type: 'memory'},
                    fields: [{name: 'id'}, {name: 'text'}]
                },
                cfg
            )
        ]);
    }
});
