/*
 * File: app/store/RouteRules.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.store.RouteRules', {
    extend: 'Ext.data.Store',

    requires: [
        'bcp.model.RouteRule',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'RouteRules',
                    autoLoad: true,
                    model: 'bcp.model.RouteRule',
                    data: [
                        {
                            routeStatusId: 1,
                            accept: false,
                            submit: true,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 2,
                            accept: true,
                            submit: false,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: false
                        },
                        {
                            routeStatusId: 3,
                            accept: false,
                            submit: true,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: false
                        },
                        {
                            routeStatusId: 4,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: true
                        },
                        {
                            routeStatusId: 5,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: true
                        },
                        {
                            routeStatusId: 6,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: true,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: true
                        },
                        {
                            routeStatusId: 7,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: true,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: true
                        },
                        {
                            routeStatusId: 8,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: false,
                            complete: true,
                            archive: false,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 9,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: false,
                            complete: false,
                            archive: true,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 10,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 11,
                            accept: false,
                            submit: true,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 12,
                            accept: true,
                            submit: false,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 13,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 14,
                            accept: false,
                            submit: true,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 15,
                            accept: false,
                            submit: true,
                            review: false,
                            approve: false,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: false,
                            reroute: false
                        },
                        {
                            routeStatusId: 16,
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: false
                        },
                        {
                            routeStatusId: 17,//issue 618
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: false
                        },
                        {
                            routeStatusId: 18,//issue 618
                            accept: false,
                            submit: false,
                            review: false,
                            approve: true,
                            process: false,
                            complete: false,
                            archive: false,
                            reject: true,
                            reroute: false
                        },
                    ],
                    proxy: {type: 'memory', reader: {type: 'json'}}
                },
                cfg
            )
        ]);
    }
});
