/*
 * File: app/store/SubViews.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.store.SubViews', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'SubViews',
                    autoLoad: true,
                    data: [
                        {
                            routeId: 'requesttracking',
                            displayText: 'Submitted Requests'
                        },
                        {
                            routeId: 'pendingrequests',
                            displayText: 'Pending Actions'
                        },
                        {
                            routeId: 'savedrequests',
                            displayText: 'Saved Requests'
                        },
                        {
                            routeId: 'preparedrequests',
                            displayText: 'Prepared Requests'
                        },
                        {
                            routeId: 'archivedrequests',
                            displayText: 'Received Requests'
                        }
                    ],
                    proxy: {type: 'memory', reader: {type: 'json'}},
                    fields: [{name: 'routeId'}, {name: 'displayText'}]
                },
                cfg
            )
        ]);
    }
});
