/*
 * File: app/store/ThirdPartyJustifications.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.store.ThirdPartyJustifications', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([
            Ext.apply(
                {
                    storeId: 'ThirdPartyJustifications',
                    data: [
                        {
                            text: 'There is no other vendor that can supply the product/service or meet the delivery, quantity or quality requirements than this Vendor, and this Vendor only accepts payment through the third-party processor.'
                        },
                        {text: 'Other'}
                    ],
                    proxy: {type: 'memory', reader: {type: 'json'}},
                    fields: [{name: 'text'}]
                },
                cfg
            )
        ]);
    }
});
