Insert into BCPMS_OWNER.LKUP_ROUTE_STATUS (ROUTE_STATUS_ID,ROUTE_STATUS_NAME) values (14,'The request is returned to the requester for additional info or modification');

Insert into BCPMS_OWNER.LKUP_ROUTE_TYPE (ROUTE_TYPE_ID,ROUTE_TYPE_NAME) values (13,'returned');

create or replace TRIGGER bcpms_owner.email_notice AFTER
    INSERT ON bcpms_owner.route
    REFERENCING
            NEW AS new
            OLD AS old
    FOR EACH ROW
DECLARE
    /*
    declare
    l_server environment.server_name%type; l_url environment.web_url%type; l_dtap environment.dtap%type;
    begin
    select server_name, web_url, dtap into l_server, l_url, l_dtap
    from environment
    where server_name = (select global_name FROM global_name);
    dbms_output.put_line(l_server || ', ' || l_url || ', ' || l_dtap);
    end;
    */


    l_app_url              VARCHAR2(200) := '';
    l_app_env              VARCHAR2(200) := '';
    l_app_bcc              VARCHAR2(200) := NULL;
    l_request_id           request.request_id%TYPE := :new.request_id;
    l_sender               NVARCHAR2(60) := get_user_name(:new.route_by);
    l_sender_email         NVARCHAR2(60) := get_user_email(:new.route_by);
    l_receip               NVARCHAR2(60) := get_user_name(:new.route_to);
    l_receip_email         NVARCHAR2(200) := get_user_email(:new.route_to);
    l_subject              NVARCHAR2(200) := 'The Bankcard Purchase Request '
                                || l_request_id
                                || ' (Req # '
                                || trim(get_req_num(l_request_id))
                                || ') ';
    l_cc_email             VARCHAR2(250) := '';
    --l_test_receip_email nvarchar2(200) := 'youchun.yao@nist.gov';
    --l_test_receip_email      NVARCHAR2 (200) := 'xinweiw@nist.gov';
    --l_test_cc_email          NVARCHAR2 (200):= 'jason.poffenberger@nist.gov;youchun.yao@nist.gov';
    --l_rc varchar2(1);
    l_body                 VARCHAR2(1000) := '';
    l_route_type_id        route.route_type_id%TYPE := :new.route_type_id;
    l_route_status_id      route.route_status_id%TYPE := :new.route_status_id;
    l_route_type_name      VARCHAR2(50) := '';
    l_link                 NVARCHAR2(300) := '';
    l_purchase_link        NVARCHAR2(300) := '';
    l_received_link        NVARCHAR2(300) := '';
    l_reject_link          NVARCHAR2(300) := '';
    l_reject_prepared_link NVARCHAR2(300) := '';
    l_always_valid_link    NVARCHAR2(300) := '';
    l_request_creator      request.created_by%TYPE := 0;
    l_route_to             route.route_to%TYPE := :new.route_to;
    l_foot                 NVARCHAR2(250) := '<br><br>This message is auto generated by the MML Bankcard Request and Approval system. Please do not reply to this email.';
    l_requisition_number   request.requisition_number%TYPE;
    l_created_for_id       request.created_for%TYPE;
    l_supervisor_email     nist_user.email%TYPE := '';
    l_item_name            item.item_name%TYPE;
    l_item_list            NVARCHAR2(2500) := '';
    v_error_code           NVARCHAR2(30);
    v_error_message        NVARCHAR2(2000);

    --MB-382
    l_body2                VARCHAR2(1000) := '';
    l_sender2              NVARCHAR2(60) := '';
    l_sender2_email        NVARCHAR2(60) := '';
    l_receip2              NVARCHAR2(60) := '';
    l_receip2_email        NVARCHAR2(200) := '';
    l_send_req_to_bch      BOOLEAN := false;
    l_req_cnt              NUMBER(2) := 0;
    l_requester_id         NUMBER := 0;
    l_deliv_to_home        NVARCHAR2(1) := 'N';




    -- 2017-09-06 yy: remove.
    --for chemical and preciousmetal notivications
    --l_is_chemical ITEM.CHEMICAL%TYPE;
    --l_is_precious_metal item.is_precious_metal%TYPE;
    -- 2018-01-18 yy: removed test receip email and test title
    --2018-01-25 xw: rejected request should have use #requesttracking, not #pendingrequests

    -- 2017-10-30 yy: for cancel request
    CURSOR l_item_cur IS
    SELECT
        item_name
    FROM
        item
    WHERE
        request_id = l_request_id;

BEGIN
    --the purpose of email notification is to defeated if we cannot find the recipient's email
    IF l_receip_email IS NULL OR length(l_receip_email) = 0 THEN
        raise_application_error(-20101, 'Error from email_notice trigger. Email recipient is missing.');
    END IF;


    --select environment variables used for email in DEV, Test or Prod
    SELECT
        app_env,
        app_url,
        notification_bcc
    INTO
        l_app_env,
        l_app_url,
        l_app_bcc
    FROM
        app_settings;

    --use environment variables to form links in email
    l_link := ' Please click this link if you need the details of this order: '
              || l_app_url
              || '#pendingrequests/'
              || :new.request_id
              || '.';
        --|| ' to see the detail.';
    --2018-01-25 xw: rejected request should have use #requesttracking, not #pendingrequests
    --2018-01-25 xw: rejected request from requester to creator should use #preparedrequests
    l_reject_link := ' Please click this link: '
                     || l_app_url
                     || '#requesttracking/'
                     || :new.request_id
                     || ' to see the detail.';

    l_reject_prepared_link := ' Please click this link: '
                              || l_app_url
                              || '#preparedrequests/'
                              || :new.request_id
                              || ' to see the detail.';

    --this link is in the email send from 
    l_purchase_link := ' Please click this link: '
                       || l_app_url
                       || '#purchases'
                       || ' and select request '
                       || :new.request_id
                       || ' to see the detail.';

    l_received_link := ' Please click this link: '
                       || l_app_url
                       || '#historicalrequests/'
                       || :new.request_id
                       || ' to see the detail.';

    l_always_valid_link := 'Please be noted that the request moves within the approval process over time and the link above may not always work. To <b>view this request at any time</b>, click this link: '
                           || l_app_url
                           || '#requestsearching/'
                           || :new.request_id;

    --MB-382 once a request is approved by BAO, check if the items need to deliver to requester's home
    --email instruction to requester about the BCH will contact to get the address in separate email
    IF l_route_type_id = 3 THEN
       -- select COUNT (*) into l_req_cnt from request where REQUEST_ID = l_request_id;
       -- IF l_req_cnt = 1
       -- THEN
        SELECT
            requester_id,
            deliver_to_home
        INTO
            l_requester_id,
            l_deliv_to_home
        FROM
            request
        WHERE
            request_id = l_request_id;

        IF
            l_deliv_to_home IS NOT NULL
            AND l_deliv_to_home = 'Y'
            AND l_requester_id IS NOT NULL
            AND l_requester_id > 0
        THEN
            l_send_req_to_bch := true;
                --get BCH name and email
            l_sender2 := get_user_name(:new.route_to);
            l_sender2_email := get_user_email(:new.route_to);
                --get requester name and email
            l_receip2 := get_user_name(l_requester_id);
            l_receip2_email := get_user_email(l_requester_id);
        END IF;
        --END IF;
    END IF;




    --2018-6-20 xw: added a update statement to update the approval_amount in the request table so
    --it can be used to determine whether the request needs to be sent back if BCH changed the price
    /**don't need this anymore since approval amount is now updated on the route panel when the BAO approves the requestIF l_route_type_id = 3
   THEN
      UPDATE REQUEST
         SET APPROVAL_AMOUNT =get_request_total_cost (l_request_id)
       WHERE request_id = l_request_id;
   END IF;**/


    --based on route type, create email body
    CASE l_route_type_id
        WHEN 1 THEN
            l_body := l_sender
                      || ' submitted a bankcard purchase request to you for review.'
                      || l_link;
        WHEN 2 THEN
            l_body := l_sender
                      || ' routed a bankcard purchase request to you for approval.'
                      || l_link;
        WHEN 3 THEN
            l_body := l_sender
                      || ' approved and routed a bankcard purchase request to you for process/order.'
                      || l_link;
            --MB-382
            IF l_send_req_to_bch THEN
                l_body2 := ' You requested this bankcard order to be delivered to your home address.  Since we cannot store your home address in the bankcard system, please send me the delivery address via encrypted email for this order.' ||
                l_link;
            END IF;
        --2018-01-29 xw: ordered request becomes a purchase and cannot be accessed in #pendingrequests
        --2021-02-16 BCH ordered the items and the request goes to the BCH's purchase view
        --since it's the same person, send an email to the bch doesn't make any sense.
        WHEN 4 THEN
            l_body := l_sender || ' ordered the item(s) in the bankcard purchase request for you.'
            || l_reject_link; --reject link actually can be used for tracking submitted request
                --|| l_purchase_link;

        --2018-01-25 xw: rejected request should have use #requesttracking, not #pendingrequests
        --when 5 then l_body := l_sender || ' rejected the bankcard purchase request.' || l_reject_link;

        --MB-472 add body link for email send to the requester or other fed or associate
            SELECT
                created_by,
                created_for,
                l_requester_id
            INTO
                l_request_creator,
                l_created_for_id,
                l_requester_id
            FROM
                request
            WHERE
                request_id = l_request_id;

            IF
                l_created_for_id IS NOT NULL
                AND l_created_for_id > 0
            THEN
                --get associate name and email
                l_receip := get_user_name(l_created_for_id);
                l_receip_email := get_user_email(l_created_for_id);
            ELSE
                --get requester name and email
                l_receip := get_user_name(l_requester_id);
                l_receip_email := get_user_email(l_requester_id);
            END IF;

        WHEN 5 THEN
--2020-03-05 app currently reoute to requester only when request is rejected so we no longer need the 
--    l_reject_prepared_link and l_cc_email. if this changes again in the future, we still cannot do cc
--    because only the preparer can use the l_reject_prepared_link. the receipient or the cced person may not be the preparer    
--            BEGIN
--                SELECT created_by
--                  INTO l_request_creator
--                  FROM request
--                 WHERE request_id = l_request_id;
--
--                IF l_request_creator = l_route_to
--                THEN
--                    l_body :=
--                           l_sender
--                        || ' rejected the bankcard purchase request.'
--                        || l_reject_prepared_link;
--                ELSE
--                    l_body :=
--                           l_sender
--                        || ' rejected the bankcard purchase request.'
--                        || l_reject_link;
--                END IF;
--
--                l_cc_email := get_user_email (l_request_creator);
--                IF l_app_env <> 'PROD'
--                THEN
--                    l_cc_email := 'xinweiw@nist.gov';
--                END IF;
--                
--           END;

            l_body := l_sender
                      || ' rejected the bankcard purchase request.'
                      || l_reject_link;
        --03/21/2022 MB-452
        WHEN 13 THEN
            l_body := l_sender
                      || ' returned the bankcard purchase request to you for additional info or modification.'
                      || l_reject_link;
        
        --2018-01-29 xw: delivered request remain in the purchase view and cannot be accessed in #pendingrequests
        WHEN 6 THEN
            l_body := 'The bankcard purchase request has been delivered.' || l_purchase_link;
        --2018-01-29 xw: delivered request remain in the purchase view and cannot be accessed in #pendingrequests
        WHEN 7 --#7 might not be needed in the future. for now just keep it in case we need to come back 
         THEN
            l_body := 'The bankcard purchase request was received. The request record was archived for record keeping.' || l_received_link;
        -- 2017-10-30 yy: if cancel, send requisition number and item name list, do not send url link.
        WHEN 8 THEN
            BEGIN
                SELECT
                    requisition_number
                INTO l_requisition_number
                FROM
                    request
                WHERE
                    request_id = l_request_id;

                OPEN l_item_cur;                    -- PL/SQL evaluates factor

                LOOP
                    FETCH l_item_cur INTO l_item_name;
                    EXIT WHEN l_item_cur%notfound;
                    l_item_list := l_item_list
                                   || l_item_name
                                   || '<br>';
                END LOOP;

                CLOSE l_item_cur;
                l_body := l_sender
                          || ' has canceled the bankcard purchase request. The requisition number is: '
                          || l_requisition_number
                          || '. <br><br>Items include: <br><br>'
                          || l_item_list;
            END;
        WHEN 9 THEN
            l_body := l_sender
                      || ' rerouted a bankcard purchase request to you.'
                      || l_link;
        WHEN 10 THEN
            l_body := l_sender
                      || ' updated the bankcard purchase request.'
                      || l_link;
        WHEN 11 THEN
            l_body := l_sender
                      || ' re-submitted a bankcard purchase request to you for review.'
                      || l_link;
        --2018-01-26 xw: added notification to requester when someone prepared a request and send it to the requester for review
        WHEN 12 THEN
            l_body := l_sender
                      || ' prepared a bankcard purchase request to you for review.'
                      || l_link;
        ELSE
            RETURN;
    END CASE;

    SELECT
        route_type_name
    INTO l_route_type_name
    FROM
        lkup_route_type
    WHERE
        route_type_id = l_route_type_id;

    --select route_status_name into l_message from lkup_route_status where route_status_id = :new.route_status_id;


     --prevent dev and test email sent to users
    IF l_app_env = 'DEV' THEN
        l_receip_email := l_app_bcc;
        l_supervisor_email := l_app_bcc;
        l_receip2_email := l_app_bcc;
        l_subject := 'TEST TEST TEST from Development!!! ' || l_subject;
    ELSIF l_app_env = 'TEST' THEN
        l_receip_email := l_app_bcc;
        l_supervisor_email := l_app_bcc;
        l_receip2_email := l_app_bcc;
        l_subject := 'TEST TEST TEST !!!' || l_subject;
    ELSE
        l_receip_email := l_receip_email;
        l_supervisor_email := l_supervisor_email;
        l_subject := l_subject;
    END IF;

    --sent notification based on route
    --2018-01-29 xw: if sender is the one who routes the request to him or herself, there's no need to send a notification
    IF l_sender_email <> l_receip_email THEN

        --2022-02-25 find this code below and commented it out since we decided to not use HOST anymore in bankcard app

        -- check associate
        --so I added the additional logic in the is_associate function
        --2020-03-05 xw: if a request is submitted by an employee for an associates (l_route_status_id = 4),
        --the first review notification should send to the NIST Host for the associates
--        IF
--            l_route_type_id = 1
--            AND l_route_status_id = 4
--        THEN
--            l_supervisor_email := is_associate(l_request_id);
--            IF l_supervisor_email IS NOT NULL THEN
--                l_body := l_sender || ' submitted a bankcard purchase request for an associate under your supervision. Please check the link to verify it.';
--                IF l_app_env <> 'PROD' THEN
--                    l_supervisor_email := 'xinweiw@nist.gov';
--                END IF;
--                up_send_email(l_sender_email, l_supervisor_email, l_cc_email, l_app_bcc, l_subject
--                    --|| :new.request_id
--                 || ' has been made for an associate',
--                             'Dear supervisor:<br><br>' --|| l_body || '<br><br>Email should send to ' || l_supervisor_email || '.' || l_link || l_foot);
--                             || l_body
--                             || l_link
--                             || '<br><br>'
--                             || l_always_valid_link
--                             || l_foot);
--
--            END IF;

--        ELSIF l_route_type_id <> 7 THEN -- 7 is received. 

        IF l_route_type_id <> 7 THEN -- 7 is received. 

            up_send_email(l_sender_email, l_receip_email, l_cc_email, l_app_bcc, l_subject
                --|| :new.request_id
                                                                                 || ' has been '
                                                                                 || l_route_type_name,
                         'Dear '
                         || l_receip
                         || ':<br><br>'
                         || l_body
                         || '<br><br>'
                         || l_always_valid_link
                         || l_foot);

        END IF;
    END IF;

    --MB-382 notify requester if deliver to home is true and BAO approved
    IF l_send_req_to_bch AND l_sender_email <> l_receip_email
    THEN
        up_send_email(l_sender2_email, l_receip2_email, l_cc_email, l_app_bcc, l_subject
                --|| l_request_id
                                                                               || ' has been '
                                                                               || l_route_type_name,
                     'Dear '
                     || l_receip2
                     || ':<br><br>'
                     || l_body2
                     || '<br><br>'
                     || l_always_valid_link
                     || l_foot);
    END IF;

--if submitting a request, sent email for chemical and precious metal items
/*  2017-09-06 youchun yao: move the chemical notification to up_check_submit_request and up_notify_cispro
    if l_route_type_id = 1 then
        l_subject := '';
        l_body := '';

        OPEN l_item_cur;  -- PL/SQL evaluates factor
        LOOP
        FETCH l_item_cur INTO l_is_chemical, l_is_precious_metal;
        EXIT WHEN l_item_cur%NOTFOUND;
            -- chemical
            if l_is_chemical = 'Y' then
                l_subject := 'TEST TEST TEST!!! The Bankcard Purchase Request '  || l_request_id || ' for chemical item';
                l_body := 'Dear chemical regulator:<br><br>' || l_sender || ' submitted a bankcard purchase request to purchase chemical item. ';
            --precious metal
            elsif l_is_precious_metal = 1 then
                l_subject := 'TEST TEST TEST!!! The Bankcard Purchase Request '  || l_request_id || ' for precious metal item';
                l_body := 'Dear precious metal regulator:<br><br>' || l_sender || ' submitted a bankcard purchase request to purchase precious metal item. ';
            end if;
            if length(l_subject) > 0 then
                up_send_email(
                    l_sender_email,
                    l_test_receip_email,
                    l_test_cc_email,
                    l_subject,
                    l_body || l_link || l_foot);
            end if;
            l_subject := '';

        END LOOP;
        CLOSE l_item_cur;
    end if;
*/
EXCEPTION
    WHEN OTHERS THEN
        v_error_code := sqlcode;
        v_error_message := substr(sqlerrm, 1, 2000);
        INSERT INTO db_error (
            source,
            user_id,
            code,
            message
        ) VALUES (
            'email_notice',
            :new.request_id,
            v_error_code,
            v_error_message
        );

END;

CREATE TABLE BCPMS_OWNER.WEB_SERVICE_CALL_FAILED_RECORD
(	
    "ID" NUMBER GENERATED ALWAYS AS IDENTITY, 
	"WS_CATEGORY" NUMBER(2,0) NOT NULL,
	"REFERENCE_ID" NUMBER(10,0), 
	"WS_METHOD" VARCHAR2(10 BYTE), 
	"STATUS_CODE" NUMBER(4,0), 
	"ERROR_MESSAGE" VARCHAR2(2048 BYTE), 
	"CREATED" DATE, 
	"LAST_SUBMITTED" DATE, 
	"RECORD_DETAIL" VARCHAR2(4000 BYTE),
      CONSTRAINT FK_IBBR_CHEM_ITEM
    FOREIGN KEY (REFERENCE_ID)
    REFERENCES ITEM_CHEMICAL(ITEM_ID)
);
   
CREATE TABLE BCPMS_OWNER.ADMIN_USERS
(	
    "ID" NUMBER GENERATED ALWAYS AS IDENTITY, 
	"USER_NAME" VARCHAR2(20 BYTE)
);

insert into BCPMS_OWNER.ADMIN_USERS (USER_NAME) VALUES('xinweiw');


CREATE OR REPLACE SYNONYM BCPMS_APP.WEB_SERVICE_CALL_FAILED_RECORD FOR BCPMS_OWNER.WEB_SERVICE_CALL_FAILED_RECORD;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.WEB_SERVICE_CALL_FAILED_RECORD TO BCPMS_APP;


CREATE OR REPLACE SYNONYM BCPMS_APP.ADMIN_USERS FOR BCPMS_OWNER.ADMIN_USERS;

GRANT DELETE, INSERT, SELECT, UPDATE ON BCPMS_OWNER.ADMIN_USERS TO BCPMS_APP;
