 /*
 BANK-488
 */
 CREATE TABLE "BCPMS_OWNER"."DIV_PREFERENCES" 
   (	
    DIV_ID NUMBER(6,0) NOT NULL ENABLE, 
	just_Pref_Val VARCHAR2(1 BYTE) DEFAULT 'O' NOT NULL ENABLE, 
    finance_Pref_Val VARCHAR2(1 BYTE) DEFAULT 'O' NOT NULL ENABLE, 
    shipping_Cost_Pref_Val VARCHAR2(1 BYTE) DEFAULT 'R' NOT NULL ENABLE, 
    shipping_Cost_Pref_Val_Detail NUMBER(6,2) default 0,
    up_To_Pref_Val VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
    up_To_Pref_Val_Detail NUMBER(6,2) default 0
   );
   CREATE UNIQUE INDEX "BCPMS_OWNER".IDX_div_pref_ID ON "BCPMS_OWNER"."DIV_PREFERENCES" ("DIV_ID");
   ALTER TABLE "BCPMS_OWNER"."DIV_PREFERENCES" ADD CONSTRAINT div_pref_pk PRIMARY KEY ("DIV_ID")
   USING INDEX "BCPMS_OWNER".IDX_div_pref_ID  ENABLE;


  GRANT DELETE ON "BCPMS_OWNER"."DIV_PREFERENCES" TO "BCPMS_APP";
  GRANT INSERT ON "BCPMS_OWNER"."DIV_PREFERENCES" TO "BCPMS_APP";
  GRANT SELECT ON "BCPMS_OWNER"."DIV_PREFERENCES" TO "BCPMS_APP";
  GRANT UPDATE ON "BCPMS_OWNER"."DIV_PREFERENCES" TO "BCPMS_APP";