CREATE OR REPLACE PACKAGE BODY BCPMS_OWNER.EMAIL_PKG AS
    /*
    Created Date:                   October 2020
    Creator:                        ppg
    Purpose:                        Handles all email notifications for the NIST Employee Bankcard application
    
    10/7/21:                        added a check in CHECK_REQUEST_FOR_NO_BCH so if no match found, no email out
    */

    g_sid                           VARCHAR2 (20)       := '';
    g_prod                          boolean             := false;
    g_app_url                       VARCHAR2 (200)      := '';
    g_dfweekday                     VARCHAR2 (9)        := 'TUESDAY';
    
    g_from                          VARCHAR2(100)       := 'empbc@nist.gov';
    g_to                            VARCHAR2 (300)      := '';
    g_cc                            VARCHAR2 (300)      := '';
    g_bcc                           VARCHAR2 (300)      := '';
    s_subject_reminder              VARCHAR2 (500)      := 'REMINDER NOTIFICATION';
    s_subject_notify                VARCHAR2 (500)      := 'NOTIFICATION OF UPCOMING NEED BY DATE';
    s_subject_check_no_bch          VARCHAR2 (500)      := 'CHECK_REQUEST_FOR_NO_BCH';
    s_subject_check_invalid_bch     VARCHAR2 (500)      := 'CHECK_REQUEST_FOR_INVALID_BCH';
    g_subject                       VARCHAR2 (500)      := '';
    g_header                        VARCHAR2 (1000)     := 'Dear ';
    s_msg_reminder                  VARCHAR2 (3000)     := 'This is a reminder that a bankcard purchase request $1 is waiting for you';
    s_msg_notify                    VARCHAR2 (3000)     := 'This is a notification that a bankcard purchase request $1 has a need by date on $2 but the purchase is still not made.';
    s_msg_check_no_bch              VARCHAR2 (3000)     := 'This is to notify you that the following requests have no BCH:<br><br>$1';
    s_msg_check_invalid_bch         VARCHAR2 (3000)     := 'This is to notify you that the following requests have an invalid BCH:<br><br>$1';
    g_msg                           VARCHAR2 (3000)     := '';
    g_msg_end                       VARCHAR2 (20)       := '';
    g_footer                        VARCHAR2 (400)      := '<br><br>This message is auto generated by the OU Bankcard Request and Approval system. Please do not reply to this email.';
    g_to_name                       VARCHAR2 (30)       := '';
    g_errcode                       VARCHAR2 (20)       := '';
    g_errmsg                        VARCHAR2 (2000)     :='';

    function IS_PROD return boolean
    is
    begin
        if g_sid is not null then return g_prod; end if;
        
        SELECT UPPER (SYS_CONTEXT ('USERENV', 'DB_NAME')) INTO g_sid FROM DUAL;
          
        if g_sid = 'MML2PDI' then g_prod := true; end if;
        
        return g_prod;
    end;
    
    procedure GET_APP_URL
    is
    begin    
        select APP_URL into g_app_url from APP_SETTINGS;

        g_app_url := g_app_url || '#pendingrequests/';

    end;
    
    procedure UPDATE_LAST_EMAIL_DATE (
        route_id                    IN ROUTE.ROUTE_ID%TYPE
    )
    is
    begin
        if route_id is null or route_id < 1 then return; end if;
        
        update ROUTE set LAST_EMAIL_DATE = sysdate where ROUTE_ID = route_id;
        
        exception
            when OTHERS then
                g_errcode := SQLCODE;
                g_errmsg := SUBSTR (SQLERRM, 1, 2000);
                insert into db_error (source, user_id, code, MESSAGE)
                values ('SEND_EMAIL', route_id, g_errcode, g_errmsg);
    end;
    
    procedure SEND_EMAIL
    is
    begin
        if g_from is null or length (g_from) < 5 or g_to is null or length (g_to) < 5 then return; end if;
        if g_subject is null or length (g_subject) < 10 or g_msg is null or length (g_msg) < 10 then return; end if;
        
        UTL_MAIL.SEND(
            sender          => g_from,
            recipients      => g_to,
            bcc		        => g_bcc,
            subject         => g_subject,
            mime_type       => 'text/html',
            message         => g_msg
        );
        
        exception
            when OTHERS then
                g_errcode := SQLCODE;
                g_errmsg := SUBSTR (SQLERRM, 1, 2000);
                insert into db_error (source, user_id, code, MESSAGE)
                values ('SEND_EMAIL', 0, g_errcode, g_errmsg);
    end;

    procedure REMINDER_CHECK
        /*
        Created Date:                   October 2020
        Creator:                        ppg
        Purpose:                        periodically send email notifications to remind the reviewers, BAOs and BCHs of a pending action
        To test:                        exec BCPMS_OWNER.EMAIL_PKG.REMINDER_CHECK;
        */
    is
        l_request_id                 INTEGER               := 0;
        l_route_type_id              INTEGER               := 0;
        l_to_id                      INTEGER               := 0;        
        l_route_date                 DATE                  := null;
        l_last_email_date            DATE                  := null;
        l_today_weekday              VARCHAR2 (10)         := '';
        l_pref_weekday               VARCHAR2 (10)         := '';
        l_counter                    integer               := 0;
        l_today                      VARCHAR2 (9)          := '';             
    begin
        get_app_url;
        
        select trim(to_char(SYSDATE, 'DAY')) into l_today from dual;
    
        declare cursor cur_route is
        select REQUEST_ID, ROUTE_ID, ROUTE_TYPE_ID, ROUTE_BY, REROUTE_BY, ROUTE_TO, ROUTE_DATE, LAST_EMAIL_DATE
        from ROUTE r left outer join PREFERENCES p on r.ROUTE_TO = p.PEOPLE_ID
        where (p.PREF_VALUE is null and l_today = g_dfweekday or upper(p.PREF_VALUE) = l_today)
            and ROUTE_TYPE_ID in (1,2,3,11) 
            and trunc(route_date)>sysdate-120 --add this condition to stop reminders for requests older than 120 days
            and r.ROUTE_ID = (
            select ROUTE_ID from ROUTE s
            where r.REQUEST_ID = s.REQUEST_ID
            order by ROUTE_ID desc fetch first rows only)
        order by REQUEST_ID;
        begin
            for rec in cur_route loop
                l_request_id := rec.REQUEST_ID;
                l_route_date := rec.ROUTE_DATE;
                l_last_email_date := rec.LAST_EMAIL_DATE;
                
                l_route_type_id := rec.ROUTE_TYPE_ID;
                l_to_id := rec.ROUTE_TO;
                g_to := get_user_email (l_to_id);
                g_to_name := get_user_name (l_to_id);
                
                if l_route_type_id = 1 or l_route_type_id = 11 then
                    g_msg_end := ' to review.';
                elsif l_route_type_id = 2 then
                    g_msg_end := ' to approve.';
                elsif l_route_type_id = 3 then
                    g_msg_end := ' to order.';
                end if;
                
                g_subject := s_subject_reminder;
                               
                if not is_prod then
                    l_counter := l_counter + 1;
                    --if l_counter > 3 then continue; end if; --in dev and test we don't want to receive too many emails

                    g_to := 'xinweiw@nist.gov';
                    g_bcc := g_to;
                    g_subject := '(#' || l_counter || ' Sent from ' || g_sid || ') ' || s_subject_reminder;
                end if;
                
                g_msg := g_header || g_to_name || ':<br><br>' || replace (s_msg_reminder, '$1', l_request_id || ' (' || g_app_url || l_request_id || ')') || g_msg_end || g_footer;
                
                send_email;
                
                update_last_email_date (rec.ROUTE_ID);

            end loop;
        end;

        exception
            when OTHERS then
                g_errcode := SQLCODE;
                g_errmsg := SUBSTR (SQLERRM, 1, 2000);
                insert into db_error (source, user_id, code, MESSAGE)
                values ('REMINDER_CHECK', l_request_id, g_errcode, g_errmsg);
    end;
    
    procedure NOTIFY_BCH_OF_UP_ORDER
        /*
        Created Date:                   Decemberber 2020
        Creator:                        ppg
        Purpose:                        Notify BCHs of upcoming unpurchased orders when their need_by_date is within a defined number of days
        To test:                        exec BCPMS_OWNER.EMAIL_PKG.NOTIFY_BCH_OF_UP_ORDER;
        
        6/11/2021: changed to use v_request_current_route becuase the original query doesn't exclude records correctly
                   e.g. run original query on 6/11/21, request 36604 was purchased on 6/8/21 but was still showing in the 
                   returned records. (Megan reported)
        */
    is
        l_request_id                INTEGER               := 0;
        l_to_id                     INTEGER               := 0;
        l_nbd                       VARCHAR2 (10)         := '';
        l_threshold                 INTEGER               := 7;
        l_counter                   integer               := 0;
        
    begin
        get_app_url;
            
        select to_number (SYS_VALUE) into l_threshold from SYSTEM_VARS where SYS_KEY = 'NEED_BY_DATE_THRESHOLD';
        if l_threshold is null or l_threshold < 1 or l_threshold > 14 then l_threshold := 7; end if;
    
        declare cursor cur_route is
        select r.REQUEST_ID, BANKCARD_HOLDER_ID, to_char (NEEDED_BY_DATE,'mm/dd/yyyy') as nbd
        from 
        v_request_current_route r,
        --route r 
        REQUEST q
        where r.REQUEST_ID = q.REQUEST_ID
        and q.needed_by_date is not null and q.bankcard_holder_id is not null
        and exists (select * from NIST_USER where q.bankcard_holder_id = people_id)
        and trunc (NEEDED_BY_DATE) - trunc (sysdate) = l_threshold
        --and trunc (NEEDED_BY_DATE) - trunc (sysdate) < l_threshold -- for testing
        and r.ROUTE_TYPE_ID in (1,2,3,11) 
        --and r.ROUTE_ID = (
        --    select ROUTE_ID from ROUTE s
        --    where r.REQUEST_ID = s.REQUEST_ID
        --    order by r.ROUTE_ID desc fetch first rows only)
        order by r.REQUEST_ID;
        begin
            for rec in cur_route loop
                l_request_id := rec.REQUEST_ID;
                l_to_id := rec.BANKCARD_HOLDER_ID;

                l_nbd := rec.nbd;
                g_to := get_user_email (l_to_id);
                g_to_name := get_user_name (l_to_id);
                
                g_msg := g_header || g_to_name || ':<br><br>' || s_msg_notify || g_footer;
                g_msg := replace (g_msg, '$1', l_request_id || ' (' || g_app_url || l_request_id || ')');
                g_msg := replace (g_msg, '$2', l_nbd);
                
                g_subject := s_subject_notify;
                
                if not is_prod then
                    l_counter := l_counter + 1;
                    if l_counter > 3 then continue; end if; --in dev and test we don't want to receive too many emails

                    g_to := 'xinweiw@nist.gov';
                    g_bcc := g_to;
                    g_subject := '(#' || l_counter || ' Sent from ' || g_sid || ') ' || s_subject_notify;
                end if;
                
                send_email;
                --dbms_output.put_line ('request id = ' || l_request_id);
            end loop;
        end;
        
        exception
            when OTHERS then
                g_errcode := SQLCODE;
                g_errmsg := SUBSTR (SQLERRM, 1, 2000);
                insert into db_error (source, user_id, code, MESSAGE)
                values ('NOTIFY_BCH_OF_UP_ORDER', l_request_id, g_errcode, g_errmsg);
                dbms_output.put_line (g_errcode || ' - ' || 'NOTIFY_BCH_OF_UP_ORDER, request id = ' || l_request_id || ', ' || g_errmsg);
    end;

    procedure CHECK_REQUEST_FOR_NO_BCH
        /*
        Created Date:                   January 2021
        Creator:                        ppg
        Purpose:                        Check requests for null BCH, if found, notify the MML Systems Support
        To test:                        exec BCPMS_OWNER.EMAIL_PKG.CHECK_REQUEST_FOR_NO_BCH;
        */
    is
            l_request_id                INTEGER               := 0;
            l_msg                       VARCHAR2 (3000)       := '';
            is_found_rec boolean := false;
    begin
        declare cursor cur_route is
        select r.REQUEST_ID, BANKCARD_HOLDER_ID
        from v_request_current_route r, REQUEST q
        where r.REQUEST_ID = q.REQUEST_ID
        and q.bankcard_holder_id is null
        and r.ROUTE_TYPE_ID in (1,2,3,11) 
        --and r.ROUTE_ID = (
        --    select ROUTE_ID from ROUTE s
        --    where r.REQUEST_ID = s.REQUEST_ID
        --    order by r.ROUTE_ID desc fetch first rows only)
        order by r.REQUEST_ID;
        begin
            for rec in cur_route loop
                is_found_rec := true;
                l_request_id := rec.REQUEST_ID;
                if l_msg is not null then
                    l_msg := l_msg || ',<br>';
                end if;
                l_msg := l_msg || l_request_id;
            end loop;

            g_subject := s_subject_check_no_bch;
            g_to := 'MML.SystemsHelp@nist.gov';
            g_bcc := 'xinwei.wen@nist.gov';
            g_msg := g_header || 'MML Systems Supports:<br><br>' || replace (s_msg_check_no_bch, '$1', l_msg) || g_footer;
                               
            if not is_prod then
                g_to := 'xinweiw@nist.gov';
                g_bcc := g_to;
                g_subject := '(Sent from ' || g_sid || ') ' || s_subject_check_no_bch;
            end if;
              
            --use this to check for any match found; if no match, we don't really need to send the email  
            if is_found_rec then 
                send_email;
            end if;
            
        end;
        exception
            when OTHERS then
                g_errcode := SQLCODE;
                g_errmsg := SUBSTR (SQLERRM, 1, 2000);
                insert into db_error (source, user_id, code, MESSAGE)
                values ('CHECK_REQUEST_FOR_NO_BCH', l_request_id, g_errcode, g_errmsg);
                dbms_output.put_line (g_errcode || ' - ' || 'CHECK_REQUEST_FOR_NO_BCH, request id = ' || l_request_id || ', ' || g_errmsg);
    end;

    procedure CHECK_REQUEST_FOR_INVALID_BCH
        /*
        Created Date:                   January 2021
        Creator:                        ppg
        Purpose:                        Check requests for invalid BCH, if found, notify the MML Systems Support
        To test:                        exec BCPMS_OWNER.EMAIL_PKG.CHECK_REQUEST_FOR_INVALID_BCH;
        */
    is
            l_request_id                INTEGER               := 0;
            l_msg                       VARCHAR2 (3000)       := '';
    begin
        declare cursor cur_route is
        select r.REQUEST_ID, BANKCARD_HOLDER_ID
        from ROUTE r, REQUEST q
        where r.REQUEST_ID = q.REQUEST_ID
        and q.bankcard_holder_id is not null
        and not exists (select * from NIST_USER_ACTIVE where q.bankcard_holder_id = people_id)
        and r.ROUTE_TYPE_ID in (1,2,3,11) and r.ROUTE_ID = (
            select ROUTE_ID from ROUTE s
            where r.REQUEST_ID = s.REQUEST_ID
            order by r.ROUTE_ID desc fetch first rows only)
        order by r.REQUEST_ID;
        begin
            for rec in cur_route loop
                l_request_id := rec.REQUEST_ID;
                if l_msg is not null then
                    l_msg := l_msg || ',<br>';
                end if;
                l_msg := l_msg || l_request_id;
            end loop;

            g_subject := s_subject_check_invalid_bch;
            g_to := 'MML.SystemsHelp@nist.gov';
            g_bcc := 'xinwei.wen@nist.gov';
            g_msg := g_header || 'MML Systems Supports:<br><br>' || replace (s_msg_check_invalid_bch, '$1', l_msg) || g_footer;
                               
            if not is_prod then
                g_to := 'xinweiw@nist.gov';
                g_subject := '(Sent from ' || g_sid || ') ' || s_subject_check_invalid_bch;
            end if;
                
            send_email;
        end;
        exception
            when OTHERS then
                g_errcode := SQLCODE;
                g_errmsg := SUBSTR (SQLERRM, 1, 2000);
                insert into db_error (source, user_id, code, MESSAGE)
                values ('CHECK_REQUEST_FOR_INVALID_BCH', l_request_id, g_errcode, g_errmsg);
                dbms_output.put_line (g_errcode || ' - ' || 'CHECK_REQUEST_FOR_INVALID_BCH, request id = ' || l_request_id || ', ' || g_errmsg);
    end;

END EMAIL_PKG;
/