CREATE TABLE BCPMS_OWNER.USER_DETAILED
(
  ID                INTEGER GENERATED ALWAYS AS IDENTITY ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  PEOPLE_ID         NUMBER                      NOT NULL,
  OU_ORG_ID         NUMBER(6)                   NOT NULL,
  DIV_ORG_ID        NUMBER(6),
  GRP_ORG_ID        NUMBER,
  ACCESS_GROUP      VARCHAR2(1 BYTE)            DEFAULT 'N'                   NOT NULL,
  ACCESS_DIV        VARCHAR2(1 BYTE)            DEFAULT 'N'                   NOT NULL,
  ACCESS_OU         VARCHAR2(1 BYTE)            DEFAULT 'N'                   NOT NULL,
  VALID_UNTIL_DATE  DATE
)
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX BCPMS_OWNER.USER_DETAILED_PK ON BCPMS_OWNER.USER_DETAILED
(ID)
LOGGING
TABLESPACE BCPMS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE BCPMS_OWNER.USER_DETAILED ADD (
  CONSTRAINT USER_DETAILED_PK
  PRIMARY KEY
  (ID)
  USING INDEX BCPMS_OWNER.USER_DETAILED_PK
  ENABLE VALIDATE);