CREATE OR REPLACE FUNCTION BCPMS_OWNER.get_user (
   p_people_id   IN NIST_USER.PEOPLE_ID%TYPE)
   RETURN NIST_USER%ROWTYPE
IS
   l_user   NIST_USER%ROWTYPE;
BEGIN
   SELECT *
     INTO l_user
     FROM NIST_USER
    WHERE people_id = p_people_id;

   RETURN l_user;
END;
/


CREATE OR REPLACE SYNONYM BCPMS_APP.GET_USER FOR BCPMS_OWNER.GET_USER;


GRANT EXECUTE ON BCPMS_OWNER.GET_USER TO BCPMS_APP;