CREATE OR REPLACE FUNCTION BCPMS_OWNER.get_user_email (
   p_people_id   IN NIST_USER.PEOPLE_ID%TYPE)
   RETURN NVARCHAR2
IS
   l_user_email   NVARCHAR2 (50);
BEGIN
   SELECT EMAIL
     INTO l_user_email
     FROM NIST_USER
    WHERE people_id = p_people_id;

   RETURN l_user_email;
END;
/


CREATE OR REPLACE SYNONYM BCPMS_APP.GET_USER_EMAIL FOR BCPMS_OWNER.GET_USER_EMAIL;


GRANT EXECUTE ON BCPMS_OWNER.GET_USER_EMAIL TO BCPMS_APP;