version=${project.version}

use.sso.proxy=false
sso.proxy.username=xinweiw

use.gendev.password=false
gendev.password=MvCHw_6RLj#3EPt

app.environment=test

are.ibbr.ws.calls.active=false
ibbr.username.and.password=nist_api:Zbbr5872$
ibbr.create.chemical.item.url=http://webdev.ibbr.umd.edu/api/ibbr_nist_chem

requisition.number.url=https://emp-test.nist.gov/nap/controllers/v2/divReqNum/generate
requisition.number.authorization.code=dgVfjXqNRqGyfKJKzvonAKHgX

mml.ou.itso.url=https://mmltest.nist.gov/org/api/v2/organization_units/roleholders/%s/ITSO
mml.employee.roles.url=https://mmltest.nist.gov/org/api/v1/employees/%d/roles
mml.employee.bankcard.approvers.url=https://mmltest.nist.gov/org/api/v1/employees/%d/bankcard_approvers
mml.bankcard.holders.url=https://mmltest.nist.gov/org/api/v2/divisions/roleholders/%s/Bankcard%%20Holder
mml.bankcard.approving.official.url=https://mmltest.nist.gov/org/api/v2/divisions/roleholders/%s/Bankcard%%20Approving%%20Official
mml.funds.certifying.official.url=https://mmltest.nist.gov/org/api/v2/divisions/roleholders/%s/Funds%%20Certifying%%20Official
mml.mission.critical.director.approver.url=https://mmltest.nist.gov/org/api/v2/organization_units/roleholders/%s/Mission%%20Critical%%20Director%%20Approver
mml.cispro.users.url=https://mmltest.nist.gov/org/api/v2/groups/cims_power_users/%s/%s
mml.supported.divisions.url=https://mmltest.nist.gov/org/api/v2/employees/%d/admin_officer_div
mml.property.custodians.url=https://mmltest.nist.gov/org/api/v2/divisions/property_custodians/%s
mml.ou.roles.url=https://mmltest.nist.gov/org/api/v2/organization_units/roleholders/%s/All
mml.division.itso.url=https://mmltest.nist.gov/org/api/v2/divisions/roleholders/%s/DITSO
mml.division.chief.url=https://mmltest.nist.gov/org/api/v2/divisions/roleholders/%s/Division%%20Chief
mml.deputy.chief.url=https://mmltest.nist.gov/org/api/v2/divisions/roleholders/%s/Deputy%%20Chief
mml.delegation.by.username.url=https://mmltest.nist.gov/org/api/v1/delegations/nap_find_by_username/%s
mml.employee.by.nist.org.id.url=https://mmltest.nist.gov/org/api/v1/employees/%d
