/*
 * File: app/model/BcpItem.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.model.BcpItem', {
    extend: 'Ext.data.Model',
    alias: 'model.bcpitem',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Boolean',
        'Ext.data.field.Date'
    ],

    idProperty: 'itemId',

    fields: [
        {type: 'int', mapping: 'id', name: 'itemId'},
        {type: 'int', name: 'requestId'},
        {type: 'int', name: 'vendorId'},
        {type: 'string', name: 'vendorName'},
        {type: 'string', name: 'requisitionNumber'},
        {type: 'string', name: 'itemName'},
        {type: 'string', name: 'description'},
        {type: 'string', name: 'catalogNumber'},
        {type: 'string', name: 'purpose'},
        {type: 'float', defaultValue: 0, mapping: 'price', name: 'unitPrice'},
        {type: 'int', defaultValue: 1, name: 'quantity'},
        {
            type: 'float',
            convert: function (v, rec) {
                return rec.data.unitPrice * rec.data.quantity;
            },
            name: 'amount'
        },
        {type: 'string', name: 'unitIssue'},
        {type: 'int', defaultValue: 0, name: 'shoppingCartFileId'},
        {
            type: 'boolean',
            defaultValue: false,
            mapping: 'chemical',
            name: 'isChemical'
        },
        {type: 'boolean', defaultValue: false, name: 'isTaggableEquipment'},
        {type: 'boolean', defaultValue: false, name: 'isShippingCost'},
        {type: 'string', name: 'objectClass'},
        {type: 'string', mapping: 'projectTask', name: 'projTask'},
        {type: 'string', name: 'createdByName'},
        {type: 'date', name: 'createdDate'},
        {type: 'string', name: 'updatedByName'},
        {type: 'date', name: 'updatedDate'},
        {name: 'itemType'},
        {type: 'float', defaultValue: 0, name: 'actualPrice'},
        {type: 'int', name: 'actualQuantity'},
        {
            type: 'float',
            convert: function (v, rec) {
                return rec.data.actualPrice * rec.data.actualQuantity;
            },
            name: 'actualAmount'
        },
        {mapping: 'latestItemStatusTypeName', name: 'itemStatus'},
        {mapping: 'latestItemStatusTypeId', name: 'itemStatusId'},
        {name: 'itemNotes'},
        {type: 'date', mapping: 'dateReceived', name: 'receivedDate'},
        {name: 'ibbrRoomName'},
        {name: 'ibbrRoomId'},
        {name: 'transactionNumber'},
        {type: 'date', name: 'statementDate'}
    ]
});
