/*
 * File: app/model/BcpVendor.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.model.BcpVendor', {
    extend: 'Ext.data.Model',
    alias: 'model.bcpvendor',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean',
        'Ext.data.field.Date'
    ],

    idProperty: 'vendorId',

    fields: [
        {type: 'int', defaultValue: 0, name: 'vendorId'},
        {type: 'int', name: 'requestId'},
        {type: 'string', name: 'name'},
        {type: 'string', name: 'streetAddr'},
        {type: 'string', name: 'city'},
        {type: 'string', name: 'state'},
        {type: 'string', name: 'zipcode'},
        {type: 'string', name: 'webUrl'},
        {type: 'string', name: 'contactName'},
        {type: 'string', name: 'phone'},
        {type: 'string', name: 'fax'},
        {type: 'string', name: 'email'},
        {type: 'string', name: 'nonElectricJust'},
        {type: 'string', name: 'nonGsaJust'},
        {type: 'string', name: 'nonSbJust'},
        {type: 'string', name: 'thirdPartyJust'},
        {type: 'string', name: 'priceJust'},
        {type: 'boolean', name: 'noJustNeeded'},
        {type: 'boolean', name: 'isNonElectric'},
        {type: 'boolean', name: 'isNonGsa'},
        {type: 'boolean', name: 'isNonSb'},
        {type: 'boolean', name: 'isThirdParty'},
        {type: 'boolean', name: 'isPriceReasonable'},
        {type: 'int', name: 'createdBy'},
        {type: 'string', name: 'createdByName'},
        {type: 'date', name: 'createdDate'},
        {type: 'string', name: 'updatedByName'},
        {type: 'date', name: 'updatedDate'},
        {type: 'string', name: 'convenienceCheckNumber'},
        {type: 'boolean', defaultValue: false, name: 'isForeignAddress'},
        {type: 'string', name: 'foreignAddress'},
        {type: 'boolean', name: 'isProfessionalOrg'}
    ]
});
