/*
 * File: app/model/RequestRoute.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.model.RequestRoute', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    idProperty: 'routeId',

    fields: [
        {type: 'int', name: 'routeId'},
        {type: 'int', name: 'requestId'},
        {type: 'int', name: 'statusId'},
        {type: 'string', name: 'statusName'},
        {type: 'int', name: 'typeId'},
        {type: 'string', name: 'typeName'},
        {type: 'date', mapping: 'timestamp', name: 'date'},
        {type: 'string', name: 'notes'},
        {type: 'int', name: 'routeBy'},
        {
            type: 'string',
            convert: function (v, rec) {
                if (rec.get('routeByDelegateName') != '') {
                    //if approved/routed by a delegate
                    return (
                        rec.get('routeByDelegateName') +
                        ' [On behalf of ' +
                        v +
                        ']'
                    );
                } else {
                    return v;
                }
            },
            name: 'routeByName'
        },
        {type: 'int', name: 'routeByDelegate'},
        {type: 'int', name: 'omitNotification'},
        {type: 'string', name: 'routeByDelegateName'},
        {type: 'int', name: 'routeTo'},
        {type: 'string', mapping: 'fullNameTo', name: 'routeToName'},
        {type: 'int', name: 'rerouteBy'},
        {type: 'string', name: 'rerouteByName'},
        {type: 'int', name: 'isDynamic'},
        {type: 'int', name: 'isDynamicReroute'},
        {type: 'int', name: 'rerouteStack'},
        {type: 'int', name: 'divisionId'},
        {type: 'int', name: 'routeStep'},
        {type: 'string', name: 'dynamicType'}
    ]
});
