/*
 * File: app/model/RouteRule.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.model.RouteRule', {
    extend: 'Ext.data.Model',

    requires: ['Ext.data.field.Integer', 'Ext.data.field.Boolean'],

    idProperty: 'routeStatusId',

    fields: [
        {type: 'int', name: 'routeStatusId'},
        {type: 'boolean', defaultValue: false, name: 'accept'},
        {type: 'boolean', defaultValue: false, name: 'submit'},
        {type: 'boolean', defaultValue: false, name: 'review'},
        {type: 'boolean', defaultValue: false, name: 'approve'},
        {type: 'boolean', defaultValue: false, name: 'process'},
        {type: 'boolean', defaultValue: false, name: 'reject'},
        {type: 'boolean', defaultValue: false, name: 'reroute'}
    ]
});
