/*
 * File: app/model/UserProfile.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.model.UserProfile', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],

    idProperty: 'peopleId',

    fields: [
        {type: 'int', name: 'peopleId'},
        {type: 'string', mapping: 'username', name: 'userName'},
        {type: 'string', name: 'displayName'},
        {type: 'string', mapping: 'ouCode', name: 'ou'},
        {type: 'string', mapping: 'divisionCode', name: 'division'},
        {type: 'string', name: 'group'},
        {type: 'int', name: 'ouId'},
        {type: 'int', mapping: 'divisionId', name: 'divId'},
        {type: 'int', mapping: 'groupId', name: 'grpId'},
        {name: 'userRoles'},
        {type: 'int', name: 'defaultHostId'},
        {type: 'int', name: 'defaultReviewerId'},
        {type: 'int', name: 'defaultBaoId'},
        {type: 'int', name: 'defaultBhId'},
        {name: 'supervisor'},
        {name: 'groupLeader'},
        {name: 'divisionChief'},
        {name: 'AdministrativeOfficer'},
        {name: 'host'},
        {type: 'boolean', defaultValue: 0, name: 'isAssociate'},
        {type: 'int', name: 'bossId'},
        {name: 'email'},
        {name: 'firstName'},
        {name: 'lastName'},
        {name: 'middleName'},
        {name: 'phoneNumber'},
        {name: 'staffType'},
        {type: 'boolean', name: 'delegating'},
        {type: 'boolean', name: 'detaileeMode'}
    ]
});
