/*
 * File: app/model/Vendor.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bcp.model.Vendor', {
    extend: 'Ext.data.Model',
    alias: 'model.vendor',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Boolean'
    ],

    idProperty: 'vendorId',

    fields: [
        {type: 'int', name: 'vendorId'},
        {type: 'string', name: 'vendorName'},
        {type: 'string', name: 'street'},
        {type: 'string', name: 'city'},
        {type: 'string', name: 'state'},
        {type: 'string', name: 'zip'},
        {type: 'string', name: 'webUrl'},
        {type: 'string', name: 'contactPerson'},
        {type: 'string', name: 'phone'},
        {type: 'string', name: 'fax'},
        {type: 'string', name: 'email'},
        {type: 'string', name: 'accountNumber'},
        {type: 'int', name: 'createdBy'},
        {type: 'date', name: 'createdDate'},
        {type: 'int', name: 'updatedBy'},
        {type: 'date', name: 'updatedDate'},
        {type: 'boolean', name: 'isForeignAddress'},
        {type: 'string', name: 'foreignAddress'},
        {type: 'string', name: 'additionalInfo'},
        {type: 'boolean', name: 'isActive'},
        {type: 'string', name: 'dunsNumber'},
        {type: 'int', name: 'ouId'},
        {type: 'int', name: 'divisionId'},
        {type: 'int', name: 'groupId'},
        {type: 'int', name: 'shared'}
    ]
});
