/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({});

Ext.application({
    models: [
        "UserProfile",
        "UserRole",
        "RequestRoute",
        "BcpRequest",
        "BcpVendor",
        "BcpFile",
        "BcUser",
        "ItsoUser",
        "BcpItem",
        "EaItem",
        "ChemicalItem",
        "LookUpData",
        "ProjectTask",
        "ObjectClass",
        "defaultRouteInfo",
        "RouteRule",
        "OrgData",
        "NistOrgDefaultRoute",
        "Vendor",
        "RequestVendor",
        "RequestJustification",
        "DelegateProfile",
        "WsCallFailedRecord",
        "IbbrRecord",
        "DivisionPreference",
        "BchInitial",
        "UserDetailedPrivilege",
        "DetaileeUser",
        "OuRoleUser",
        "PcItem",
        "DetailedUser"
    ],
    stores: [
        "BcpAppVersion",
        "LkUserRolesNotUsed",
        "UserRoles",
        "RequestRoutes",
        "ItsoUsers",
        "FileCategories",
        "DefaultRoutes",
        "Reviewers",
        "Baos",
        "BankcardHolders",
        "RouteRules",
        "NonSbJustifications",
        "PriceJustifications",
        "ThirdPartyJustifications",
        "CommercialVendorJustifications",
        "UsStates",
        "ActiveRequests",
        "PendingRequests",
        "ProcessedRequests",
        "HistoricalRequests",
        "ProjectTaskCodes",
        "ProjectTaskCodesSearch",
        "Divisions",
        "SupportedDivisions",
        "Groups",
        "PrefWeekdays",
        "DivisionPreferences",
        "RequestStatuses",
        "LkItemStatus",
        "NavigationTree",
        "ObjectClasses",
        "SavedRequests",
        "OuAllStaffs",
        "OuEmployees",
        //'DivEmployees',
        "NistEmployees",
        "Ous",
        "NonGsaJustifications",
        "PreparedRequests",
        "IbbrRooms",
        "SubViews",
        "DashSettings",
        "AuthUser",
        "RequestVendors",
        "CurrentRequest",
        "RequestItems",
        "RequestFiles",
        "LkSharedLevels",
        "SharedVendors",
        "RequestJustifications",
        "RoutingHistory",
        "Fys",
        "Delegates",
        "IbbrRecordStore",
        "WsCallFailedRecordStore",
        "BchInitials",
        "PrefNotificationFrequency",
        "OuRoles",
        "UserDetailedPrivileges",
        "Detailees",
        "RequesterUserRoles",
        "PurchaseTypes",
        "Fcos",
        "OuFcos",
        "AllFcos",
        "DivisionChiefs",
        "MissionCriticalCategories",
        "DetailedUsers"
    ],
    views: [
        "PtcWindow",
        "FinancePanel",
        "RoutePanel",
        "ItemPanel",
        "VendorPanel",
        "PersonAsVendorWindow",
        "GeneralInfoPanel",
        "RoutingHistory",
        "FileUploadForm",
        "FileAttachments",
        "RouteWindow",
        "DynamicRouteWindow",
        "ReadOnlyRequest",
        "PendingRequests",
        "Purchases",
        "ShippingCostWindow",
        "ItemCreditWindow",
        "Preferences",
        "DivPreferences",
        "RequestSearching",
        "OcWindow",
        "DashBoard",
        "RequestsDashView",
        "Page404",
        "Page401",
        "ChangeRouteWindow",
        "JustificationPanel",
        "RequestGrid",
        "ItemGrid",
        "AuditReport",
        "EAReport",
        "FileAttachmentGrid",
        "ItemStatusesWindow",
        "OrderWindow",
        "IbbrRoomTreeWindow",
        "SavedRequests",
        "AppContainer",
        "NewRequest",
        "RequestTrackingBase",
        "PreparedRequests",
        "RequestTracking",
        "HistoricalRequests",
        "BchCommentWindow",
        "DescriptionWindow",
        "PartialDeliveryWindow",
        "EditReq",
        "CreateRequestWindow",
        "WarningWindow",
        "ChangeRequesterWindow",
        "VendorPanel",
        "Vendors",
        "JustificationPanel",
        "WsCallFailedRecord",
        "IbbrRecord",
        "windows.RouteBack",
        "windows.BcpAlert",
        "EditMissionCriticalWindow",
        "PcItemReport",
        "ItemsReport",
        "DetailedUsers"
    ],
    controllers: ["AppController"],
    defaultToken: "dashboard",
    name: "bcp",

    launch: function () {
        //set up default properties for ajax requests
        //Ext.Ajax.useDefaultXhrHeader=false;
        Ext.Ajax.defaultHeaders = {
            Accept: "application/json",
            //'Content-Type': 'application/x-www-form-urlencoded'
            "Content-Type": "application/json"
        };
        Ext.Ajax.method = "POST";

        Ext.Ajax.disableCaching = false;
        Ext.Ajax.setTimeout(60000);

        //define logout message
        //window.onbeforeunload = function (e) {
        //    return 'You will be logged out of the application.';
        // };
        //Okta change
        //get rid of the "leave site" message when redirect using window.location.href
        window.addEventListener("beforeunload", function (e) {
            // Cancel the "Leave Site?" prompt by returning an empty string
            e.returnValue = ""; // For older browsers
            return ""; // For modern browsers
        });

        //Define a runtime config file
        Ext.define("bcp.config.Runtime", {
            singleton: true,
            config: {
                serverBaseUrl: "/empbc/v1/", // init value
                //serverBaseUrl : window.location.origin+'/stick/cfc/webservices/'
                mode: "Offline",
                purchaseLimit: 20000,
                itsoLimit: 0 //issue 606, used to be $3500 but now all IT purchases need ITSO approval
            },
            constructor: function (config) {
                this.initConfig(config);
            }
        });

        //handles failure request
        Ext.Ajax.on("requestexception", function (conn, response, options, e) {
            var statusCode = response.status,
                subject = "?subject=EMPBC Error",
                message = "",
                body = "&body=",
                mailto = "mailto:MML.SystemsHelp@nist.gov";

            //in case there's a mask
            Ext.getBody().unmask();

            // 404 - file or method not found - special case
            if (statusCode == 404) {
                message = "URL " + options.url + " not found";
            } else if (statusCode == 500) {
                message = "Server side operation failure.";
            } else if (statusCode == 403) {
                message = "Server side operation forbidden.";
            } else if (statusCode == 406) {
                //remove the browser's default popup
                window.onbeforeunload = null;
                window.location.href = "/empbc/login.html";
                return;
            } else if (statusCode == 401) {
                /*Ext.MessageBox.alert('Session Timed Out',
                    'Please reload the page by clicking the [Ok] button to create a new session.',
                    function () {
                        location.reload();
                    });*/

                //if users try to access a request without proper privilege (change the request id in the url, for example), the
                //server method would return code 401
                //and doing location reload would lead to a loop of reloading the app
                //location.reload();

                //if a route uses the before method to prep data, then the
                //prepdata method in the appcontainer will display an alert and redirect the user to dashboard, so no need to redirect to
                //page 401. However, if it does not use prep data, we have to redirect the user
                window.location.href = window.location.pathname + "#page401";
                return;
            } else {
                var userInfo = "";
                try {
                    userInfo = JSON.stringify(Ext.getStore("AuthUser").first().data);
                } catch (ex) {
                    userInfo = "unable to get user info.";
                }
                //get some basic info
                message =
                    "  Error for " +
                    options.method +
                    " on " +
                    options.url +
                    "   " +
                    "at   " +
                    window.location.href +
                    "   " +
                    "with user info: " +
                    userInfo;
                message = message.replace(/&/g, "+");

                try {
                    var jsonResp = Ext.decode(response.responseText);
                    //add server side returned error message if any
                    message = jsonResp.error.description + "   " + message;
                } catch (ex) {
                    console.log(ex);
                }
            }

            message = Ext.htmlEncode(message);
            body = body + message;
            mailto = mailto + subject + body;
            Ext.Msg.alert(
                "Error",
                "Unexpected error happened.<br>" +
                    options.method +
                    " on " +
                    options.url +
                    "<br>" +
                    '<a href="' +
                    mailto +
                    '" ' +
                    'target="_blank">Please click here to report the error.</a>'
            );
        });

        Ext.define(
            "bcp.mixin.Badge",
            {
                extend: "Ext.Mixin",

                requires: [
                    //require this for the override
                    "Ext.button.Button"
                ],

                mixinConfig: {
                    id: "badge",
                    after: {
                        onRender: "renderBadgeText"
                    }
                },

                config: {
                    badgeText: null
                },

                renderBadgeText: function () {
                    var badgeText = this.getBadgeText();

                    if (badgeText) {
                        this.updateBadgeText(badgeText);
                    }
                },

                updateBadgeText: function (badgeText, oldBadgeText) {
                    var me = this,
                        el = me.el;

                    if (me.rendered) {
                        el.set({
                            "data-badge-text": badgeText
                        });

                        el.toggleCls(Ext.baseCSSPrefix + "badge", !!badgeText);

                        me.fireEvent("badgetextchange", me, badgeText, oldBadgeText);
                    }
                }
            },
            function (BadgeMixin) {
                Ext.override(Ext.button.Button, {
                    mixins: [BadgeMixin]
                });
            }
        );

        //define common util methods
        Ext.define("bcp.util.CommonUtil", {
            singleton: true,

            /**
             * Helper function to load a store and return a Promise.
             * @param {Ext.data.Store} store The store to load.
             * @returns {Ext.Promise} A promise that resolves with the loaded store or rejects on error.
             */
            loadStore: function (store) {
                return new Ext.Promise(function (resolve, reject) {
                    store.load({
                        callback: function (records, operation, success) {
                            if (success) {
                                console.log("Successfully loaded store: " + store.getStoreId());
                                resolve(store);
                            } else {
                                var errorMsg = "Failed to load store: " + store.getStoreId();
                                if (operation && operation.getError()) {
                                    errorMsg += ". Error: " + operation.getError();
                                }
                                console.error(errorMsg);
                                reject(errorMsg);
                            }
                        }
                    });
                });
            },
            //reusable alert with focus on the ok button
            //test script can use keydown enter to close the alert
            //without the need to locate the ok button
            showAlert: function (title, message, fn, scope) {
                let msgBox = Ext.Msg.alert(title, message, fn, scope);
                // wait for msgbox to be fully rendered
                Ext.defer(() => {
                    let okButton = msgBox.down("button[text=OK]");
                    if (okButton) {
                        okButton.focus();
                    }
                }, 100);
            },
            showWarning: function (message) {
                this.showAlert("Warning", message);
            },
            showError: function (message) {
                this.showAlert("Error", message);
            },
            showValidationError: function (message) {
                this.showAlert("Validation Error", message);
            },
            deepCloneStore: function (source) {
                var target = Ext.create("Ext.data.Store", {
                    model: source.model
                });

                Ext.each(source.getRange(), function (record) {
                    var newRecordData = Ext.clone(record.copy().data);
                    var model = new source.model(newRecordData, newRecordData.id);

                    target.add(model);
                });

                return target;
            },
            createFormInput: function (type, name, value) {
                var myinput = document.createElement("input");
                myinput.type = type;
                myinput.name = name;
                myinput.value = value;
                return myinput;
            },
            makeFormReadOnly: function (form, isReadOnly) {
                Ext.suspendLayouts();
                form.getFields().each(function (field) {
                    field.setReadOnly(isReadOnly);
                });
                Ext.resumeLayouts();
            },
            getInvalidFields: function (form) {
                var invalidFields = [];
                Ext.suspendLayouts();
                form.getForm()
                    .getFields()
                    .filterBy(function (field) {
                        if (field.validate()) return;
                        invalidFields.push(field);
                    });
                Ext.resumeLayouts(true);
                return invalidFields;
            },
            getInvalidFieldsAlert: function (form) {
                var fieldNames = [];
                var fields = this.getInvalidFields(form);
                for (var i = 0; i < fields.length; i++) {
                    var field = fields[i];
                    fieldNames.push(field.fieldLabel);
                }
                Ext.Msg.alert("Invalid Fields", "The following fields are invalid: " + fieldNames.join(", "));
            },
            disableButtons: function (component) {
                component.query("button").forEach(function (comp) {
                    comp.disable();
                });
            },
            enableButtons: function (component) {
                component.query("button").forEach(function (comp) {
                    comp.enable();
                });
            },
            isUserInRole: function (allowedRoles, roles) {
                // Check if allowedRoles is valid
                if (!Array.isArray(allowedRoles) || allowedRoles.length === 0) {
                    return false;
                }

                //use supplied roles by default, if not provided, use logged in user's roles in the UserRoles store
                if (!roles) {
                    roles = Ext.getStore("UserRoles").data.items;
                }
                //check user role and return true or false
                for (var j = 0; j < roles.length; j++) {
                    //make it work whether it's a extjs model obj or a simple obj
                    var roleName = roles[j].isModel ? roles[j].get("name") : roles[j].name;
                    //if app admin or is one of the allowedRoles
                    if (roleName === "App Admin" || allowedRoles.includes(roleName)) {
                        return true;
                    }
                }
                return false;
            },
            currentFiscalYear: function () {
                var currentYear = new Date().getFullYear(), //yr in 4 digits
                    currentFy = Number(currentYear.toString().substr(-2)), //yr in 2 digits
                    createNextFyEndDate = new Date(new Date().getFullYear() + "-10-01T00:00:00-04:00");
                if (new Date() >= createNextFyEndDate) {
                    currentFy++;
                }
                return currentFy;
            },
            moneyRenderer: function (val) {
                if (val >= 0) {
                    return '<span style="color:green;">' + Ext.util.Format.usMoney(val) + "</span>";
                } else if (val < 0) {
                    return '<span style="color:red;">' + Ext.util.Format.usMoney(val) + "</span>";
                }
                return val;
            },
            ynRenderer: function (val) {
               val = (val || "N").toString().toUpperCase();
                if (val === "Y") {
                    return 'Yes';
                }
                return 'No';
            },
            urlRenderer: function (value, displayName) {
                var myURL = "";
                if (value) {
                    //if user enters a website name without http, add it to make it a valid url
                    if (value.indexOf("http") === -1) {
                        value = "https://" + value;
                    }
                    myURL = '<a href="' + value + '" target="_blank">' + displayName + "</a>";
                }
                return myURL;
            },
            removeSafetySuffix: function (str) {
                // Check if the Requisition number ends with any of the specified suffixes
                if (str.endsWith("-CHEM")) {
                    return str.slice(0, -5); // Remove '-CHEM'
                } else if (str.endsWith("-BIO")) {
                    return str.slice(0, -4); // Remove '-BIO'
                } else if (str.endsWith("-BIOCH")) {
                    return str.slice(0, -6); // Remove '-BIOCH'
                }
                return str; // Return the original string if no suffix is found
            },
            convertFileToBase64: function (file) {
                return new Ext.Promise(function (resolve, reject) {
                    const reader = new FileReader();
                    reader.readAsDataURL(file);
                    reader.onload = () => resolve(reader.result);
                    reader.onerror = (error) => reject(error);
                });
            },
            ajaxSuccessHandler: function (response, handler) {
                var jsonResp = {},
                    subject = "?subject=EMPBC Error",
                    //message = "",
                    body = "&body=",
                    mailto = "mailto:MML.SystemsHelp@nist.gov";

                try {
                    jsonResp = Ext.decode(response.responseText);
                } catch (ex) {
                    body = body + Ext.htmlEncode(ex.stack);
                    mailto = mailto + subject + body;
                    Ext.Msg.alert(
                        "Error",
                        "Unexpected error happened.<br>" +
                            '<a href="' +
                            mailto +
                            '" ' +
                            'target="_blank">Please click here to report the error.</a>'
                    );
                    return;
                }
                if (typeof jsonResp !== "undefined") {
                    if (jsonResp.success) {
                        handler(jsonResp);
                    } else {
                        //currently, this is the only validation error
                        if (jsonResp.error.code == 1008) {
                            Ext.Msg.alert("Validation Error", "<b>" + jsonResp.error.description + "<b>");
                        } else {
                            //ajax call returned a json containing success=false
                            //it should be a catched error from server side and can display
                            //detailed error message
                            body = body + Ext.htmlEncode(jsonResp.error.description);
                            mailto = mailto + subject + body;
                            Ext.Msg.alert(
                                "Error",
                                "Unexpected error happened.<br>" +
                                    "Error Detail: <b>" +
                                    jsonResp.error.description +
                                    "<b><br>" +
                                    '<a href="' +
                                    mailto +
                                    '" ' +
                                    'target="_blank">Please click here to report the error.</a>'
                            );
                            return;
                        }
                    }
                } else {
                    //the returned response is not generated by server side error handler
                    //display a generic error message and include everything in the email body
                    body = body + Ext.htmlEncode(response);
                    mailto = mailto + subject + body;
                    Ext.Msg.alert(
                        "Error",
                        "Unexpected error happened.<br>" +
                            '<a href="' +
                            mailto +
                            '" ' +
                            'target="_blank">Please click here to report the error.</a>'
                    );
                }
            },
            responseHandler: function (response) {
                var jsonResp = null;
                try {
                    jsonResp = Ext.decode(response.responseText);
                } catch (ex) {
                    Ext.Msg.alert("Error", "Unexpected error happened.");
                    return null;
                }

                if (jsonResp) {
                    if (jsonResp.success) {
                        return jsonResp.data;
                    } else {
                        var code = jsonResp.error.code;
                        Ext.Msg.alert("Server Error" + code, "<b>" + jsonResp.error.description + "<b>");
                        return jsonResp;
                    }
                } else {
                    Ext.Msg.alert("Unexpected Server Error", "Unexpected error happened.");
                    return null;
                }
            },
            ajaxJson: function (method, url, json) {
                return new Ext.Promise(function (resolve, reject) {
                    Ext.Ajax.request({
                        url: url,
                        method: method,
                        scope: this,
                        jsonData: Ext.encode(json),
                        success: function (response) {
                            this.responseHandler(response)
                                .then((jsonResp) => {
                                    if (jsonResp.success) {
                                        resolve(jsonResp);
                                    } else {
                                        reject(jsonResp);
                                    }
                                })
                                .catch((error) => {
                                    reject(error);
                                });
                        },
                        failure: function (response) {
                            this.responseHandler(response)
                                .then((jsonResp) => {
                                    // this means a server side caught error with code != 200
                                    reject(jsonResp);
                                })
                                .catch((error) => {
                                    reject(error);
                                });
                        }
                    });
                });
            },
            makeAjaxRequest: function (config) {
                return new Promise(function (resolve, reject) {
                    Ext.Ajax.request({
                        url: config.url,
                        method: config.method || "GET",
                        jsonData:
                            config.jsonData && (config.method === "POST" || config.method === "PUT")
                                ? config.jsonData
                                : undefined,
                        success: function (response) {
                            try {
                                bcp.util.CommonUtil.ajaxSuccessHandler(response, function (result) {
                                    resolve(result); // Pass result if needed, otherwise just resolve()
                                });
                            } catch (e) {
                                console.log(`Exception while processing ajax return: ${e}`);
                                reject(response);
                            }
                        },
                        failure: function (response) {
                            reject(response);
                        },
                        scope: config.scope || this
                    });
                });
            }
        });

        //extends form fields for showing red * for required fields
        Ext.define("Overrides.form.field.Base", {
            override: "Ext.form.field.Base",

            getLabelableRenderData: function () {
                var me = this,
                    data = me.callParent(),
                    /*    labelClsExtra = me.labelClsExtra;

                if (!me.allowBlank) {
                    data.labelClsExtra = (labelClsExtra ? labelClsExtra + ' ' : '') + me.requiredCls;
                }
                */
                    labelSeparator = me.labelSeparator;

                //added readOnly check so displayfields won't all show as required
                //modified to not add * to checkbox since unselected checkbox does have value=false, not blank
                if (!me.readOnly && !me.allowBlank && me.xtype !== "checkboxfield") {
                    //data.beforeLabelTpl = '<span style="color:red">&nbsp;*</span> ';
                    data.labelSeparator = '<span style="color:red">&nbsp;*</span> ' + labelSeparator;
                }

                return data;
            }
        });

        Ext.define("bcp.util.DownloadFile", {
            requires: ["Ext.form.Panel"],
            singleton: true,

            download: function (config) {
                config = config || {};
                var url = config.url;
                //method = config.method || 'GET', // Either GET or POST. Default is POST.
                //params = config.params || {};

                //create a form
                var form = document.createElement("form");
                form.setAttribute("target", "_blank");
                form.method = "GET";
                form.action = url;

                //add param values
                //form.appendChild(bcp.util.CommonUtil.createFormInput("text","fileId",params.fileId));
                //form.appendChild(bcp.util.CommonUtil.createFormInput("text","token",params.token));

                //add the form
                document.body.appendChild(form);

                //submit the form
                form.submit();

                //remove the form after submit
                form.remove();
            }
        });

        /*Ext.state.Manager.setProvider(new Ext.state.CookieProvider({

            expires: new Date(new Date().getTime()+(1000*60*60*24*31)) //1 Month from now

        }));*/
        Ext.state.Manager.setProvider(Ext.create("Ext.state.LocalStorageProvider"));

        Ext.Ajax.request({
            url: bcp.config.Runtime.getServerBaseUrl() + "system/version",
            method: "GET",
            scope: this,
            success: function (response) {
                bcp.util.CommonUtil.ajaxSuccessHandler(response, function (result) {
                    if (!result.data) {
                        Ext.Msg.alert("System Error", "Application failed to load. Please try again later.");
                        return false;
                    } else {
                        var store = Ext.getStore("BcpAppVersion");
                        var obj = {};
                        if (store.count() > 0) {
                            var rec = store.first();
                            var cachedVersion = rec.get("version");

                            if (cachedVersion != result.data) {
                                store.removeAll();
                                //set new verison#
                                obj.version = result.data;

                                //set last used to be 31 minutes ago so the warning banner will show when app version is updated
                                var currentTime = new Date();
                                // Subtract 31 minutes (31 * 60 * 1000 milliseconds) from the current time
                                var olderTime = new Date(currentTime.getTime() - 31 * 60 * 1000);
                                obj.lastUsed = olderTime;

                                store.add(obj);
                                store.sync();
                                /*Ext.MessageBox.alert('New Version Found', 'There is a newer version available. Please click [Ok] to get the new version',
                                    function (btn, text) {
                                        location.reload();
                                    });
                                return;*/
                                Ext.MessageBox.show({
                                    title: "New Version Found",
                                    progressText: "Updating application...please wait",
                                    width: 300,
                                    progress: true,
                                    closable: false
                                });

                                //try to solve the issue when client code is updated, it takes two reloads for the changes to be loaded
                                if (navigator.serviceWorker) {
                                    navigator.serviceWorker.getRegistration().then(function (registration) {
                                        if (registration) {
                                            //console.log(registration.toString());
                                            registration
                                                .unregister()
                                                .then(function (success) {
                                                    // if success = true, unregister was successful
                                                    //console.log("service worker unregistered");
                                                })
                                                .then(function (cleanCache) {
                                                    if ("caches" in window) {
                                                        caches
                                                            .keys()
                                                            .then(function (keyList) {
                                                                return Promise.all(
                                                                    keyList.map(function (key) {
                                                                        //console.log(key);
                                                                        return caches.delete(key);
                                                                    })
                                                                );
                                                            })
                                                            .then(function (final) {
                                                                location.reload();
                                                            });
                                                    }
                                                });
                                        }
                                    });
                                }
                            } else {
                                //app version not changed

                                //OKTA related change
                                //save the time when users loaded and used the app
                                rec.set("lastUsed", new Date());
                                rec.save();
                                store.sync();
                            }
                        } else {
                            //no app version saved yet
                            obj.version = result.data;
                            obj.lastUsed = new Date();
                            store.add(obj);
                            store.sync();
                        }
                    }
                });
            },
            failure: function () {
                Ext.Msg.alert("System Error", "Application failed to load. Please try again later.");
                return false;
            }
        });

        Ext.route.Router.suspend();
        this.checkAuthUser();
    },

    checkAuthUser: function () {
        //users could click a url with hash to go directly to a subview; however, since the main homeview
        //is dynamically added after proper user login (getUserProfile) and its content is also dynamically generated
        //based on roles in the userprofile, we need to make sure the main homeview is ready before jumping to a subview
        //that may not exists yet
        var //me = this,
            ptcs = Ext.getStore("ProjectTaskCodes"),
            ptcss = Ext.getStore("ProjectTaskCodesSearch"),
            objcs = Ext.getStore("ObjectClasses"),
            staffs = Ext.getStore("OuAllStaffs"),
            //ouFeds = Ext.getStore('OuEmployees'),
            //divFeds = Ext.getStore('DivEmployees'),
            groups = Ext.getStore("Groups"),
            ous = Ext.getStore("Ous"),
            divs = Ext.getStore("Divisions"),
            supDivs = Ext.getStore("SupportedDivisions"),
            reviewers = Ext.getStore("Reviewers"),
            baos = Ext.getStore("Baos"),
            fcos = Ext.getStore("Fcos"),
            ouFcos = Ext.getStore("OuFcos"),
            divisionChiefs = Ext.getStore("DivisionChiefs"),
            bhs = Ext.getStore("BankcardHolders"),
            itsos = Ext.getStore("ItsoUsers"),
            ouRoles = Ext.getStore("OuRoles"),
            auStore = Ext.getStore("AuthUser"),
            routeStore = Ext.getStore("DefaultRoutes"),
            fyStore = Ext.getStore("Fys"),
            divPrefsStore = Ext.getStore("DivisionPreferences"),
            today = new Date(),
            currentYear = new Date().getFullYear(), //yr in 4 digits
            currentFy = Number(currentYear.toString().substr(-2)), //yr in 2 digits
            beginFy = 18, //when we start using the bankcard app
            //the date we allow select next FY
            //issue#578 change date early so users can access the nextFY in the dropdown in July instead of Sept
            createNextFyDate = new Date(new Date().getFullYear() + "-07-19T00:00:00-04:00"),
            //the date we disallow select next FY
            createNextFyEndDate = new Date(new Date().getFullYear() + "-10-01T00:00:00-04:00"),
            loggedInUser = auStore.first();
        //when app just launches, the user is not ready yet
        if (loggedInUser === null) {
            //call server to get user profile. It should work
            //since single sign-on prevent unauthenticated users from accessing the page. If it
            //failed somehow, redirect the user to login page
            try {
                Ext.MessageBox.show({
                    title: "Loading Data",
                    progressText: "Loading data...please wait",
                    width: 300,
                    progress: true,
                    closable: false
                });
                Ext.Ajax.request({
                    url: bcp.config.Runtime.getServerBaseUrl() + "users/profile",
                    disableCaching: false,
                    success: function (response) {
                        bcp.util.CommonUtil.ajaxSuccessHandler(response, function (result) {
                            var ret = result.data,
                                subject = "?subject=EMPBC Error",
                                body = "",
                                mailto = "";
                            try {
                                if (result.success) {
                                    auStore.loadRawData(ret.profile);
                                    //model.set('userRoles',ret.roles);
                                    Ext.getStore("UserRoles").loadRawData(ret.roles);

                                    //BNAK-545, store user's detailing org data
                                    if (ret.detailedPrivilege) {
                                        Ext.getStore("UserDetailedPrivileges").loadRawData(ret.detailedPrivilege);
                                    }

                                    if (ret.profile.delegating) {
                                        Ext.getStore("Delegates").loadRawData(ret.delegation.trueUser);
                                    } else {
                                        Ext.getStore("Delegates").loadRawData(ret.delegation.delegateAs);
                                    }

                                    //load detailee user into the store if detailee mode
                                    if (ret.profile.detaileeMode) {
                                        Ext.getStore("Detailees").loadRawData(ret.detailee);
                                    } else {
                                        Ext.getStore("Detailees").removeAll();
                                    }

                                    var df = Ext.create("bcp.model.NistOrgDefaultRoute", ret.defaultRoute);
                                    routeStore.add(df);

                                    //get side menu data
                                    var navStore = Ext.getStore("NavigationTree"),
                                        subviews = Ext.getStore("SubViews");

                                    //add admin role to the roles store if profile returns accessAdmin=true
                                    if (ret.profile.accessAdmin != true) {
                                        //remove admin menu if not admin
                                        v = navStore.findNode("text", "Admin");
                                        if (v) {
                                            v.remove();
                                            navStore.sync();
                                        }
                                    } else {
                                        Ext.getStore("UserRoles").insert(0, {
                                            name: "App Admin",
                                            id: 999,
                                            category: "AppSupport"
                                        });
                                    }
                                    //filter views not needed by NIST Associates
                                    if (ret.profile.staffType == "NIST Associate") {
                                        const nodesToRemove = [
                                            "Submitted",
                                            "Received",
                                            "Pending Actions",
                                            "Purchases",
                                            "Audit Report",
                                            "PC Report",
                                            "EA Report",
                                            "Reports",
                                            "Vendors",
                                            "Preferences"
                                        ];
                                        nodesToRemove.forEach((nodeText) => {
                                            const node = navStore.findNode("text", nodeText);
                                            if (node) {
                                                node.remove();
                                            }
                                        });

                                        navStore.sync();

                                        //remove subviews not needed
                                        subviews.remove(subviews.findRecord("routeId", "requesttracking"));
                                        subviews.remove(subviews.findRecord("routeId", "pendingrequests"));
                                        subviews.remove(subviews.findRecord("routeId", "archivedrequests"));
                                    }
                                    //filter views not needed by Bankcard Holders
                                    //NOTE: test for null because menu items maybe removed by block above already
                                    if (!bcp.util.CommonUtil.isUserInRole(["Bankcard Holder"])) {
                                        var pview = navStore.findNode("text", "Purchases");
                                        if (pview) {
                                            pview.remove();
                                            navStore.sync();
                                        }
                                    }
                                    //MB-455
                                    if (
                                        !bcp.util.CommonUtil.isUserInRole([
                                            "Administrative Officer",
                                            "Bankcard Holder",
                                            "Bankcard Approving Official"
                                        ])
                                    ) {
                                        if (navStore.findNode("text", "EA Report")) {
                                            navStore.findNode("text", "EA Report").remove();
                                        }
                                    }

                                    //Bank-488,506
                                    if (
                                        !bcp.util.CommonUtil.isUserInRole([
                                            "Administrative Officer",
                                            "Senior Management Advisor",
                                            "Executive Officer"
                                        ])
                                    ) {
                                        if (navStore.findNode("text", "Division")) {
                                            navStore.findNode("text", "Division").remove();
                                        }
                                    }

                                    if (!bcp.util.CommonUtil.isUserInRole(["Property Custodian"])) {
                                        if (navStore.findNode("text", "PC Report")) {
                                            navStore.findNode("text", "PC Report").remove();
                                        }
                                    }

                                    //the vendors management view is for these roles
                                    //to use because they can do CRUD to shared vendors
                                    if (
                                        !bcp.util.CommonUtil.isUserInRole([
                                            "Administrative Officer",
                                            "Senior Management Advisor",
                                            "Laboratory Office Manager",
                                            "Division Office Manager",
                                            "Group Office Manager",
                                            "Bankcard Holder",
                                            "Administrative Office Assistant"
                                        ])
                                    ) {
                                        var v = navStore.findNode("text", "Vendors");
                                        if (v) {
                                            v.remove();
                                            navStore.sync();
                                        }
                                    }

                                    //ou roles used to enforce rules for GL and above management requesters (detail emp won't need this)
                                    //since we use a non-management staff for the group to mimic to get approvers
                                    ouRoles.load();


                                    //load necessary org data
                                    groups.load();
                                    ous.load();
                                    divs.load();

                                    //supported divs for AOs
                                    supDivs.load();

                                    //for use ptc in search criteria
                                    ptcss.proxy.url = "/empbc/v1/projectTasks/allOU";
                                    ptcss.proxy.setTimeout(60000);
                                    ptcss.load();

                                    var ouCode = "";
                                    //make sure if detailee mode, ptc store were using the right OU param to load data
                                    if (ret.profile.detaileeMode) {
                                        ouCode = Ext.getStore("Detailees").first().get("ouCode");
                                    } else {
                                        ouCode = ret.profile.ouCode;
                                    }

                                    //ou specified ptcs anf ocs
                                    ptcs.proxy.url = "/empbc/v1/projectTasks/" + ouCode;
                                    ptcs.proxy.setTimeout(120000);
                                    ptcs.load();
                                    objcs.load();

                                    //ou specified staffs
                                    staffs.load();
                                    staffs.proxy.setTimeout(60000);
                                    //ou or div specified approvers
                                    reviewers.load();
                                    bhs.load();
                                    baos.load();

                                    //fcos.load();
                                    //ouFcos.load();
                                    bcp.util.CommonUtil.loadStore(fcos)
                                        .then(function (loadedFcosStore) {
                                            return bcp.util.CommonUtil.loadStore(ouFcos);
                                        })
                                        .then(function (loadedOuFcosStore) {
                                            // Create the new 'allFcos' store or get it if it already exists
                                            var allFcosStore = Ext.getStore("AllFcos");
                                            allFcosStore.removeAll(); // Clear any existing records

                                            // Add all records from fcosStore to allFcosStore
                                            // getRange() returns an array of records, which can be passed to add()
                                            if (fcos.getCount() > 0) {
                                                allFcosStore.add(fcos.getRange());
                                            }

                                            // Add all records from ouFcosStore to allFcosStore
                                            if (ouFcos.getCount() > 0) {
                                                allFcosStore.add(ouFcos.getRange());
                                            }
                                        })
                                        .catch(function (error) {
                                            // Handle any error that occurred in the loading chain
                                            console.error("An error occurred loading Fco data:", error);
                                        });

                                    divisionChiefs.load();
                                    itsos.load();

                                   
                                    //if allow requester to request for other division
                                    //then the div id should use request's divId rather than login user's divId
                                    //to make it easier, just load all divisions's prefs first using 0 or a negative num as the divId
                                    divPrefsStore.proxy.url = "/empbc/v1/nistOrgs/getDivPrefs/0";
                                    divPrefsStore.load();

                                    //if today is 10/1 or later, FY is in next FY
                                    if (today >= createNextFyEndDate) {
                                        currentFy++;
                                    }
                                    //create data for fy store startinf from FY18 to current FY
                                    for (var i = beginFy; i <= currentFy; i++) {
                                        fyStore.add({fy: i, display: "FY" + i});
                                    }
                                    //after the loop above, i = currentFy+1 = nextFY
                                    //between 9/15 and 10/1, we allow user to create req for next FY
                                    if (today >= createNextFyDate && today < createNextFyEndDate) {
                                        //i++;
                                        fyStore.add({fy: i, display: "FY" + i});
                                    }

                                    //create the warning banner window
                                    var warningWindow = Ext.create("bcp.view.WarningWindow", {
                                        title: appTitle
                                    });

                                    //set event listeners for the agreed button
                                    warningWindow.on({
                                        agreed: {
                                            fn: function () {
                                                warningWindow.close();
                                                Ext.create("bcp.view.AppContainer");
                                                //resume suspended router to allow navigation
                                                Ext.route.Router.resume();
                                            }
                                        },
                                        scope: this,
                                        single: true
                                    });

                                    var vstore = Ext.getStore("BcpAppVersion");

                                    var appTitle = "OU Bankcard Purchase Pre-Approval System";

                                    //if app version localstorage store has data
                                    if (vstore.count() > 0) {
                                        var rec = vstore.first();
                                        var cachedVersion = rec.get("version");
                                        //add app version to the app title
                                        appTitle = appTitle + " v" + cachedVersion;

                                        //OKTA related change
                                        //try to detemine whether to show the warning banner when app reload
                                        var lastUsedTime = rec.get("lastUsed");
                                        var currentTime = new Date();
                                        var timeDifference = currentTime - lastUsedTime;
                                        var thirtyMinutesInMilliseconds = 30 * 60 * 1000; // 30 minutes in milliseconds

                                        if (timeDifference > thirtyMinutesInMilliseconds) {
                                            // More than 30 minutes have passed
                                            // Show the banner
                                            warningWindow.show();
                                        } else {
                                            // Less than or equal to 30 minutes have passed
                                            // Do not show the warning banner, just resumes the route
                                            Ext.create("bcp.view.AppContainer");
                                            Ext.route.Router.resume();
                                        }
                                    } else {
                                        //nothing stored yet
                                        //code won't get here unless the ajax request to get app version failed for a user who never used the app before
                                        warningWindow.show();
                                    }
                                } else {
                                    console.log("auth result not succeed");
                                    //location.reload();
                                    /*
                                      Ext.MessageBox.hide();
                                      //API returns 200 response but with a custom error message
                                      subject = "?subject=EMPBC Error";
                                      body = "&body=" + Ext.htmlEncode(result.error.description);
                                      mailto = mailto + subject + body;
                                      Ext.Msg.alert('Error', "Unexpected error happened.<br>" +
                                          'Error Detail: <b>' + result.error.description + '<b><br>' +
                                          '<a href="' + mailto +
                                          '" ' + 'target="_blank">Please click here to report the error.</a>'
                                      );
                                      return;
                                      */
                                }

                                Ext.MessageBox.hide();
                            } catch (ex) {
                                Ext.MessageBox.hide();
                                subject = "?subject=EMPBC Error";
                                body = "&body=" + Ext.htmlEncode(ex.stack);
                                mailto = "mailto:MML.SystemsHelp@nist.gov" + subject + body;
                                Ext.Msg.alert(
                                    "Error",
                                    "Unexpected error happened.<br>" +
                                        ex.message +
                                        "<br>" +
                                        '<a href="' +
                                        mailto +
                                        '" ' +
                                        'target="_blank">Please click here to report the error.</a>'
                                );
                            }
                        });
                    },
                    /* failure: function (response) {
                         console.log("auth failed");
                         //redirect user to a login page which is not part of the extjs application
                         //offline now, use first record in mockup as logged in user
                         Ext.MessageBox.hide();
                         var subject = "?subject=EMPBC Error",
                             body = "&body=",
                             mailto = "mailto:MML.SystemsHelp@nist.gov";

                         try {
                             var jsonResp = Ext.decode(response.responseText);
                             body = body + Ext.htmlEncode(jsonResp.error.description);
                         } catch (ex) {
                             body = body + "error occurred when trying to get user profile.";
                         }

                         mailto = mailto + subject + body;
                         Ext.Msg.alert('Error', "Unexpected error happened.<br>" +
                             '<a href="' + mailto +
                             '" ' + 'target="_blank">Please click here to report the error.</a>'
                         );
                     },*/
                    scope: this
                });
            } catch (ex) {
                Ext.MessageBox.hide();
                var subject = "?subject=EMPBC Error",
                    body = "&body=" + Ext.htmlEncode(ex.stack),
                    mailto = "mailto:MML.SystemsHelp@nist.gov" + subject + body;
                Ext.Msg.alert(
                    "Error",
                    "Unexpected error happened while starting the application.<br>" +
                        ex.message +
                        "<br>" +
                        '<a href="' +
                        mailto +
                        '" ' +
                        'target="_blank">Please click here to report the error.</a>'
                );
            }
        } else {
            //code shouldn't be here since on app launch, no logged in user should be found in the session store
            Ext.route.Router.resume();
        }

        // do not execute queued hash changes
        //Ext.route.Router.resume(true);
        //this.redirectTo('login');
    }
});
