
  CREATE TABLE "BCPMS_OWNER"."NIST_GROUP" 
   (	"ORG_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"ORG_CD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ORG_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"EFFECTIVE_DT" DATE, 
	"ORG_ACRNM" VARCHAR2(6 BYTE), 
	"OU_ORG_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"DIV_ORG_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"ACTIVE_YN" CHAR(1 BYTE) NOT NULL ENABLE, 
	"LAST_UPDATE_DT" DATE NOT NULL ENABLE, 
	 CONSTRAINT "NIST_GROUP_PK" PRIMARY KEY ("ORG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BCPMS_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BCPMS_DATA" ;

  CREATE INDEX "BCPMS_OWNER"."IDX_GRP_ACTIVE_YN" ON "BCPMS_OWNER"."NIST_GROUP" ("ACTIVE_YN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BCPMS_DATA" ;

  CREATE INDEX "BCPMS_OWNER"."IDX_GRP_BDATE" ON "BCPMS_OWNER"."NIST_GROUP" ("EFFECTIVE_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BCPMS_DATA" ;

  CREATE INDEX "BCPMS_OWNER"."IDX_GRP_DIV_ID" ON "BCPMS_OWNER"."NIST_GROUP" ("DIV_ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BCPMS_DATA" ;

  CREATE INDEX "BCPMS_OWNER"."IDX_GRP_OU_ID" ON "BCPMS_OWNER"."NIST_GROUP" ("OU_ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BCPMS_DATA" ;

  CREATE INDEX "BCPMS_OWNER"."IDX_GRP_UPDT_DT" ON "BCPMS_OWNER"."NIST_GROUP" ("LAST_UPDATE_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BCPMS_DATA" ;


  GRANT SELECT ON "BCPMS_OWNER"."NIST_GROUP" TO "ADMIN_PORTAL_OWNER";
  GRANT SELECT ON "BCPMS_OWNER"."NIST_GROUP" TO "BCPMS_APP";
  GRANT SELECT ON "BCPMS_OWNER"."NIST_GROUP" TO "BCPMS_READ";
